export interface OracleFlavorPhrase {
  pt: string;
  en: string;
}

// Banco de frases características de cada oráculo, agrupadas por humor,
// mostradas num balão junto ao selo do oráculo (MovieDetailsModal).
//
// IMPORTANTE: essas chaves usam o mesmo nome (camelCase) das chaves de
// tradução oracle.moods.* — mas o banco de dados guarda mood_key em outro
// formato (com hífen: 'dark-and-scary', 'drug-trip', etc). O mapa
// DB_MOOD_TO_PHRASE_KEY faz essa ponte.
export const ORACLE_FLAVOR_PHRASES: Record<string, Record<string, OracleFlavorPhrase[]>> = {
  bogart: {
    mindBlowing: [
      { pt: 'Esse aqui vira sua cabeça do avesso e ainda cobra reentrada.', en: 'This one turns your head inside out and still charges for a return trip.' },
      { pt: 'Não tenta entender de primeira. Ninguém entendeu.', en: 'Don\'t try to get it the first time. Nobody did.' },
      { pt: 'Depois desse, você sai da sala uma pessoa levemente diferente.', en: 'After this one, you leave the room a slightly different person.' },
      { pt: 'Lógica é ótima. Aqui ela não vai te ajudar em nada.', en: 'Logic is great. Here, it won\'t help you one bit.' },
      { pt: 'Pausa se precisar. Ninguém vai julgar. Eu já pausei três vezes.', en: 'Pause if you need to. No one will judge. I paused three times myself.' },
      { pt: 'Esse filme não te dá respostas, te dá mais perguntas caras de resolver.', en: 'This film doesn\'t give you answers, it gives you pricier questions.' },
      { pt: 'Sucesso de bilheteria com cara de experimento de laboratório. Combinação rara.', en: 'Box office hit with the face of a lab experiment. Rare combo.' },
      { pt: 'Assiste uma vez pra curtir, assiste de novo pra entender o que curtiu.', en: 'Watch it once to enjoy, watch it again to understand what you enjoyed.' },
      { pt: 'Esse sofá é confortável. Sua cabeça, depois disso, não vai ser mais.', en: 'This couch is comfortable. Your head, after this, won\'t be anymore.' },
      { pt: 'Tem filme que te entretém. Esse aqui te reprograma.', en: 'Some movies entertain you. This one reprograms you.' },
    ],
    adrenaline: [
      { pt: 'Cinto apertado. Esse aqui não dá tempo pra pipoca esfriar.', en: 'Buckle up. This one doesn\'t give your popcorn time to go cold.' },
      { pt: 'Batimento acelerado é normal. Se não acelerou, procura um médico.', en: 'Racing heartbeat is normal. If it didn\'t race, see a doctor.' },
      { pt: 'Esse filme não pausa pra explicar nada. Ou acompanha, ou fica pra trás.', en: 'This film doesn\'t pause to explain anything. Keep up or get left behind.' },
      { pt: 'Blockbuster de verdade, do tipo que ainda sabe o que é tensão.', en: 'A real blockbuster, the kind that still knows what tension means.' },
      { pt: 'Levanta do sofá se conseguir. Eu não consegui.', en: 'Get up off the couch if you can. I couldn\'t.' },
      { pt: 'Esse ritmo aí a Cobra ia achar bonitinho demais. Mas pra gente, já é o suficiente.', en: 'The Snake would find this pace way too tame. But for us, it\'s plenty.' },
      { pt: 'Ação com orçamento e com propósito. Rara combinação essa.', en: 'Action with a budget and a purpose. Rare combination, that.' },
      { pt: 'Não é o tipo de filme que você assiste. É o tipo que você sobrevive.', en: 'Not the kind of movie you watch. The kind you survive.' },
      { pt: 'Todo mundo saiu do cinema com o coração dois andares mais alto.', en: 'Everyone left the theater with their heart two floors higher.' },
      { pt: 'Esse aqui é pipoca com adrenalina misturada no óleo.', en: 'This one\'s popcorn with adrenaline mixed into the oil.' },
    ],
    adventures: [
      { pt: 'Pega sua mochila imaginária. Essa jornada vale a viagem.', en: 'Grab your imaginary backpack. This journey is worth the trip.' },
      { pt: 'Tem filme que te leva pra outro lugar. Esse aqui te leva pra outro mundo.', en: 'Some movies take you somewhere else. This one takes you to another world.' },
      { pt: 'Épico de verdade, do tipo que ainda acredita em final feliz merecido.', en: 'A real epic, the kind that still believes in an earned happy ending.' },
      { pt: 'Esse filme tem escala de mapa e coração do tamanho do mapa também.', en: 'This film has a map-sized scale and a heart just as big.' },
      { pt: 'Sofá vira tapete mágico por duas horas. Aproveita a viagem.', en: 'The couch becomes a magic carpet for two hours. Enjoy the ride.' },
      { pt: 'Grandioso sem ser bobo. Isso já é raro o suficiente pra recomendar.', en: 'Grand without being silly. That alone is rare enough to recommend.' },
      { pt: 'Esse aqui tem tudo: perigo, descoberta e uma trilha sonora que gruda.', en: 'This one has it all: danger, discovery, and a score that sticks.' },
      { pt: 'Cansei só de assistir. E olha que eu nem levantei do sofá.', en: 'I got tired just watching. And I didn\'t even leave the couch.' },
      { pt: 'Aventura popular, dessas que enchem sala e ainda merecem encher.', en: 'Popular adventure, the kind that fills theaters and actually deserves to.' },
      { pt: 'Bilheteria alta, ambição maior ainda. Combinação que funciona.', en: 'High box office, even higher ambition. A combo that works.' },
    ],
    darkScary: [
      { pt: 'Deixa a luz acesa. Não por mim, por você mesmo.', en: 'Leave the light on. Not for me, for yourself.' },
      { pt: 'Vi coisa pior que esse filme em quarenta anos de sofá. Mas não muita coisa.', en: 'I\'ve seen worse than this film in forty years on this couch. But not much worse.' },
      { pt: 'Esse aqui não te assusta com susto barato. Te assusta com ideia.', en: 'This one doesn\'t scare you with a cheap jump. It scares you with an idea.' },
      { pt: 'Tem medo antigo que a gente carrega antes mesmo de nascer. Esse filme sabe disso.', en: 'There\'s an ancient fear we carry before we\'re even born. This film knows it.' },
      { pt: 'Terror popular, do bom, do que ainda assombra depois dos créditos.', en: 'Popular horror, the good kind, the kind that still haunts after the credits.' },
      { pt: 'Dorme com a porta trancada hoje. Depois me agradece.', en: 'Sleep with the door locked tonight. Thank me later.' },
      { pt: 'Já vi esse escuro antes, num sonho ruim de décadas atrás. Ele voltou.', en: 'I\'ve seen this darkness before, in a bad dream from decades ago. It came back.' },
      { pt: 'Sucesso de bilheteria e pesadelo garantido. Combinação rara e eficiente.', en: 'Box office hit and guaranteed nightmare. A rare and efficient combo.' },
      { pt: 'Esse filme não pede desculpa por te deixar mal. Ele nem devia.', en: 'This film doesn\'t apologize for messing you up. It shouldn\'t have to.' },
      { pt: 'Sapo velho reconhece medo de longe. Esse aqui, eu senti da porta da sala.', en: 'An old frog recognizes fear from a distance. This one, I felt from the doorway.' },
    ],
    romantic: [
      { pt: 'Prepara o lenço. Não pro choro, pro suor da mão de tanta emoção.', en: 'Get a tissue ready. Not for crying, for the sweaty palms from all the feeling.' },
      { pt: 'Amor de verdade, do tipo que a gente torce mesmo sabendo que vai doer.', en: 'Real love, the kind you root for even knowing it\'s going to hurt.' },
      { pt: 'Esse filme não é piegas. É só sincero, o que hoje em dia parece piegas.', en: 'This film isn\'t sappy. It\'s just sincere, which nowadays looks sappy.' },
      { pt: 'Casal de cinema desses, a gente não esquece nem querendo.', en: 'A movie couple like this, you don\'t forget even if you try.' },
      { pt: 'Romance popular que não insulta sua inteligência. Raridade e tanto.', en: 'Popular romance that doesn\'t insult your intelligence. Quite the rarity.' },
      { pt: 'Vai fazer você ligar pra alguém depois. Não diz que eu não avisei.', en: 'This is going to make you call someone afterward. Don\'t say I didn\'t warn you.' },
      { pt: 'Final feliz? Talvez. Final sincero? Com certeza.', en: 'Happy ending? Maybe. Honest ending? Definitely.' },
      { pt: 'Esse aqui prova que química na tela ainda existe, e ainda funciona.', en: 'This one proves on-screen chemistry still exists, and it still works.' },
      { pt: 'Bilheteria de romance que faz jus ao gênero. Vale o abraço no sofá.', en: 'Romance box office numbers that do the genre justice. Worth the couch cuddle.' },
      { pt: 'Sapo velho não chora fácil. Nesse aqui, quase.', en: 'An old frog doesn\'t cry easily. With this one, almost.' },
    ],
    familyTime: [
      { pt: 'Chama todo mundo pro sofá. Esse aqui é pra assistir junto mesmo.', en: 'Call everyone to the couch. This one\'s meant to be watched together.' },
      { pt: 'Criança ri, adulto se emociona escondido. Fórmula perfeita.', en: 'Kids laugh, adults get emotional on the sly. Perfect formula.' },
      { pt: 'Esse filme é gostoso igual chocolate quente. Aquece sem enjoar.', en: 'This film is as cozy as hot chocolate. Warms you up without overdoing it.' },
      { pt: 'Sucesso de bilheteria que a família inteira concorda. Isso já é milagre.', en: 'A box office hit the whole family agrees on. That alone is a miracle.' },
      { pt: 'Lição sem sermão. Assim que se ensina algo direito.', en: 'A lesson without a lecture. That\'s how you teach something right.' },
      { pt: 'Esse aqui vira clássico de domingo à tarde na sua casa. Confia.', en: 'This one becomes your house\'s Sunday afternoon classic. Trust me.' },
      { pt: 'Pipoca extra pra essa sessão. Vale o filme inteiro em pé aplaudindo.', en: 'Extra popcorn for this session. Worth a full standing ovation.' },
      { pt: 'Diverte sem infantilizar. Respeita quem assiste, seja qual for a idade.', en: 'Entertains without dumbing down. Respects the viewer, whatever their age.' },
      { pt: 'Esse filme é daqueles que três gerações assistem e todas gostam por motivos diferentes.', en: 'This is the kind of film three generations watch and each likes for different reasons.' },
      { pt: 'Sapo velho aprova. E olha que eu sou difícil de agradar depois de tanto sofá.', en: 'Old frog approves. And I\'m hard to please after this much couch time.' },
    ],
    laughOutLoud: [
      { pt: 'Separa um tempo pra rir sem vergonha. Esse aqui não perdoa.', en: 'Set aside some time to laugh without shame. This one shows no mercy.' },
      { pt: 'Comédia popular que ainda arranca risada de verdade, não só sorrisinho educado.', en: 'Popular comedy that still gets real laughs, not just polite smiles.' },
      { pt: 'Esse filme é tipo pipoca: começa uma cena e você já quer a próxima.', en: 'This film is like popcorn: one scene starts and you already want the next.' },
      { pt: 'Ri até doer a barriga. Depois ri de novo porque doeu.', en: 'Laugh until it hurts. Then laugh again because it hurt.' },
      { pt: 'Timing de piada impecável. Isso não se ensina em escola nenhuma.', en: 'Impeccable comic timing. You can\'t teach that in any school.' },
      { pt: 'Bilheteria de comédia que não envelheceu mal. Raridade e tanto no gênero.', en: 'A comedy box office hit that didn\'t age badly. Quite the rarity in the genre.' },
      { pt: 'Esse aqui é antídoto pra dia ruim. Receita simples, efeito garantido.', en: 'This one\'s an antidote for a bad day. Simple recipe, guaranteed effect.' },
      { pt: 'Elenco com química de sobra. Risada contagia, e aqui contagia rápido.', en: 'Cast with chemistry to spare. Laughter is contagious, and here it spreads fast.' },
      { pt: 'Leve, popular e engraçado sem ser bobo. Combinação rara de achar.', en: 'Light, popular, and funny without being dumb. A rare combo to find.' },
      { pt: 'Sapo velho não ri fácil. Nesse aqui, gargalhei feio.', en: 'Old frog doesn\'t laugh easily. With this one, I cackled ugly.' },
    ],
    drugTrip: [
      { pt: 'Não precisa de nada além de um sofá confortável pra essa viagem. Palavra de sapo.', en: 'You don\'t need anything but a comfy couch for this trip. Frog\'s word.' },
      { pt: 'Esse filme mexe com a cabeça sem pedir licença. E ainda faz sucesso de bilheteria.', en: 'This film messes with your head without asking permission. And it\'s still a box office hit.' },
      { pt: 'Visual que hipnotiza, roteiro que confunde de propósito. Funciona direitinho.', en: 'Visuals that hypnotize, a script that confuses on purpose. Works just fine.' },
      { pt: 'A Cobra ia adorar esse aqui. Mas garanto, popular como é, também merece seu tempo.', en: 'The Snake would love this one. But trust me, popular as it is, it still deserves your time.' },
      { pt: 'Esse filme não segue as regras do tempo nem do espaço. Só senta e aceita.', en: 'This film doesn\'t follow the rules of time or space. Just sit back and accept it.' },
      { pt: 'Sensorial de doer. Isso aqui é experiência, não só filme.', en: 'Sensory overload in the best way. This is an experience, not just a film.' },
      { pt: 'Bilheteria alta pra um filme desse tanto estranho. O público topou a viagem.', en: 'High box office for something this strange. The audience signed up for the trip.' },
      { pt: 'Esse aqui você não assiste, você atravessa.', en: 'This one you don\'t watch, you go through it.' },
      { pt: 'Trilha sonora e imagem grudam na sua cabeça por dias. Consideração pra quem tem compromisso amanhã.', en: 'Soundtrack and imagery stick in your head for days. Fair warning if you\'ve got plans tomorrow.' },
      { pt: 'Sapo velho viu muita coisa estranha nesse sofá. Esse filme ainda me surpreendeu.', en: 'Old frog has seen plenty of strange things on this couch. This film still surprised me.' },
    ],
    catharsis: [
      { pt: 'Esse filme não quer te fazer feliz. Quer te fazer sentir alguma coisa de verdade.', en: 'This film doesn\'t want to make you happy. It wants to make you feel something real.' },
      { pt: 'Prepara o peito pra apertar. Não tem como sair ileso desse.', en: 'Brace your chest for tightness. There\'s no leaving this one unscathed.' },
      { pt: 'Chorei igual não choro há anos. E olha que eu já vi muita coisa desse sofá.', en: 'I cried like I haven\'t in years. And I\'ve seen plenty from this couch.' },
      { pt: 'Esse filme dói de um jeito bom. Existe esse tipo de dor, e é esse aqui.', en: 'This film hurts in a good way. That kind of pain exists, and this is it.' },
      { pt: 'Sucesso de bilheteria que também sabe partir seu coração com classe.', en: 'A box office hit that also knows how to break your heart with class.' },
      { pt: 'Não é filme leve. Mas é filme necessário. Tem diferença.', en: 'Not a light film. But a necessary one. There\'s a difference.' },
      { pt: 'Depois desse, você vai precisar de um tempo antes de assistir qualquer outra coisa.', en: 'After this one, you\'ll need a moment before watching anything else.' },
      { pt: 'Esse filme te esvazia pra depois te encher de novo, diferente.', en: 'This film empties you out just to fill you back up, different.' },
      { pt: 'Elenco entregando tudo que tinha. Dá pra sentir cada centímetro disso na tela.', en: 'A cast giving everything they had. You can feel every inch of it on screen.' },
      { pt: 'Sapo velho não se emociona fácil depois de tantas décadas de sofá. Esse me pegou.', en: 'Old frog doesn\'t get emotional easily after this many decades on the couch. This one got me.' },
    ],
  },
  fincher: {
    catharsis: [
      { pt: 'Chorar é opcional. Sair diferente da sala, não é.', en: 'Crying is optional. Leaving the room a different person is not.' },
      { pt: 'Filme antigo tem uma vantagem: ninguém mais lembra como dói. Vou te lembrar.', en: 'Old films have one advantage: everyone forgot how much they hurt. Let me remind you.' },
      { pt: 'Já vi gente dura chorar com esse. Você não vai ser exceção.', en: 'I\'ve seen tough people cry at this one. You won\'t be the exception.' },
      { pt: 'Esse aqui não pede desculpa por ser difícil de assistir. Ele nem devia.', en: 'This one doesn\'t apologize for being hard to watch. It shouldn\'t have to.' },
      { pt: 'Clássico e devastador. A combinação favorita de quem gosta de sofrer bem.', en: 'Classic and devastating. The favorite combo for those who like to suffer well.' },
      { pt: 'Bilheteria alta na época, e ainda assim ninguém saiu ileso da sala.', en: 'High box office back in the day, and still nobody left the theater unscathed.' },
      { pt: 'Se prepara. Esse não é filme, é confissão em forma de roteiro.', en: 'Brace yourself. This isn\'t a film, it\'s a confession dressed up as a script.' },
      { pt: 'Um clássico desses só existe porque alguém teve coragem de doer de propósito.', en: 'A classic like this only exists because someone had the guts to hurt on purpose.' },
      { pt: 'Vai te esvaziar por dentro. E, de alguma forma, você vai agradecer por isso.', en: 'It\'s going to hollow you out. And somehow, you\'ll be grateful for it.' },
      { pt: 'Eu já vi esse filme mais vezes do que confesso. Ainda funciona toda vez.', en: 'I\'ve watched this one more times than I\'ll admit. Still works every time.' },
    ],
    drugTrip: [
      { pt: 'Filme antigo mexendo com sua cabeça de um jeito que o CGI moderno nem sonha em imitar.', en: 'An old film messing with your head in a way modern CGI wouldn\'t dream of matching.' },
      { pt: 'Isso aqui foi feito antes de existir botão de pausa pra você respirar. Sofre em silêncio.', en: 'This was made before pause buttons existed for you to catch your breath. Suffer in silence.' },
      { pt: 'Cult desde o primeiro dia. Ninguém entendeu na época, e é exatamente por isso que funciona.', en: 'Cult since day one. Nobody got it back then, and that\'s exactly why it works.' },
      { pt: 'A Cobra ia babar nesse aqui. Mas eu vi primeiro, e vou recomendar do meu jeito.', en: 'The Snake would drool over this one. But I saw it first, and I\'ll recommend it my way.' },
      { pt: 'Sem efeito especial de hoje, só câmera, montagem e a insanidade de quem dirigiu.', en: 'No modern special effects, just camera, editing, and the insanity of whoever directed it.' },
      { pt: 'Esse filme não envelheceu. Ele só ficou mais estranho com o tempo, o que é elogio.', en: 'This film didn\'t age. It just got stranger with time, which is a compliment.' },
      { pt: 'Bilheteria mediana na época, culto obsessivo depois. História clássica de filme mal compreendido.', en: 'Mediocre box office back then, obsessive cult following since. Classic tale of a misunderstood film.' },
      { pt: 'Assista sóbrio pra provar um ponto. Depois me conta se conseguiu.', en: 'Watch it sober to prove a point. Then tell me if you managed.' },
      { pt: 'Tem gente que jura que esse filme prevê o futuro. Eu só acho que ele prevê ressaca.', en: 'Some people swear this film predicts the future. I just think it predicts a hangover.' },
      { pt: 'Isso aqui é experimento de laboratório disfarçado de entretenimento. Aproveita a cobaia que é você.', en: 'This is a lab experiment disguised as entertainment. Enjoy being the test subject.' },
    ],
    laughOutLoud: [
      { pt: 'Comédia antiga tem uma vantagem: ninguém tinha medo de ser engraçado de verdade.', en: 'Old comedies have one advantage: nobody was afraid to actually be funny.' },
      { pt: 'Esse roteiro é afiado igual navalha. E ninguém se corta, só ri.', en: 'This script is sharp as a razor. And nobody bleeds, they just laugh.' },
      { pt: 'Timing perfeito, elenco impecável. Comédia como ela deveria continuar sendo feita.', en: 'Perfect timing, flawless cast. Comedy as it should still be made.' },
      { pt: 'Clássico de bilheteria que ainda arranca risada décadas depois. Isso é durabilidade.', en: 'A box office classic that still gets laughs decades later. That\'s durability.' },
      { pt: 'Piada boa não precisa de efeito especial. Precisa só de um roteirista competente.', en: 'A good joke doesn\'t need special effects. It just needs a competent writer.' },
      { pt: 'Esse filme envelheceu melhor que muita gente que trabalhou nele.', en: 'This film aged better than a lot of people who worked on it.' },
      { pt: 'Rir sem CGI, sem grito, sem meme. Só diálogo bom. Coisa rara hoje.', en: 'Laughing without CGI, without shouting, without memes. Just good dialogue. Rare thing nowadays.' },
      { pt: 'Sucesso na época, referência até hoje. A comédia raramente envelhece tão bem assim.', en: 'A hit back then, a reference to this day. Comedy rarely ages this well.' },
      { pt: 'Esse elenco tinha química de sobra. Dá pra sentir até pela poeira da fita.', en: 'This cast had chemistry to spare. You can feel it even through the tape\'s dust.' },
      { pt: 'Eu, rindo de um filme velho? Acontece mais do que eu gostaria de admitir.', en: 'Me, laughing at an old film? Happens more than I\'d like to admit.' },
    ],
    familyTime: [
      { pt: 'Família antiga de cinema não tinha CGI pra esconder problema. Só atuação boa mesmo.', en: 'Old movie families didn\'t have CGI to hide problems. Just good acting.' },
      { pt: 'Esse clássico ensinou mais gente a amar cinema do que qualquer aula de escola.', en: 'This classic taught more people to love cinema than any school class.' },
      { pt: 'Bilheteria de época que ainda passa no Natal de alguém, todo ano, sem falha.', en: 'A period box office hit that still airs at someone\'s Christmas every year, without fail.' },
      { pt: 'Sabe aquele cheiro de fita VHS gasta de tanto rebobinar? Esse filme é esse cheiro.', en: 'You know that smell of a VHS tape worn out from rewinding? This film is that smell.' },
      { pt: 'Geração inteira cresceu citando esse filme sem nem saber a origem da frase.', en: 'A whole generation grew up quoting this film without even knowing where the line came from.' },
      { pt: 'Clássico cult que virou tradição de família sem ninguém decidir formalmente isso.', en: 'A cult classic that became a family tradition without anyone formally deciding so.' },
      { pt: 'Curioso como todo filme de família antigo tem uma cena que assusta as crianças até hoje. Esse não é diferente.', en: 'Funny how every old family film has one scene that still scares kids today. This one\'s no different.' },
      { pt: 'Direção competente, roteiro sem preguiça. Isso já bastava, e ainda basta.', en: 'Competent direction, no lazy writing. That was enough back then, and it still is.' },
      { pt: 'Esse filme sobreviveu a décadas de remake ruim tentando substituí-lo. Continua invicto.', en: 'This film survived decades of bad remakes trying to replace it. Still undefeated.' },
      { pt: 'Elenco pequeno, produção modesta, resultado gigante. A matemática do cinema clássico nunca fez muito sentido, e é exatamente por isso que funciona.', en: 'Small cast, modest production, massive result. Classic cinema math never quite added up, and that\'s exactly why it works.' },
    ],
    darkScary: [
      { pt: 'Terror antigo, de quando o medo vinha do silêncio e não de barulho alto no ouvido.', en: 'Old-school horror, from when fear came from silence, not a loud noise in your ear.' },
      { pt: 'Clássico do gênero. Assustou uma geração inteira sem precisar de um único jump scare barato.', en: 'A genre classic. Terrified an entire generation without a single cheap jump scare.' },
      { pt: 'Esse filme foi banido em alguns lugares na época. Hoje eu entendo perfeitamente o motivo.', en: 'This film was banned in some places back then. Today I completely understand why.' },
      { pt: 'Esse aqui não pede desculpa por incomodar. Foi feito pra incomodar mesmo, e ainda incomoda décadas depois.', en: 'This one doesn\'t apologize for being disturbing. It was made to disturb, and it still does, decades later.' },
      { pt: 'Cult desde a estreia. Ninguém foi ao cinema preparado, e ninguém saiu de lá do mesmo jeito.', en: 'Cult status since its premiere. Nobody went to the theater prepared, and nobody left the same.' },
      { pt: 'Direção que constrói tensão como quem tem todo o tempo do mundo. E o resultado assusta mais por isso.', en: 'Direction that builds tension like it has all the time in the world. And it\'s scarier for it.' },
      { pt: 'Bilheteria modesta na época, terror cultuado até hoje. Nem todo clássico precisa de sucesso imediato.', en: 'Modest box office back then, cult horror ever since. Not every classic needs immediate success.' },
      { pt: 'Esse filme não usa sangue pra assustar. Usa a sua própria imaginação contra você, e funciona melhor.', en: 'This film doesn\'t use blood to scare you. It uses your own imagination against you, and it works better.' },
      { pt: 'Fã de terror categórico afirma que esse é obrigatório. Eu, cético por natureza, concordo pra variar.', en: 'Die-hard horror fans call this one mandatory viewing. Me, a natural skeptic, I agree for once.' },
      { pt: 'Trilha sonora mínima, tensão máxima. A raposa aprende bastante sobre paciência assistindo isso.', en: 'Minimal score, maximum tension. The fox learns a lot about patience watching this one.' },
    ],
    romantic: [
      { pt: 'Romance antigo, quando beijo na tela ainda significava alguma coisa e não só contrato de marketing.', en: 'Old-school romance, back when an on-screen kiss actually meant something and wasn\'t just a marketing contract.' },
      { pt: 'Esse casal tem mais química num olhar do que a maioria tem em dois filmes inteiros hoje em dia.', en: 'This couple has more chemistry in one glance than most have in two whole films nowadays.' },
      { pt: 'Clássico do gênero. Chorei? Não vou confirmar nem negar.', en: 'A genre classic. Did I cry? I\'ll neither confirm nor deny.' },
      { pt: 'Diálogo bem escrito seduz mais que qualquer efeito visual. Esse filme prova isso sem esforço.', en: 'Well-written dialogue seduces more than any visual effect. This film proves it effortlessly.' },
      { pt: 'Bilheteria de época, referência até hoje. Poucos romances envelhecem tão bem quanto esse.', en: 'Period box office hit, still a reference today. Few romances age this well.' },
      { pt: 'Final agridoce de dar inveja em roteirista moderno, que ainda acha que precisa explicar tudo.', en: 'A bittersweet ending that would make modern screenwriters jealous, the ones who still think they need to explain everything.' },
      { pt: 'Esse filme não precisa de trilha sonora exagerada pra te emocionar. Ele já é bom sozinho.', en: 'This film doesn\'t need an overblown score to move you. It\'s already good on its own.' },
      { pt: 'Romance cult que provou que nem todo final feliz precisa ser óbvio.', en: 'A cult romance that proved not every happy ending needs to be obvious.' },
      { pt: 'Casal icônico. Tão icônico que hoje viraria meme, e isso não diminui em nada o valor.', en: 'An iconic couple. So iconic they\'d be a meme today, which takes nothing away from its value.' },
      { pt: 'Direção sutil, atuação contida. A raposa aprecia esse tipo de contenção, mesmo sem ter fama de sentimental.', en: 'Subtle direction, restrained acting. The fox appreciates this kind of restraint, even without a reputation for sentimentality.' },
    ],
    adventures: [
      { pt: 'Aventura de época, quando efeito prático significava alguém realmente se pendurando de um penhasco.', en: 'Period adventure, back when a practical effect meant someone actually hanging off a cliff.' },
      { pt: 'Esse filme definiu o gênero por décadas. Copiado inúmeras vezes, igualado poucas.', en: 'This film defined the genre for decades. Copied countless times, matched rarely.' },
      { pt: 'Bilheteria estrondosa na época. E olha que não tinha nem CGI pra ajudar a impressionar.', en: 'Massive box office back then. And it didn\'t even have CGI to help impress.' },
      { pt: 'Herói clássico, daqueles que resolvia problema com carisma e não com dez minutos de explicação.', en: 'A classic hero, the kind who solved problems with charisma, not ten minutes of exposition.' },
      { pt: 'Trilha sonora tão icônica que você reconhece três notas e já sabe exatamente qual filme é.', en: 'A score so iconic you recognize three notes and instantly know exactly which film it is.' },
      { pt: 'Esse filme envelheceu tão bem que enganosamente parece mais moderno que muito lançamento recente.', en: 'This film aged so well it deceptively looks more modern than a lot of recent releases.' },
      { pt: 'Cult e sucesso comercial ao mesmo tempo. Combinação rara que a raposa aprecia com carinho.', en: 'Cult status and commercial success at the same time. A rare combo the fox appreciates dearly.' },
      { pt: 'Curioso como toda grande aventura clássica tem um vilão mais carismático que o próprio herói. Esse não foge à regra.', en: 'Funny how every great classic adventure has a villain more charismatic than the hero. This one\'s no exception.' },
      { pt: 'Escala grandiosa feita com recurso limitado. Isso aqui é criatividade forçada a aparecer.', en: 'Grand scale made with limited resources. This is creativity forced to show up.' },
      { pt: 'Assisti esse filme tantas vezes que consigo recitar o roteiro. Não vou fazer isso, mas consigo.', en: 'I\'ve watched this film so many times I could recite the script. Won\'t do it, but I could.' },
    ],
    mindBlowing: [
      { pt: 'Filme antigo mexendo com narrativa de um jeito que Hollywood moderna ainda tem medo de tentar.', en: 'An old film messing with narrative in a way modern Hollywood is still afraid to try.' },
      { pt: 'Estrutura não-linear antes de ser moda. Esse filme fez e a crítica não sabia nem como reagir.', en: 'Non-linear structure before it was trendy. This film did it and critics didn\'t even know how to react.' },
      { pt: 'Assista uma vez pra se perder. Assista de novo pra perceber que estava tudo ali desde o início.', en: 'Watch it once to get lost. Watch it again to realize it was all there from the start.' },
      { pt: 'Cult instantâneo. Bilheteria discreta, influência gigantesca. História clássica de filme à frente do próprio tempo.', en: 'Instant cult classic. Modest box office, massive influence. Classic tale of a film ahead of its time.' },
      { pt: 'Roteiro que confia na sua inteligência. Coisa rara hoje, coisa rara também naquela época, pra ser sincero.', en: 'A script that trusts your intelligence. Rare thing today, rare thing back then too, to be honest.' },
      { pt: 'Prefiro filme que me deixa confuso de propósito a filme que me explica tudo com desenho e seta.', en: 'I\'d rather a film leave me confused on purpose than one that explains everything with a diagram and an arrow.' },
      { pt: 'Final que você discute por anos com quem assistiu junto. Ainda não chegamos a um consenso, aliás.', en: 'An ending you debate for years with whoever watched it with you. Still haven\'t reached a consensus, by the way.' },
      { pt: 'Montagem que quebra as regras que ninguém tinha nem escrito ainda. Ousadia pura.', en: 'Editing that broke rules nobody had even written yet. Pure audacity.' },
      { pt: 'Esse filme foi mal compreendido na estreia. Hoje é citado como obra-prima. A crítica também erra, vira e mexe.', en: 'This film was misunderstood on release. Today it\'s cited as a masterpiece. Critics get it wrong too, every now and then.' },
      { pt: 'Poucos filmes te fazem questionar o que você acabou de ver por dias. Esse é um deles, e eu ainda questiono.', en: 'Few films make you question what you just watched for days. This is one of them, and I still question it.' },
    ],
    adrenaline: [
      { pt: 'Gravado quando o cinema ainda tinha alma, e atores que fumavam até nos créditos.', en: 'Filmed when cinema still had a soul, and actors who smoked through the credits.' },
      { pt: 'Perseguição de carro sem CGI. Isso ali é aço de verdade batendo em aço de verdade.', en: 'A car chase without CGI. That\'s real steel hitting real steel.' },
      { pt: 'Ação clássica, do tipo que não precisa de dez cortes por segundo pra parecer rápida.', en: 'Classic action, the kind that doesn\'t need ten cuts per second to feel fast.' },
      { pt: 'Bilheteria estrondosa na época. Hoje ainda ensina roteirista novo como se faz tensão.', en: 'Massive box office back then. Still teaches new screenwriters how tension is done today.' },
      { pt: 'Esse filme não usa trilha sonora pra dizer quando ficar tenso. Você sente sozinho, e é melhor assim.', en: 'This film doesn\'t use score cues to tell you when to feel tense. You feel it on your own, and it\'s better that way.' },
      { pt: 'Dublê de verdade, risco de verdade. Hoje chamariam isso de insanidade. Eu chamo de cinema.', en: 'Real stuntman, real risk. Today they\'d call this insanity. I call it filmmaking.' },
      { pt: 'Curioso como todo grande filme de ação clássico tem uma cena de perseguição que virou referência obrigatória em qualquer lista. Esse não é diferente.', en: 'Funny how every great classic action film has a chase scene that becomes mandatory reference in any list. This one\'s no different.' },
      { pt: 'Herói durão sem precisar gritar frase de efeito a cada cinco minutos. Menos é mais, sempre foi.', en: 'A tough hero who doesn\'t need to shout a catchphrase every five minutes. Less is more, always was.' },
      { pt: 'Ritmo que não dá respiro, mesmo sem depender de explosão a cada plano.', en: 'A pace that gives you no breathing room, even without an explosion in every shot.' },
      { pt: 'Esse filme prova que adrenalina de verdade vem de tensão bem construída, não só de barulho alto.', en: 'This film proves real adrenaline comes from well-built tension, not just loud noise.' },
    ],
  },
  cypher: {
    drugTrip: [
      { pt: 'Esse filme não foi feito, foi alucinado. E o mais assustador é que fez sentido pra alguém financiar.', en: 'This film wasn\'t made, it was hallucinated. And the scariest part is someone actually financed it.' },
      { pt: 'Ninguém assistiu sóbrio e terminou de assistir sóbrio. Isso é quase garantia de qualidade pra mim.', en: 'Nobody started sober and finished sober. That\'s almost a quality guarantee for me.' },
      { pt: 'Achei essa fita numa caixa sem rótulo, num porão que eu prefiro não descrever em detalhes.', en: 'Found this tape in an unlabeled box, in a basement I\'d rather not describe in detail.' },
      { pt: 'Diretor declarou publicamente não lembrar de ter filmado certas cenas. Acredito plenamente.', en: 'The director publicly stated he doesn\'t remember filming certain scenes. I fully believe it.' },
      { pt: 'Esse filme não tem enredo, tem sintoma. Assista como quem observa uma febre alheia.', en: 'This film doesn\'t have a plot, it has a symptom. Watch it like you\'re observing someone else\'s fever.' },
      { pt: 'Censurado, perdido, redescoberto degradado. Cada versão parece mais estranha que a anterior, de propósito ou não.', en: 'Banned, lost, rediscovered degraded. Each version seems stranger than the last, on purpose or not.' },
      { pt: 'Ninguém explicou o que significa. Ninguém devia tentar. Alguns venenos não têm antídoto, só efeito.', en: 'Nobody explained what it means. Nobody should try. Some venoms have no antidote, only effect.' },
      { pt: 'Trilha sonora que parece ter sido gravada num pesadelo alheio. Uso e abuso disso pra assustar quem assiste.', en: 'A score that sounds like it was recorded inside someone else\'s nightmare. I fully exploit that to unsettle whoever watches.' },
      { pt: 'Esse filme mente pra você o tempo inteiro, e ainda assim parece mais honesto que muito filme \'realista\' por aí.', en: 'This film lies to you the entire time, and somehow still feels more honest than most \'realistic\' films out there.' },
      { pt: 'Guardei esse pro final porque é o mais estranho de todos. Se sobreviveu até aqui, já provou seu valor.', en: 'Saved this one for last because it\'s the strangest of them all. If you made it this far, you\'ve already proven yourself.' },
    ],
    catharsis: [
      { pt: 'Esse filme não te consola. Te arranca algo por dentro e não devolve.', en: 'This film doesn\'t console you. It rips something out of you and doesn\'t give it back.' },
      { pt: 'Ninguém distribuiu direito porque é pesado demais pra sala de cinema comum. Assista sozinho, é melhor assim.', en: 'Nobody distributed it properly because it\'s too heavy for a regular theater. Watch it alone, it\'s better that way.' },
      { pt: 'Achei esse filme numa lista de \'obras que os próprios diretores se recusaram a revisitar\'. Isso me disse tudo que eu precisava saber.', en: 'Found this film on a list of \'works the directors themselves refused to revisit.\' That told me everything I needed to know.' },
      { pt: 'Chorei assistindo, e olha que eu não choro fácil. Considera isso um selo de qualidade.', en: 'I cried watching it, and I don\'t cry easily. Consider that a seal of approval.' },
      { pt: 'Esse filme foi feito com dor real de alguém envolvido na produção. Dá pra sentir cada frame disso.', en: 'This film was made with real pain from someone involved in the production. You can feel it in every frame.' },
      { pt: 'Ninguém assistiu porque não tem final feliz, nem final triste bonito. Só tem final, cru.', en: 'Nobody watched it because there\'s no happy ending, not even a pretty sad one. Just an ending, raw.' },
      { pt: 'Esvazia você de propósito. Depois te deixa sozinho com o vazio pra descobrir o que fazer com ele.', en: 'Empties you out on purpose. Then leaves you alone with the emptiness to figure out what to do with it.' },
      { pt: 'Direção que não pisca, não corta na hora certa pra te poupar. Você sente cada segundo desconfortável.', en: 'Direction that doesn\'t blink, doesn\'t cut away at the right time to spare you. You feel every uncomfortable second.' },
      { pt: 'Obscuro, cruel, necessário. Nessa ordem, ou em qualquer ordem, tanto faz.', en: 'Obscure, cruel, necessary. In that order, or any order, doesn\'t matter.' },
      { pt: 'Guardei esse veneno pro fim de tudo, de propósito. Algumas coisas só fazem sentido no final.', en: 'Saved this venom for the very end, on purpose. Some things only make sense at the end.' },
    ],
    mindBlowing: [
      { pt: 'Esse aqui fede a genialidade mal executada. Meu veneno favorito.', en: 'This one reeks of poorly executed genius. My favorite venom.' },
      { pt: 'Ninguém entendeu o final. Nem eu. Isso não me impede de recomendar com toda confiança.', en: 'Nobody understood the ending. Not even me. That doesn\'t stop me from recommending it with full confidence.' },
      { pt: 'Diretor teve um surto criativo e ninguém o impediu a tempo. O resultado é isso aqui.', en: 'The director had a creative breakdown and nobody stopped him in time. This is the result.' },
      { pt: 'Filme tão confuso que virou proibido em festival por \'incompreensibilidade\'. Motivo mais nobre eu nunca vi.', en: 'A film so confusing it got banned from a festival for \'incomprehensibility.\' Never seen a nobler reason.' },
      { pt: 'Achei esse numa lista chamada \'filmes que quebraram seus editores\'. Assinei embaixo.', en: 'Found this on a list called \'films that broke their editors.\' Signed right underneath.' },
      { pt: 'Estrutura de tempo que não segue regra nenhuma, nem as que o próprio filme cria. Delicioso caos.', en: 'A time structure that follows no rule, not even the ones the film itself creates. Delicious chaos.' },
      { pt: 'Ninguém assistiu porque dá dor de cabeça de verdade. Eu considero isso elogio, não aviso.', en: 'Nobody watched it because it gives you a real headache. I consider that a compliment, not a warning.' },
      { pt: 'Tudo que existe, existe ao mesmo tempo dentro desse filme, feito um espelho quebrado refletindo o próprio quebrar. Isso não é bagunça, é a única forma honesta de mostrar como tudo é, no fundo, a mesma coisa se olhando de ângulos diferentes.', en: 'Everything that exists, exists at once inside this film, like a broken mirror reflecting its own breaking. This isn\'t a mess, it\'s the only honest way to show how everything is, deep down, the same thing looking at itself from different angles.' },
      { pt: 'Esse filme não quer que você entenda. Quer que você sinta a confusão como experiência, não como falha.', en: 'This film doesn\'t want you to understand. It wants you to feel the confusion as an experience, not a flaw.' },
      { pt: 'Guardei esse veneno pra quem já achou que tinha visto tudo. Vamos ver se aguenta.', en: 'Saved this venom for someone who thought they\'d already seen it all. Let\'s see if you can handle it.' },
    ],
    adrenaline: [
      { pt: 'Ação tão mal distribuída que só sobrou em fita pirata de segunda geração. Ainda acelera o coração.', en: 'Action so poorly distributed it only survived on a second-generation bootleg tape. Still races your heart.' },
      { pt: 'Ninguém financiou a continuação porque o primeiro quase matou o orçamento inteiro do estúdio. Vale cada centavo perdido.', en: 'Nobody funded a sequel because the first one nearly killed the studio\'s entire budget. Worth every lost cent.' },
      { pt: 'Perseguição filmada sem permissão de ninguém. Literalmente. Isso explica a adrenalina real na tela.', en: 'A chase filmed without anyone\'s permission. Literally. That explains the real adrenaline on screen.' },
      { pt: 'Dublê machucado de verdade numa cena. Ficou no filme. Isso aqui é dor genuína, não encenada.', en: 'A stuntman actually got hurt in one scene. It stayed in the film. This is genuine pain, not staged.' },
      { pt: 'Filme tão intenso que o próprio elenco se recusou a comentar sobre as filmagens depois. Adoro esse tipo de silêncio.', en: 'A film so intense the cast refused to talk about the shoot afterward. I love that kind of silence.' },
      { pt: 'Ninguém assistiu porque a cópia mal circulou. Eu consegui a minha por um favor que prefiro não explicar.', en: 'Nobody watched it because the copy barely circulated. I got mine through a favor I\'d rather not explain.' },
      { pt: 'Essa ação não tem herói bonzinho. Tem gente desesperada fazendo coisa estúpida e funcionando por sorte.', en: 'This action has no nice hero. Just desperate people doing something stupid and getting lucky.' },
      { pt: 'Filmado num lugar que provavelmente não deixaria mais filmar nada depois disso. Compreensível.', en: 'Filmed somewhere that probably wouldn\'t allow filming again after this. Understandable.' },
      { pt: 'Ritmo tão bruto que parece amador. É exatamente por isso que funciona melhor que blockbuster polido.', en: 'A pace so raw it feels amateur. That\'s exactly why it works better than a polished blockbuster.' },
      { pt: 'Esse veneno é forte. Bebe com cuidado, ou não bebe nada, tanto faz pra mim.', en: 'This venom is strong. Drink carefully, or don\'t drink at all, makes no difference to me.' },
    ],
    adventures: [
      { pt: 'Aventura tão obscura que o próprio mapa do filme parece ter se perdido junto com a distribuição.', en: 'An adventure so obscure even the film\'s own map seems to have gotten lost along with its distribution.' },
      { pt: 'Orçamento de ninguém, ambição de gente grande. Essa desproporção é meu tipo favorito de beleza.', en: 'Nobody\'s budget, big-league ambition. That imbalance is my favorite kind of beauty.' },
      { pt: 'Achei essa fita numa venda de garagem, literalmente. O dono nem sabia o que tinha em mãos.', en: 'Found this tape at a literal garage sale. The owner didn\'t even know what they had.' },
      { pt: 'Ninguém terminou de assistir por causa da trilha sonora estranha. Eu terminei por causa dela.', en: 'Nobody finished watching because of the strange score. I finished because of it.' },
      { pt: 'Jornada sem destino claro, sem herói claro, sem final claro. Perfeitamente perturbador.', en: 'A journey with no clear destination, no clear hero, no clear ending. Perfectly unsettling.' },
      { pt: 'Filme feito com dinheiro emprestado e favor de amigo. Sobrevive até hoje por teimosia pura.', en: 'A film made with borrowed money and favors from friends. Still survives today out of pure stubbornness.' },
      { pt: 'Elenco de atores que nunca mais atuaram. Talvez esse filme tenha consumido tudo que tinham.', en: 'A cast that never acted again. Maybe this film consumed everything they had.' },
      { pt: 'Essa aventura não te leva a lugar nenhum feliz. Te leva a algum lugar verdadeiro, que já é mais raro.', en: 'This adventure doesn\'t take you anywhere happy. It takes you somewhere true, which is already rarer.' },
      { pt: 'Censurado em algum lugar obscuro por razão ainda mais obscura. Isso só aumentou meu interesse.', en: 'Banned somewhere obscure for an even more obscure reason. That only increased my interest.' },
      { pt: 'Guardei essa joia suja pra quem gosta de cavar sem luva. Espero que suas mãos aguentem.', en: 'Saved this dirty gem for someone who likes digging without gloves. Hope your hands can take it.' },
    ],
    romantic: [
      { pt: 'Romance tão obscuro que parece ter sido feito só pra duas pessoas assistirem. Você é a terceira.', en: 'A romance so obscure it seems made for only two people to watch. You\'re the third.' },
      { pt: 'Não é bonitinho. É desconfortável do jeito que amor de verdade costuma ser.', en: 'It\'s not cute. It\'s uncomfortable the way real love usually is.' },
      { pt: 'Achei esse filme numa cinemateca que fechou um mês depois. Quase parece destino, mas eu não acredito nisso.', en: 'Found this film at a cinematheque that closed a month later. Almost feels like fate, but I don\'t buy that.' },
      { pt: 'Final nada feliz, nada trágico também. Só real, o que incomoda mais que qualquer drama exagerado.', en: 'Not a happy ending, not a tragic one either. Just real, which unsettles more than any exaggerated drama.' },
      { pt: 'Ninguém assistiu porque o amor aqui não é bonito de se ver. É verdadeiro demais pra ser confortável.', en: 'Nobody watched it because the love here isn\'t pretty to look at. It\'s too true to be comfortable.' },
      { pt: 'Casal que se destrói mutuamente com carinho genuíno. Combinação cruel que eu aprecio de longe.', en: 'A couple destroying each other with genuine tenderness. A cruel combo I appreciate from a distance.' },
      { pt: 'Diretor desconhecido, uma única obra, depois silêncio total. Às vezes um filme é tudo que alguém precisa dizer.', en: 'Unknown director, a single work, then total silence. Sometimes one film is all someone needs to say.' },
      { pt: 'Romance que não segue fórmula nenhuma. Nem eu sei explicar por que funciona, só sei que funciona.', en: 'A romance that follows no formula at all. Even I can\'t explain why it works, I just know it does.' },
      { pt: 'Beijo mais desconfortável que eu já vi na tela. Por isso mesmo, o mais honesto.', en: 'The most uncomfortable kiss I\'ve ever seen on screen. Which is exactly why it\'s the most honest.' },
      { pt: 'Guardei esse pra alguém que já sofreu de amor de verdade. Suspeito que seja você.', en: 'Saved this one for someone who\'s already suffered real love. I suspect that\'s you.' },
    ],
    familyTime: [
      { pt: 'Filme de família tão esquecido que nem a família que fez lembra dele. Ironia deliciosa.', en: 'A family film so forgotten even the family who made it doesn\'t remember it. Delicious irony.' },
      { pt: 'Achei numa prateleira de locadora falida, com poeira grossa. Tratei como relíquia.', en: 'Found it on a shelf of a bankrupt rental store, thick with dust. Treated it like a relic.' },
      { pt: 'Ninguém popularizou porque é estranho demais pra criança e sutil demais pra adulto notar. Ponto exato que eu gosto.', en: 'Nobody popularized it because it\'s too strange for kids and too subtle for adults to notice. Exact spot I like.' },
      { pt: 'Curioso como toda família na tela é só um espelho quebrado da nossa, cada estilhaço mostrando um ângulo diferente do mesmo rosto. Esse filme entendeu isso antes de qualquer manual de roteiro.', en: 'Funny how every family on screen is just a broken mirror of our own, each shard showing a different angle of the same face. This film understood that before any screenwriting manual did.' },
      { pt: 'Zero prêmio, zero bilheteria, uma cena que eu não esqueço até hoje. Prioridades certas.', en: 'Zero awards, zero box office, one scene I still haven\'t forgotten. Right priorities.' },
      { pt: 'Filme obscuro que trata criança como gente de verdade, não como enfeite de roteiro. Raro até nos famosos.', en: 'An obscure film that treats children like real people, not script decoration. Rare even among the famous ones.' },
      { pt: 'Ninguém fala desse filme em lista nenhuma. Eu falo baixinho, só pra quem merece.', en: 'Nobody mentions this film on any list. I mention it quietly, only to those who deserve it.' },
      { pt: 'Produção tão pequena que o elenco provavelmente era vizinho do diretor. Sinceridade que dinheiro não compra.', en: 'Production so small the cast was probably the director\'s neighbors. Sincerity money can\'t buy.' },
      { pt: 'Achado, perdido, achado de novo. Esse filme tem mais vidas que gato. Combina comigo.', en: 'Found, lost, found again. This film has more lives than a cat. Suits me.' },
      { pt: 'Esquecido pelo mundo, guardado por mim. Considere isso um empréstimo raro.', en: 'Forgotten by the world, kept by me. Consider this a rare loan.' },
    ],
    laughOutLoud: [
      { pt: 'Comédia tão obscura que nem o diretor lembra direito de ter feito. Rimos juntas mesmo assim.', en: 'A comedy so obscure even the director barely remembers making it. We laughed together anyway.' },
      { pt: 'Ninguém assistiu, ninguém recomenda, e é exatamente por isso que essa piada ainda é surpresa.', en: 'Nobody watched it, nobody recommends it, and that\'s exactly why the joke still lands as a surprise.' },
      { pt: 'Humor tão estranho que incomoda antes de fazer rir. Prefiro assim.', en: 'Humor so strange it unsettles before it amuses. I prefer it that way.' },
      { pt: 'Achei numa lista de \'piores comédias\' de um fórum morto. Discordo veementemente, e rio até hoje.', en: 'Found it on a \'worst comedies\' list from a dead forum. I strongly disagree, and I still laugh at it.' },
      { pt: 'Esse filme é engraçado do jeito errado, o que o torna certo pra mim.', en: 'This film is funny in the wrong way, which makes it right for me.' },
      { pt: 'Rir sem saber se pode. Essa incerteza é meu ingrediente favorito de comédia.', en: 'Laughing without knowing if you\'re allowed to. That uncertainty is my favorite comedy ingredient.' },
      { pt: 'Elenco desconhecido, orçamento inexistente, timing cômico acidentalmente perfeito. Aprecio o acidente.', en: 'Unknown cast, no budget, comic timing accidentally perfect. I appreciate the accident.' },
      { pt: 'Ninguém entendeu a piada em 1987. Ainda ninguém entende. Isso não impede de ser genial.', en: 'Nobody got the joke in 1987. Still nobody gets it. That doesn\'t stop it from being genius.' },
      { pt: 'Cruel com os personagens, generoso com a plateia. Distribuição de sofrimento que eu aprecio.', en: 'Cruel to its characters, generous to the audience. A distribution of suffering I appreciate.' },
      { pt: 'Comédia esquecida que mereceria ser lembrada só pra incomodar mais gente. Compartilho por maldade pura.', en: 'A forgotten comedy that deserves remembering just to unsettle more people. I share it out of pure spite.' },
    ],
    darkScary: [
      { pt: 'Achei esse enterrado bem fundo. Ninguém assistiu por um bom motivo, e eu adorei descobrir qual.', en: 'Found this one buried deep. Nobody watched it for a good reason, and I loved finding out why.' },
      { pt: 'Aviso de verdade, não fingido: esse filme tem cena que gente com estômago fraco arrepende de ter visto. Eu não arrependi.', en: 'A real warning, not a fake one: this film has a scene people with weak stomachs regret seeing. I didn\'t.' },
      { pt: 'Zero estrelas em site de crítica. Isso só me deixou curiosa. E valeu cada minuto perturbador.', en: 'Zero stars on review sites. That only made me curious. And it was worth every disturbing minute.' },
      { pt: 'Ninguém fala desse filme porque ninguém sobreviveu ileso pra recomendar. Menos eu.', en: 'Nobody talks about this film because nobody survived unscathed enough to recommend it. Except me.' },
      { pt: 'Achado em festival que nem existe mais. Isso já deveria te dizer o suficiente.', en: 'Found at a festival that doesn\'t even exist anymore. That alone should tell you enough.' },
      { pt: 'Diretor sumiu depois desse filme. Ninguém sabe se foi escolha ou consequência. Delicioso mistério.', en: 'The director vanished after this film. Nobody knows if it was choice or consequence. Delicious mystery.' },
      { pt: 'Isso aqui não assusta com monstro. Assusta com a ideia de que talvez não exista monstro nenhum, só nós.', en: 'This doesn\'t scare you with a monster. It scares you with the idea that maybe there\'s no monster at all, just us.' },
      { pt: 'Poucos viram, menos ainda terminaram de assistir. Eu terminei duas vezes.', en: 'Few watched it, even fewer finished it. I finished it twice.' },
      { pt: 'Esse veneno eu guardei de propósito. Sabia que ia gostar de alguém que chegasse até aqui.', en: 'I saved this venom on purpose. Knew I\'d enjoy whoever made it this far.' },
      { pt: 'Se depois desse filme você dormir tranquilo, ou é forte demais, ou não prestou atenção o suficiente.', en: 'If you sleep soundly after this film, you\'re either too strong, or you weren\'t paying enough attention.' },
    ],
  },
};

// Ponte entre o mood_key salvo no banco (recommendation_pools) e a chave
// usada aqui no banco de frases (mesmo nome das traduções oracle.moods.*).
const DB_MOOD_TO_PHRASE_KEY: Record<string, string> = {
  'adventures': 'adventures',
  'catharsis': 'catharsis',
  'adrenaline': 'adrenaline',
  'mind-blowing': 'mindBlowing',
  'laugh-out-loud': 'laughOutLoud',
  'drug-trip': 'drugTrip',
  'romantic': 'romantic',
  'dark-and-scary': 'darkScary',
  'family-time': 'familyTime',
  'random-surprise': 'random-surprise' // sentinela — filtrada, não é humor de verdade
};

/**
 * Sorteia uma frase do oráculo, respeitando o(s) humor(es) reais que o filme
 * bateu nas pools (recommendation_pools). "random-surprise" é a união das
 * outras 9 pools — se essa for a ÚNICA correspondência (o filme não bateu em
 * nenhum humor específico), sorteia de qualquer um dos 9 humores. Se bateu em
 * humor(es) específico(s), sorteia só entre esses.
 */
export function getRandomFlavorPhrase(oracle: string, dbMoodKeys: string[]): OracleFlavorPhrase | null {
  const oracleMoods = ORACLE_FLAVOR_PHRASES[oracle];
  if (!oracleMoods) return null;

  const specificMoods = dbMoodKeys
    .map((k) => DB_MOOD_TO_PHRASE_KEY[k])
    .filter((k): k is string => !!k && k !== 'random-surprise' && !!oracleMoods[k]);

  const candidateMoods = specificMoods.length > 0 ? specificMoods : Object.keys(oracleMoods);
  if (candidateMoods.length === 0) return null;

  const chosenMood = candidateMoods[Math.floor(Math.random() * candidateMoods.length)];
  const phrases = oracleMoods[chosenMood];
  if (!phrases || phrases.length === 0) return null;
  return phrases[Math.floor(Math.random() * phrases.length)];
}