import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, User, Globe } from 'lucide-react';
import { useTranslation } from 'react-i18next';

interface Persona {
  name: string;
  descriptionPt: string;
  descriptionEn: string;
  imageQuery: string;
}

const PERSONAS: Record<string, Persona> = {
  EIA: { name: 'Forrest Gump', imageQuery: 'forrest-gump-1994', descriptionPt: 'Forrest Gump é o protagonista homônimo do romance de 1986 de Winston Groom e de sua premiada adaptação cinematográfica de 1994 dirigida por Robert Zemeckis. Retratado por Tom Hanks, o personagem é um homem de coração puro e intelecto limitado que, de forma inocente, participa de momentos decisivos da história dos Estados Unidos no século XX.', descriptionEn: 'Forrest Gump is the title character of Winston Groom\'s 1986 novel and its acclaimed 1994 film adaptation directed by Robert Zemeckis. Portrayed by Tom Hanks, he is a pure-hearted man of limited intellect who innocently participates in pivotal moments of 20th-century American history.' },
  EIB: { name: 'Nina Sayers', imageQuery: 'black-swan-nina', descriptionPt: 'Nina Sayers é a protagonista do filme psicológico Black Swan, dirigido por Darren Aronofsky. Interpretada por Natalie Portman, ela é uma bailarina nova-iorquina obcecada pela perfeição que mergulha em um colapso psicológico ao buscar encarnar as dualidades do "Cisne Branco" e do "Cisne Negro" em uma produção de O Lago dos Cisnes.', descriptionEn: 'Nina Sayers is the protagonist of Darren Aronofsky\'s psychological film Black Swan. Played by Natalie Portman, she is a New York ballerina obsessed with perfection who descends into psychological collapse while attempting to embody both the White Swan and Black Swan in a production of Swan Lake.' },
  EIX: { name: 'Joel Barish', imageQuery: 'eternal-sunshine-joel', descriptionPt: 'Joel Barish é o protagonista do filme Eternal Sunshine of the Spotless Mind, dirigido por Michel Gondry e escrito por Charlie Kaufman. Interpretado por Jim Carrey, Joel é um homem introspectivo que busca apagar as memórias de um relacionamento fracassado, tornando-se o centro emocional de uma história sobre amor, perda e identidade.', descriptionEn: 'Joel Barish is the protagonist of Eternal Sunshine of the Spotless Mind, directed by Michel Gondry and written by Charlie Kaufman. Played by Jim Carrey, Joel is an introspective man who seeks to erase memories of a failed relationship, becoming the emotional center of a story about love, loss, and identity.' },
  EIK: { name: 'Rick Blaine', imageQuery: 'casablanca-humphrey-bogart', descriptionPt: 'Rick Blaine é o protagonista do filme clássico Casablanca, interpretado por Humphrey Bogart. Dono do bar Rick\'s Café Américain na cidade de Casablanca, ele é um expatriado americano cínico e desencantado que se vê dividido entre o amor e o dever em meio à Segunda Guerra Mundial.', descriptionEn: 'Rick Blaine is the protagonist of the classic film Casablanca, played by Humphrey Bogart. Owner of Rick\'s Café Américain in Casablanca, he is a cynical American expatriate torn between love and duty during World War II.' },
  EID: { name: 'Rust Cohle', imageQuery: 'true-detective-rust-cohle', descriptionPt: 'Rustin Spencer "Rust" Cohle é o protagonista da primeira temporada da série True Detective (2014), criada por Nic Pizzolatto. Interpretado por Matthew McConaughey, Cohle é um detetive brilhante, profundamente atormentado e marcado por visões filosóficas e existenciais sobre a natureza da vida e do mal.', descriptionEn: 'Rust Cohle is the protagonist of the first season of True Detective (2014). Played by Matthew McConaughey, Cohle is a brilliant, deeply tormented detective shaped by philosophical and existential views on the nature of life and evil.' },
  EIL: { name: 'Amélie Poulain', imageQuery: 'amelie-poulain-audrey-tautou', descriptionPt: 'Amélie Poulain é a personagem principal do filme francês Le Fabuleux Destin d\'Amélie Poulain, dirigido por Jean-Pierre Jeunet. Interpretada por Audrey Tautou, Amélie tornou-se um ícone da cultura pop por seu olhar poético e imaginativo sobre a vida cotidiana em Paris.', descriptionEn: 'Amélie Poulain is the main character of the French film Amélie, directed by Jean-Pierre Jeunet. Played by Audrey Tautou, she became a pop culture icon for her poetic and imaginative view of everyday life in Paris.' },
  ECA: { name: 'Salvatore Di Vita', imageQuery: 'cinema-paradiso-salvatore', descriptionPt: 'Salvatore Di Vita é o protagonista do filme italiano Nuovo Cinema Paradiso, dirigido por Giuseppe Tornatore. Sua história retrata o crescimento de um menino apaixonado por cinema em uma pequena cidade siciliana e sua trajetória até se tornar um renomado cineasta, refletindo sobre memória, amizade e perda.', descriptionEn: 'Salvatore Di Vita is the protagonist of the Italian film Cinema Paradiso, directed by Giuseppe Tornatore. His story depicts a boy\'s love for cinema in a small Sicilian town and his journey to becoming a renowned filmmaker, reflecting on memory, friendship, and loss.' },
  ECB: { name: 'Michael Corleone', imageQuery: 'godfather-michael-corleone-al-pacino', descriptionPt: 'Michael Corleone é o protagonista fictício da saga cinematográfica The Godfather, criada por Mario Puzo e dirigida por Francis Ford Coppola. Interpretado por Al Pacino, ele é o terceiro filho de Vito Corleone e se torna o chefe da família após uma trajetória marcada por lealdade, violência e tragédia.', descriptionEn: 'Michael Corleone is the fictional protagonist of The Godfather film saga, created by Mario Puzo and directed by Francis Ford Coppola. Played by Al Pacino, he is the third son of Vito Corleone who becomes the family patriarch after a path marked by loyalty, violence, and tragedy.' },
  ECX: { name: 'Betty Elms', imageQuery: 'mulholland-drive-naomi-watts', descriptionPt: 'Betty Elms é uma personagem fictícia do filme Mulholland Drive, dirigido por David Lynch. Interpretada por Naomi Watts, Betty representa uma aspirante a atriz recém-chegada a Los Angeles, cuja história mistura sonho, identidade e ilusão.', descriptionEn: 'Betty Elms is a fictional character in Mulholland Drive, directed by David Lynch. Played by Naomi Watts, Betty represents an aspiring actress newly arrived in Los Angeles whose story blends dream, identity, and illusion.' },
  ECK: { name: 'Atticus Finch', imageQuery: 'to-kill-mockingbird-atticus-finch', descriptionPt: 'Atticus Finch é um personagem fictício do romance To Kill a Mockingbird (1960), de Harper Lee, e do filme homônimo de 1962. Advogado e pai viúvo de Scout e Jem Finch, ele simboliza integridade moral e justiça em meio ao racismo do sul dos Estados Unidos na década de 1930.', descriptionEn: 'Atticus Finch is a fictional character from Harper Lee\'s 1960 novel and its 1962 film adaptation. A lawyer and widowed father, he symbolizes moral integrity and justice amid the racism of the 1930s American South.' },
  ECD: { name: 'Lee Chandler', imageQuery: 'manchester-by-sea-casey-affleck', descriptionPt: 'Lee Chandler é o protagonista do filme Manchester by the Sea, interpretado por Casey Affleck, cuja atuação lhe rendeu o Oscar de Melhor Ator. O personagem é um zelador de Boston que retorna à sua cidade natal após a morte do irmão, enfrentando traumas passados e responsabilidades inesperadas.', descriptionEn: 'Lee Chandler is the protagonist of Manchester by the Sea, played by Casey Affleck in his Oscar-winning performance. He is a Boston janitor who returns to his hometown after his brother\'s death, confronting past traumas and unexpected responsibilities.' },
  ECL: { name: 'Guido Orefice', imageQuery: 'life-is-beautiful-roberto-benigni', descriptionPt: 'Guido Orefice é o protagonista do filme La vita è bella ("A Vida é Bela"), interpretado por Roberto Benigni, que também dirigiu e coescreveu a obra. O personagem é um livreiro judeu na Itália fascista cuja imaginação e otimismo sustentam a família em meio aos horrores do Holocausto.', descriptionEn: 'Guido Orefice is the protagonist of Life Is Beautiful, played by Roberto Benigni who also directed and co-wrote the film. He is a Jewish bookseller in fascist Italy whose imagination and optimism sustain his family amid the horrors of the Holocaust.' },
  ERA: { name: 'Ted Lasso', imageQuery: 'ted-lasso-jason-sudeikis', descriptionPt: 'Ted Lasso é o personagem fictício principal da série de comédia "Ted Lasso", interpretado por Jason Sudeikis. Ele é um treinador de futebol americano contratado inesperadamente para comandar um time de futebol inglês, apesar de sua falta de experiência no esporte. O personagem tornou-se símbolo de otimismo, empatia e liderança positiva.', descriptionEn: 'Ted Lasso is the main character of the comedy series Ted Lasso, played by Jason Sudeikis. He is an American football coach unexpectedly hired to manage an English soccer team despite his lack of experience in the sport, becoming a symbol of optimism, empathy, and positive leadership.' },
  ERB: { name: 'Anakin Skywalker', imageQuery: 'star-wars-anakin-skywalker', descriptionPt: 'Anakin Skywalker é um personagem fictício da franquia Star Wars, criado por George Lucas. Originalmente um escravo em Tatooine com grande sensibilidade à Força, tornou-se Cavaleiro Jedi e mais tarde o Sith Lord Darth Vader. Sua jornada trágica, da promessa à queda e à redenção, é um dos arcos narrativos mais icônicos do cinema.', descriptionEn: 'Anakin Skywalker is a fictional character in the Star Wars franchise, created by George Lucas. Originally a slave on Tatooine with exceptional Force sensitivity, he became a Jedi Knight and later the Sith Lord Darth Vader. His tragic journey from promise to fall to redemption is one of cinema\'s most iconic narrative arcs.' },
  ERX: { name: 'Scott Pilgrim', imageQuery: 'scott-pilgrim-vs-world', descriptionPt: 'Scott Pilgrim é o protagonista do filme Scott Pilgrim vs. the World, interpretado por Michael Cera. Um jovem músico de Toronto que precisa derrotar os sete ex-namorados malvados de sua nova paixão, Ramona Flowers. O personagem mistura cultura pop, videogame e amor de forma irreverente.', descriptionEn: 'Scott Pilgrim is the protagonist of Scott Pilgrim vs. the World, played by Michael Cera. A young Toronto musician who must defeat the seven evil exes of his new love interest, Ramona Flowers. The character blends pop culture, video games, and romance in an irreverent style.' },
  ERK: { name: 'William Wallace', imageQuery: 'braveheart-william-wallace', descriptionPt: 'William Wallace é o protagonista fictício do filme Braveheart, de 1995, dirigido e estrelado por Mel Gibson. Inspirado no líder escocês homônimo do século XIII, o personagem é retratado como um guerreiro carismático que lidera uma revolta contra a dominação inglesa.', descriptionEn: 'William Wallace is the fictional protagonist of Braveheart (1995), directed by and starring Mel Gibson. Inspired by the real 13th-century Scottish leader, he is portrayed as a charismatic warrior leading a revolt against English dominion.' },
  ERD: { name: 'Tony Stark', imageQuery: 'iron-man-tony-stark-robert-downey', descriptionPt: 'Tony Stark é um personagem fictício do Universo Cinematográfico da Marvel (MCU), interpretado por Robert Downey Jr.. Gênio bilionário, inventor e filantropo, ele é a identidade civil do super-herói Homem de Ferro e figura central da franquia The Avengers.', descriptionEn: 'Tony Stark is a fictional character in the Marvel Cinematic Universe, played by Robert Downey Jr. A genius billionaire inventor and philanthropist, he is the civilian identity of Iron Man and a central figure in The Avengers franchise.' },
  ERL: { name: 'Elle Woods', imageQuery: 'legally-blonde-elle-woods', descriptionPt: 'Elle Woods é a protagonista fictícia da comédia americana Legally Blonde e suas continuações, interpretada por Reese Witherspoon. O personagem é um ícone cultural do início dos anos 2000.', descriptionEn: 'Elle Woods is the fictional protagonist of the American comedy Legally Blonde and its sequels, played by Reese Witherspoon. The character is a cultural icon of the early 2000s.' },
  ESA: { name: 'Mia Dolan', imageQuery: 'la-la-land-emma-stone-mia', descriptionPt: 'Mia Dolan é a personagem principal do filme musical La La Land, interpretada por Emma Stone. Aspirante a atriz em Los Angeles, Mia simboliza o conflito entre paixão artística e realidade prática.', descriptionEn: 'Mia Dolan is the main character of the musical film La La Land, played by Emma Stone. An aspiring actress in Los Angeles, Mia symbolizes the conflict between artistic passion and practical reality.' },
  ESB: { name: 'Amy Dunne', imageQuery: 'gone-girl-amy-dunne-rosamund-pike', descriptionPt: 'Amy Dunne é a personagem central do thriller psicológico Gone Girl, dirigido por David Fincher. Interpretada por Rosamund Pike, Amy é conhecida por sua complexidade e pela reviravolta que define o enredo, tornando-se um dos retratos mais marcantes da manipulação psicológica no cinema contemporâneo.', descriptionEn: 'Amy Dunne is the central character of the psychological thriller Gone Girl, directed by David Fincher. Played by Rosamund Pike, Amy is known for her complexity and the twist that defines the plot, becoming one of the most striking portrayals of psychological manipulation in contemporary cinema.' },
  ESX: { name: 'The Driver', imageQuery: 'drive-2011-ryan-gosling', descriptionPt: 'The Driver é o protagonista do filme Drive (2011), interpretado por Ryan Gosling. Ele é um dublê de cinema e motorista de fuga em Los Angeles, retratado como uma figura enigmática, lacônica e violenta quando necessário. Tornou-se um ícone moderno do anti-herói minimalista.', descriptionEn: 'The Driver is the protagonist of Drive (2011), played by Ryan Gosling. A Hollywood stuntman and getaway driver in Los Angeles, he is portrayed as an enigmatic, laconic figure who turns violent when necessary. He became a modern icon of the minimalist anti-hero.' },
  ESK: { name: 'Rocky Balboa', imageQuery: 'rocky-balboa-sylvester-stallone', descriptionPt: 'Rocky Balboa é um personagem fictício da série de filmes Rocky, criado e interpretado por Sylvester Stallone. O personagem é um boxeador ítalo-americano da Filadélfia que se torna símbolo de perseverança, disciplina e superação.', descriptionEn: 'Rocky Balboa is a fictional character from the Rocky film series, created and played by Sylvester Stallone. He is an Italian-American boxer from Philadelphia who became a symbol of perseverance, discipline, and triumph over adversity.' },
  ESD: { name: 'Joker', imageQuery: 'joker-2019-joaquin-phoenix', descriptionPt: 'O Coringa (Joker, 2019) é interpretado por Joaquin Phoenix. A obra apresenta uma origem alternativa e realista para o famoso vilão da DC Comics, explorando temas de isolamento social, doença mental e desigualdade urbana.', descriptionEn: 'The Joker (2019), played by Joaquin Phoenix, presents an alternative and realistic origin for the famous DC Comics villain, exploring themes of social isolation, mental illness, and urban inequality.' },
  ESL: { name: 'Jack Dawson', imageQuery: 'titanic-jack-dawson-leonardo-dicaprio', descriptionPt: 'Jack Dawson é um personagem fictício do filme Titanic, interpretado por Leonardo DiCaprio. Jovem artista de espírito livre, ele vive um romance trágico com Rose DeWitt Bukater a bordo do RMS Titanic.', descriptionEn: 'Jack Dawson is a fictional character in Titanic, played by Leonardo DiCaprio. A free-spirited young artist, he lives a tragic romance with Rose DeWitt Bukater aboard the RMS Titanic.' },
  IEA: { name: 'Cooper', imageQuery: 'interstellar-cooper-matthew-mcconaughey', descriptionPt: 'Cooper é o protagonista do filme de ficção científica Interstellar, interpretado por Matthew McConaughey. Ele é um ex-piloto e engenheiro da NASA que se torna a última esperança da humanidade em uma missão interestelar para salvar a Terra da extinção ecológica.', descriptionEn: 'Cooper is the protagonist of the sci-fi film Interstellar, played by Matthew McConaughey. He is a former NASA pilot and engineer who becomes humanity\'s last hope in an interstellar mission to save Earth from ecological extinction.' },
  IEB: { name: 'Louis Bloom', imageQuery: 'nightcrawler-jake-gyllenhaal', descriptionPt: 'Louis Bloom é o protagonista do filme Nightcrawler, interpretado por Jake Gyllenhaal. O personagem é um aspirante a cinegrafista independente de Los Angeles que se envolve na prática de registrar imagens de crimes e acidentes para vender a emissoras de TV. Sua figura simboliza a ambição extrema e a ética corrompida.', descriptionEn: 'Louis Bloom is the protagonist of Nightcrawler, played by Jake Gyllenhaal. An aspiring freelance videographer in Los Angeles who films crime and accident scenes to sell to TV networks, he symbolizes extreme ambition and corrupt ethics.' },
  IEX: { name: 'Dom Cobb', imageQuery: 'inception-dom-cobb-leonardo-dicaprio', descriptionPt: 'Dom Cobb é o protagonista do filme Inception, interpretado por Leonardo DiCaprio. Cobb é um ladrão especializado em "extração" — o roubo de segredos do inconsciente durante o sonho. O personagem é o centro emocional e filosófico da história, marcada por temas de culpa, memória e realidade.', descriptionEn: 'Dom Cobb is the protagonist of Inception, played by Leonardo DiCaprio. He is a thief specializing in "extraction" — stealing secrets from the subconscious during dreams. The character is the emotional and philosophical center of the story, marked by themes of guilt, memory, and reality.' },
  IEK: { name: 'Sherlock Holmes', imageQuery: 'sherlock-holmes-detective', descriptionPt: 'Sherlock Holmes é um detetive fictício criado pelo escritor escocês Sir Arthur Conan Doyle. Figura central da literatura policial, tornou-se o arquétipo do investigador lógico e observador, símbolo da literatura policial moderna e ícone cultural mundial.', descriptionEn: 'Sherlock Holmes is a fictional detective created by Sir Arthur Conan Doyle. A central figure in crime literature, he became the archetype of the logical and observant investigator, a symbol of modern detective fiction and a worldwide cultural icon.' },
  IED: { name: 'Robert Angier', imageQuery: 'the-prestige-hugh-jackman', descriptionPt: 'Robert Angier é um personagem fictício do filme The Prestige, interpretado por Hugh Jackman. Ele é um ilusionista carismático cuja rivalidade com Alfred Borden impulsiona a trama em uma competição obsessiva por fama e perfeição.', descriptionEn: 'Robert Angier is a fictional character in The Prestige, played by Hugh Jackman. He is a charismatic illusionist whose rivalry with Alfred Borden drives the plot in an obsessive competition for fame and perfection.' },
  IEL: { name: 'Mark Watney', imageQuery: 'the-martian-matt-damon', descriptionPt: 'Mark Watney é o protagonista de The Martian, interpretado por Matt Damon. Ele é um astronauta e botânico da NASA que fica preso em Marte após uma missão fracassada e precisa usar engenhosidade científica para sobreviver.', descriptionEn: 'Mark Watney is the protagonist of The Martian, played by Matt Damon. He is a NASA astronaut and botanist stranded on Mars after a failed mission who must use scientific ingenuity to survive until rescue.' },
  ICA: { name: 'Prof. Keating', imageQuery: 'dead-poets-society-robin-williams', descriptionPt: 'Professor John Keating é um personagem fictício do filme Dead Poets Society, interpretado por Robin Williams. Ele é um professor de literatura inglesa que inspira seus alunos a pensar de forma independente e a "aproveitar o dia" ("carpe diem").', descriptionEn: 'Professor John Keating is a fictional character in Dead Poets Society, played by Robin Williams. He is an English literature teacher who inspires his students to think independently and to "seize the day" (carpe diem).' },
  ICB: { name: 'Dr. Jonathan Crane', imageQuery: 'batman-begins-scarecrow', descriptionPt: 'Dr. Jonathan Crane é um personagem fictício do filme Batman Begins (2005), também conhecido como Espantalho. Interpretado por Cillian Murphy, ele combina psicologia, manipulação e terrorismo químico, explorando o medo como arma.', descriptionEn: 'Dr. Jonathan Crane is a fictional character in Batman Begins (2005), also known as the Scarecrow. Played by Cillian Murphy, he combines psychology, manipulation, and chemical terrorism, exploiting fear as a weapon.' },
  ICX: { name: 'Theodore Twombly', imageQuery: 'her-2013-joaquin-phoenix', descriptionPt: 'Theodore Twombly é o protagonista do filme Her, interpretado por Joaquin Phoenix. Theodore é um homem solitário que desenvolve uma relação emocional com um sistema operacional inteligente chamado Samantha.', descriptionEn: 'Theodore Twombly is the protagonist of Her, played by Joaquin Phoenix. He is a lonely man who develops an emotional relationship with an intelligent operating system named Samantha.' },
  ICK: { name: 'Spock', imageQuery: 'star-trek-spock', descriptionPt: 'Spock é um personagem fictício da franquia Star Trek, conhecido por sua lógica impecável e herança mista humana e vulcana. Tornou-se um dos ícones mais duradouros da cultura pop e símbolo do equilíbrio entre razão e emoção.', descriptionEn: 'Spock is a fictional character in the Star Trek franchise, known for his impeccable logic and mixed human-Vulcan heritage. He became one of the most enduring pop culture icons and a symbol of the balance between reason and emotion.' },
  ICD: { name: 'Rorschach', imageQuery: 'watchmen-rorschach', descriptionPt: 'Rorschach é um personagem fictício da graphic novel Watchmen. Vigilante mascarado em uma Nova York alternativa dos anos 1980, ele é conhecido por seu moralismo absoluto e sua máscara mutante.', descriptionEn: 'Rorschach is a fictional character from the Watchmen graphic novel. A masked vigilante in an alternate 1980s New York, he is known for his absolute moralism and his shifting ink-blot mask.' },
  ICL: { name: 'Luna Lovegood', imageQuery: 'harry-potter-luna-lovegood', descriptionPt: 'Luna Lovegood é uma personagem fictícia do universo Harry Potter. Conhecida por sua personalidade excêntrica, inteligência intuitiva e lealdade aos amigos, interpretada por Evanna Lynch nos filmes.', descriptionEn: 'Luna Lovegood is a fictional character from the Harry Potter universe. Known for her eccentric personality, intuitive intelligence, and loyalty to her friends, she is played by Evanna Lynch in the films.' },
  IRA: { name: 'Ender Wiggin', imageQuery: 'enders-game-ender-wiggin', descriptionPt: 'Ender Wiggin é o protagonista fictício de Ender\'s Game. Ele é uma criança prodígio treinada para se tornar o comandante supremo das forças humanas em uma guerra contra alienígenas, explorando temas de liderança, empatia e moralidade.', descriptionEn: 'Ender Wiggin is the fictional protagonist of Ender\'s Game. He is a child prodigy trained to become the supreme commander of human forces in a war against an alien race, exploring themes of leadership, empathy, and morality.' },
  IRB: { name: 'Jigsaw', imageQuery: 'saw-jigsaw-killer', descriptionPt: 'Jigsaw, nome real John Kramer, é o principal antagonista da franquia de filmes Saw. Conhecido como "o assassino do quebra-cabeça", ele submete suas vítimas a armadilhas brutais para testar sua vontade de viver.', descriptionEn: 'Jigsaw, real name John Kramer, is the main antagonist of the Saw film franchise. Known as the "jigsaw killer", he subjects his victims to brutal traps to test their will to live.' },
  IRX: { name: 'Kevin Wendell Crumb', imageQuery: 'split-2016-james-mcavoy', descriptionPt: 'Kevin Wendell Crumb é o personagem principal do filme Split, dirigido por M. Night Shyamalan. Ele abriga 23 personalidades distintas e uma 24ª sobre-humana conhecida como "A Fera". Interpretado por James McAvoy.', descriptionEn: 'Kevin Wendell Crumb is the main character of Split, directed by M. Night Shyamalan. He harbors 23 distinct personalities and a 24th superhuman one known as "The Beast", played by James McAvoy.' },
  IRK: { name: 'Hercule Poirot', imageQuery: 'hercule-poirot-agatha-christie', descriptionPt: 'Hercule Poirot é um detetive fictício criado por Agatha Christie. De origem belga, é um dos personagens mais icônicos da literatura policial, conhecido por seu intelecto meticuloso e obsessão pela ordem e pelos "pequenos detalhes".', descriptionEn: 'Hercule Poirot is a fictional detective created by Agatha Christie. Of Belgian origin, he is one of the most iconic characters in crime literature, known for his meticulous intellect and obsession with order and "the little grey cells".' },
  IRD: { name: 'Michael Scofield', imageQuery: 'prison-break-michael-scofield', descriptionPt: 'Michael Scofield é o protagonista fictício da série Prison Break, interpretado por Wentworth Miller. Ele é um engenheiro estrutural brilhante que se infiltra deliberadamente em uma prisão para resgatar seu irmão condenado injustamente.', descriptionEn: 'Michael Scofield is the fictional protagonist of Prison Break, played by Wentworth Miller. He is a brilliant structural engineer who deliberately infiltrates a prison to rescue his unjustly condemned brother.' },
  IRL: { name: 'Rusty Ryan', imageQuery: "ocean's-eleven-brad-pitt", descriptionPt: 'Rusty Ryan é um personagem fictício da série de filmes Ocean\'s, interpretado por Brad Pitt. Ele é o carismático braço direito de Danny Ocean, conhecido por sua inteligência, calma sob pressão e constante apetite.', descriptionEn: 'Rusty Ryan is a fictional character from the Ocean\'s film series, played by Brad Pitt. He is the charismatic right-hand man of Danny Ocean, known for his intelligence, composure under pressure, and constant appetite.' },
  ISA: { name: 'Doc Brown', imageQuery: 'back-to-future-doc-brown-christopher-lloyd', descriptionPt: 'Doc Brown (Dr. Emmett Brown) é um personagem fictício da franquia Back to the Future, interpretado por Christopher Lloyd. Ele é o excêntrico cientista responsável por inventar a máquina do tempo em um DeLorean.', descriptionEn: 'Doc Brown (Dr. Emmett Brown) is a fictional character from the Back to the Future franchise, played by Christopher Lloyd. He is the eccentric scientist who invents the time machine in a DeLorean.' },
  ISB: { name: 'John Doe', imageQuery: 'se7en-kevin-spacey-john-doe', descriptionPt: 'John Doe é o assassino fictício do thriller policial Se7en, interpretado por Kevin Spacey. O personagem é o vilão central cuja série de crimes brutais gira em torno dos sete pecados capitais.', descriptionEn: 'John Doe is the fictional killer in the crime thriller Se7en, played by Kevin Spacey. The central villain whose series of brutal crimes revolves around the seven deadly sins.' },
  ISX: { name: 'Major Kusanagi', imageQuery: 'ghost-in-shell-major-kusanagi', descriptionPt: 'Major Motoko Kusanagi é a protagonista cibernética da franquia Ghost in the Shell. Ela simboliza a fusão entre humanidade e tecnologia, explorando os limites da consciência e da identidade em um mundo altamente conectado.', descriptionEn: 'Major Motoko Kusanagi is the cybernetic protagonist of the Ghost in the Shell franchise. She symbolizes the fusion of humanity and technology, exploring the limits of consciousness and identity in a hyper-connected world.' },
  ISK: { name: 'HAL 9000', imageQuery: '2001-space-odyssey-hal-9000', descriptionPt: 'HAL 9000 é uma inteligência artificial ficcional central do filme 2001: A Space Odyssey, de Stanley Kubrick. Representa o ápice da tecnologia de computadores conscientes e simboliza tanto o potencial quanto os perigos da inteligência artificial.', descriptionEn: 'HAL 9000 is a fictional artificial intelligence at the center of Stanley Kubrick\'s 2001: A Space Odyssey. It represents the pinnacle of conscious computer technology and symbolizes both the potential and dangers of artificial intelligence.' },
  ISD: { name: 'Roy Batty', imageQuery: 'blade-runner-roy-batty-rutger-hauer', descriptionPt: 'Roy Batty é o carismático líder dos replicantes em Blade Runner (1982), interpretado por Rutger Hauer. Sua busca por mais vida e significado faz dele uma das figuras mais complexas do cinema de ficção científica.', descriptionEn: 'Roy Batty is the charismatic leader of the replicants in Blade Runner (1982), played by Rutger Hauer. His search for more life and meaning makes him one of the most complex figures in science fiction cinema.' },
  ISL: { name: 'Emmet Brickowski', imageQuery: 'lego-movie-emmet', descriptionPt: 'Emmet Brickowski é o protagonista de The Lego Movie. Ele é um boneco Lego comum que inesperadamente se torna o herói de uma aventura épica, destacando temas de criatividade e colaboração.', descriptionEn: 'Emmet Brickowski is the protagonist of The Lego Movie. He is an ordinary Lego minifigure who unexpectedly becomes the hero of an epic adventure, highlighting themes of creativity and collaboration.' },
  CEA: { name: 'Walter Mitty', imageQuery: 'secret-life-walter-mitty-ben-stiller', descriptionPt: 'Walter Mitty é o personagem principal de The Secret Life of Walter Mitty, estrelado por Ben Stiller. Um homem comum e sonhador que vive aventuras extraordinárias em sua imaginação, até que circunstâncias o levam a viver experiências reais transformadoras.', descriptionEn: 'Walter Mitty is the main character of The Secret Life of Walter Mitty, starring Ben Stiller. An ordinary daydreamer who lives extraordinary adventures in his imagination, until circumstances lead him to experience real transformative adventures.' },
  CEB: { name: 'Travis Bickle', imageQuery: 'taxi-driver-robert-de-niro-travis', descriptionPt: 'Travis Bickle é o protagonista fictício do filme Taxi Driver, interpretado por Robert De Niro. Tornou-se um dos personagens mais icônicos do cinema americano, símbolo de alienação urbana e colapso psicológico.', descriptionEn: 'Travis Bickle is the fictional protagonist of Taxi Driver, played by Robert De Niro. He became one of the most iconic characters in American cinema, a symbol of urban alienation and psychological collapse.' },
  CEX: { name: 'The Narrator', imageQuery: 'persona-bergman-film', descriptionPt: 'O Narrador é uma figura metacinematográfica do filme Persona, de Ingmar Bergman. Ele representa a consciência do próprio filme e sua reflexão sobre identidade, percepção e a natureza da arte.', descriptionEn: 'The Narrator is a metacinematic figure in Ingmar Bergman\'s Persona. He represents the consciousness of the film itself and its reflection on identity, perception, and the nature of art.' },
  CEK: { name: 'Lawrence of Arabia', imageQuery: 'lawrence-of-arabia-peter-otoole', descriptionPt: 'Lawrence of Arabia é o personagem principal do épico cinematográfico de 1962, interpretado por Peter O\'Toole. É uma representação dramática de um homem dividido entre culturas e identidades durante a Primeira Guerra Mundial.', descriptionEn: 'Lawrence of Arabia is the main character of the 1962 epic film, played by Peter O\'Toole. He is a dramatic representation of a man divided between cultures and identities during World War I.' },
  CED: { name: 'Daniel Plainview', imageQuery: 'there-will-be-blood-daniel-day-lewis', descriptionPt: 'Daniel Plainview é o protagonista fictício do filme There Will Be Blood, interpretado por Daniel Day-Lewis. Um ambicioso empresário do petróleo do início do século XX, simboliza o poder corrosivo da ganância no capitalismo americano.', descriptionEn: 'Daniel Plainview is the fictional protagonist of There Will Be Blood, played by Daniel Day-Lewis. An ambitious oil entrepreneur from the early 20th century, he symbolizes the corrosive power of greed in American capitalism.' },
  CEL: { name: 'Jules Winnfield', imageQuery: 'pulp-fiction-samuel-l-jackson-jules', descriptionPt: 'Jules Winnfield é um personagem fictício do filme Pulp Fiction, interpretado por Samuel L. Jackson. Ele é um matador filosófico e carismático cuja retórica intensa e transformação espiritual tornaram-se ícones do cinema moderno.', descriptionEn: 'Jules Winnfield is a fictional character in Pulp Fiction, played by Samuel L. Jackson. He is a philosophical and charismatic hitman whose intense rhetoric and spiritual transformation became icons of modern cinema.' },
  CIA: { name: 'Ikiru Watanabe', imageQuery: 'ikiru-kurosawa-1952', descriptionPt: 'Ikiru Watanabe é o protagonista do filme japonês Ikiru, de Akira Kurosawa. Um burocrata de Tóquio que enfrenta o vazio existencial ao descobrir estar com câncer terminal. Sua jornada transforma-se em uma reflexão sobre o sentido da vida.', descriptionEn: 'Ikiru Watanabe is the protagonist of Akira Kurosawa\'s Japanese film Ikiru. A Tokyo bureaucrat who confronts existential emptiness after discovering he has terminal cancer, his journey becomes a reflection on the meaning of life.' },
  CIB: { name: 'Adrian Veidt', imageQuery: 'watchmen-ozymandias-veidt', descriptionPt: 'Adrian Veidt, conhecido como Ozymandias, é um personagem fictício de Watchmen. Retratado como o homem mais inteligente do mundo, ele é um dos vigilantes mais influentes e controversos de sua era.', descriptionEn: 'Adrian Veidt, known as Ozymandias, is a fictional character from Watchmen. Portrayed as the world\'s smartest man, he is one of the most influential and controversial vigilantes of his era.' },
  CIX: { name: 'O Stalker', imageQuery: 'stalker-tarkovsky-1979', descriptionPt: 'O Stalker é o personagem central do filme soviético de ficção científica Stalker, de Andrei Tarkovsky. Ele guia dois homens através de uma área misteriosa e proibida chamada Zona, que supostamente concede os desejos mais profundos.', descriptionEn: 'The Stalker is the central character of Andrei Tarkovsky\'s Soviet sci-fi film Stalker. He guides two men through a mysterious forbidden area called the Zone, which supposedly grants the deepest wishes of those who reach its center.' },
  CIK: { name: 'Antonius Block', imageQuery: 'seventh-seal-max-von-sydow', descriptionPt: 'Antonius Block é o cavaleiro fictício de O Sétimo Selo (1957), de Ingmar Bergman. Ele enfrenta uma personificação da Morte em uma partida de xadrez, buscando sentido e fé em meio à peste e ao silêncio divino.', descriptionEn: 'Antonius Block is the fictional knight in Ingmar Bergman\'s The Seventh Seal (1957). He faces a personification of Death in a game of chess, seeking meaning and faith amid plague and divine silence.' },
  CID: { name: 'Amon Göth', imageQuery: 'schindlers-list-ralph-fiennes', descriptionPt: 'Amon Göth é um personagem fictício do filme Schindler\'s List. Baseado em figura histórica real, é retratado como o comandante brutal de um campo de concentração durante a Segunda Guerra Mundial, interpretado por Ralph Fiennes.', descriptionEn: 'Amon Göth is a fictional character in Schindler\'s List, based on a real historical figure. He is portrayed as the brutal commander of a concentration camp during World War II, played by Ralph Fiennes.' },
  CIL: { name: 'Guido', imageQuery: 'eight-and-half-fellini-mastroianni', descriptionPt: 'Guido é o protagonista do filme italiano 8½, de Federico Fellini. Interpretado por Marcello Mastroianni, ele é um diretor de cinema em crise criativa e existencial, amplamente visto como o alter ego de Fellini.', descriptionEn: 'Guido is the protagonist of Federico Fellini\'s 8½, played by Marcello Mastroianni. He is a film director in creative and existential crisis, widely seen as Fellini\'s alter ego.' },
  CRA: { name: 'Aang', imageQuery: 'avatar-aang-last-airbender', descriptionPt: 'Aang é o protagonista da série animada Avatar: The Last Airbender. Ele é o último sobrevivente dos Nômades do Ar e o atual Avatar, responsável por manter o equilíbrio entre as quatro nações e os elementos.', descriptionEn: 'Aang is the protagonist of Avatar: The Last Airbender. He is the last survivor of the Air Nomads and the current Avatar, responsible for maintaining balance between the four nations and the elements.' },
  CRB: { name: 'Harry Lime', imageQuery: 'the-third-man-orson-welles', descriptionPt: 'Harry Lime é um personagem fictício central de The Third Man, estrelado por Orson Welles. É um contrabandista carismático e moralmente ambíguo na Viena pós-Segunda Guerra Mundial, cuja presença domina o filme mesmo aparecendo em poucas cenas.', descriptionEn: 'Harry Lime is a central fictional character in The Third Man, played by Orson Welles. He is a charismatic and morally ambiguous smuggler in post-WWII Vienna whose presence dominates the film despite appearing in few scenes.' },
  CRX: { name: 'Lain Iwakura', imageQuery: 'serial-experiments-lain-anime', descriptionPt: 'Lain Iwakura é a protagonista da série de anime Serial Experiments Lain (1998). Uma adolescente introspectiva cuja jornada explora a interseção entre identidade, consciência e tecnologia digital.', descriptionEn: 'Lain Iwakura is the protagonist of the anime series Serial Experiments Lain (1998). An introspective teenager whose journey explores the intersection of identity, consciousness, and digital technology.' },
  CRK: { name: 'Aragorn', imageQuery: 'lord-of-rings-aragorn-viggo-mortensen', descriptionPt: 'Aragorn é um personagem fictício da trilogia The Lord of the Rings. Um dos protagonistas da saga e heróis centrais da Terceira Era da Terra-média, símbolo de liderança, coragem e legitimidade real.', descriptionEn: 'Aragorn is a fictional character from The Lord of the Rings trilogy. One of the saga\'s protagonists and central heroes of Middle-earth\'s Third Age, he is a symbol of leadership, courage, and royal legitimacy.' },
  CRD: { name: 'Príncipe Ashitaka', imageQuery: 'princess-mononoke-ashitaka-ghibli', descriptionPt: 'O Príncipe Ashitaka é o protagonista de Princess Mononoke, de Hayao Miyazaki. Um jovem príncipe cuja jornada o coloca no centro de um conflito entre a natureza e a industrialização.', descriptionEn: 'Prince Ashitaka is the protagonist of Hayao Miyazaki\'s Princess Mononoke. A young prince whose journey places him at the center of a conflict between nature and industrialization.' },
  CRL: { name: 'Kiki', imageQuery: "kiki's-delivery-service-ghibli", descriptionPt: 'Kiki é a jovem protagonista de Kiki\'s Delivery Service (1989), de Hayao Miyazaki. Uma bruxa em treinamento que parte de casa para aprender sobre independência e responsabilidade.', descriptionEn: "Kiki is the young protagonist of Hayao Miyazaki's Kiki's Delivery Service (1989). A witch in training who leaves home to learn about independence and responsibility." },
  CSA: { name: 'Maria', imageQuery: 'sound-of-music-julie-andrews-maria', descriptionPt: 'Maria é a protagonista do filme musical The Sound of Music, interpretada por Julie Andrews. Baseada em Maria von Trapp, ela é uma noviça austríaca que se torna governanta da família von Trapp e depois esposa do capitão.', descriptionEn: 'Maria is the protagonist of The Sound of Music, played by Julie Andrews. Based on Maria von Trapp, she is an Austrian novice who becomes the Von Trapp family governess and later the captain\'s wife.' },
  CSB: { name: 'Tom Ripley', imageQuery: 'talented-mr-ripley-matt-damon', descriptionPt: 'Tom Ripley é o protagonista fictício de O Talentoso Ripley, interpretado por Matt Damon. Um jovem impostor de personalidade enigmática, ambição obsessiva e moral ambígua.', descriptionEn: 'Tom Ripley is the fictional protagonist of The Talented Mr. Ripley, played by Matt Damon. A young impostor with an enigmatic personality, obsessive ambition, and ambiguous morality.' },
  CSX: { name: 'Pinóquio', imageQuery: 'pinocchio-guillermo-del-toro', descriptionPt: 'Pinóquio é o protagonista do filme em stop motion de Guillermo del Toro. Inspirado no romance clássico de Carlo Collodi, essa versão reinventa o boneco de madeira como um símbolo de inocência e desobediência.', descriptionEn: 'Pinocchio is the protagonist of Guillermo del Toro\'s stop-motion film. Inspired by Carlo Collodi\'s classic novel, this version reimagines the wooden puppet as a symbol of innocence and defiance.' },
  CSK: { name: 'Jay Gatsby', imageQuery: 'great-gatsby-leonardo-dicaprio', descriptionPt: 'Jay Gatsby é o personagem central de The Great Gatsby. Figura enigmática e símbolo do sonho americano, conhecido por sua riqueza extravagante, festas luxuosas e paixão obsessiva por Daisy Buchanan.', descriptionEn: 'Jay Gatsby is the central character of The Great Gatsby. An enigmatic figure and symbol of the American Dream, known for his extravagant wealth, lavish parties, and obsessive passion for Daisy Buchanan.' },
  CSD: { name: 'Capitão Willard', imageQuery: 'apocalypse-now-martin-sheen-willard', descriptionPt: 'Capitão Willard é o personagem central de Apocalypse Now, interpretado por Martin Sheen. Um oficial do Exército dos EUA enviado em missão secreta para eliminar o coronel renegado Walter E. Kurtz durante a Guerra do Vietnã.', descriptionEn: 'Captain Willard is the central character of Apocalypse Now, played by Martin Sheen. A U.S. Army officer sent on a secret mission to eliminate the renegade Colonel Kurtz during the Vietnam War.' },
  CSL: { name: 'Monsieur Hulot', imageQuery: 'monsieur-hulot-holiday-tati', descriptionPt: 'Monsieur Hulot é o personagem central criado e interpretado por Jacques Tati. Figura excêntrica, gentil e desajeitada, tornou-se um dos ícones cômicos mais duradouros do cinema francês do pós-guerra.', descriptionEn: 'Monsieur Hulot is the central character created and played by Jacques Tati. An eccentric, gentle, and clumsy figure, he became one of the most enduring comic icons of postwar French cinema.' },
  REA: { name: 'Paddington', imageQuery: 'paddington-bear-movie', descriptionPt: 'Paddington é um urso educado e bem-intencionado originário do "Darkest Peru", que se torna protagonista dos filmes Paddington. Criado por Michael Bond, ele vive aventuras em Londres com a família Brown.', descriptionEn: 'Paddington is a polite and well-meaning bear from "Darkest Peru" who becomes the protagonist of the Paddington films. Created by Michael Bond, he lives adventures in London with the Brown family.' },
  REB: { name: 'Cruella de Vil', imageQuery: 'cruella-de-vil-101-dalmatians', descriptionPt: 'Cruella de Vil é a principal antagonista de 101 Dálmatas, retratada como uma socialite excêntrica e obcecada por moda que deseja fazer casacos de pele com filhotes de dálmata.', descriptionEn: 'Cruella de Vil is the main antagonist of 101 Dalmatians, portrayed as an eccentric, fashion-obsessed socialite who wants to make fur coats from dalmatian puppies.' },
  REX: { name: 'Baby', imageQuery: 'baby-driver-ansel-elgort', descriptionPt: 'Baby é o protagonista do filme Baby Driver, interpretado por Ansel Elgort. Um jovem e talentoso motorista de fuga que usa a música como refúgio para lidar com um zumbido crônico nos ouvidos.', descriptionEn: 'Baby is the protagonist of Baby Driver, played by Ansel Elgort. A young and talented getaway driver who uses music as refuge to cope with a chronic ringing in his ears.' },
  REK: { name: 'Danny Ocean', imageQuery: "ocean's-eleven-george-clooney", descriptionPt: 'Danny Ocean é o protagonista da franquia de filmes Ocean\'s Eleven, interpretado por George Clooney. Símbolo do golpista elegante e calculista no cinema de assaltos.', descriptionEn: 'Danny Ocean is the protagonist of the Ocean\'s Eleven film franchise, played by George Clooney. A symbol of the elegant and calculating con man in heist cinema.' },
  RED: { name: 'Jordan Belfort', imageQuery: 'wolf-of-wall-street-leonardo-dicaprio', descriptionPt: 'Jordan Belfort é o protagonista de The Wolf of Wall Street, de Martin Scorsese. Baseado em pessoa real, é um corretor de ações ambicioso cuja ascensão e queda ilustram o excesso e a corrupção de Wall Street.', descriptionEn: 'Jordan Belfort is the protagonist of The Wolf of Wall Street by Martin Scorsese. Based on a real person, he is an ambitious stockbroker whose meteoric rise and spectacular fall illustrate the excess and corruption of Wall Street.' },
  REL: { name: 'Ferris Bueller', imageQuery: 'ferris-buellers-day-off-matthew-broderick', descriptionPt: 'Ferris Bueller é o protagonista de Ferris Bueller\'s Day Off, interpretado por Matthew Broderick. O arquétipo do estudante espirituoso e rebelde dos anos 1980 que desafia regras em busca de liberdade.', descriptionEn: 'Ferris Bueller is the protagonist of Ferris Bueller\'s Day Off, played by Matthew Broderick. The archetype of the witty and rebellious 1980s student who defies rules in pursuit of freedom.' },
  RIA: { name: 'Woody', imageQuery: 'toy-story-woody-tom-hanks', descriptionPt: 'Woody é o protagonista da franquia Toy Story, criada pela Pixar. Um boneco de caubói que atua como líder e figura paternal entre os brinquedos de Andy.', descriptionEn: 'Woody is the protagonist of Pixar\'s Toy Story franchise. A cowboy doll who acts as leader and paternal figure among Andy\'s toys, voiced by Tom Hanks.' },
  RIB: { name: 'Sid Phillips', imageQuery: 'toy-story-sid-phillips', descriptionPt: 'Sid Phillips é o principal antagonista do primeiro Toy Story (1995). Conhecido por seu comportamento destrutivo com brinquedos, tornou-se um dos vilões infantis mais memoráveis da animação moderna.', descriptionEn: 'Sid Phillips is the main antagonist of the first Toy Story (1995). Known for his destructive behavior with toys, he became one of the most memorable child villains in modern animation.' },
  RIX: { name: 'Vanellope', imageQuery: 'wreck-it-ralph-vanellope', descriptionPt: 'Vanellope von Schweetz é uma personagem de Wreck-It Ralph. Uma corredora carismática e rebelde do jogo "Sugar Rush", conhecida por seu espírito determinado e sua habilidade de "glitchar".', descriptionEn: 'Vanellope von Schweetz is a character from Wreck-It Ralph. A charismatic and rebellious racer from the game "Sugar Rush", known for her determined spirit and ability to "glitch".' },
  RIK: { name: 'George Bailey', imageQuery: "it's-a-wonderful-life-james-stewart", descriptionPt: 'George Bailey é o protagonista de It\'s a Wonderful Life (1946), interpretado por James Stewart. Um homem generoso e idealista que sacrifica seus sonhos para ajudar os outros, símbolo de empatia e propósito.', descriptionEn: 'George Bailey is the protagonist of It\'s a Wonderful Life (1946), played by James Stewart. A generous and idealistic man who sacrifices his dreams to help others, a symbol of empathy and purpose.' },
  RID: { name: 'Cady Heron', imageQuery: 'mean-girls-lindsay-lohan-cady', descriptionPt: 'Cady Heron é a protagonista de Mean Girls, interpretada por Lindsay Lohan. Criada na África, ela entra em uma escola americana e tenta se adaptar às complexas dinâmicas sociais do ensino médio.', descriptionEn: 'Cady Heron is the protagonist of Mean Girls, played by Lindsay Lohan. Raised in Africa, she enters an American high school and tries to adapt to its complex social dynamics.' },
  RIL: { name: 'Shrek', imageQuery: 'shrek-dreamworks-animation', descriptionPt: 'Shrek é o protagonista da franquia de animação Shrek, da DreamWorks. Um ogro verde que vive isolado em um pântano e se tornou um dos ícones mais reconhecíveis da animação moderna.', descriptionEn: 'Shrek is the protagonist of DreamWorks\' Shrek animation franchise. A green ogre who lives isolated in a swamp and became one of the most recognizable icons of modern animation.' },
  RCA: { name: 'Miguel Rivera', imageQuery: 'coco-pixar-miguel-rivera', descriptionPt: 'Miguel Rivera é o protagonista do filme animado Coco (2017) da Pixar. Um menino mexicano apaixonado por música que desafia as tradições familiares ao sonhar em se tornar músico.', descriptionEn: 'Miguel Rivera is the protagonist of Pixar\'s animated film Coco (2017). A Mexican boy passionate about music who defies family traditions by dreaming of becoming a musician.' },
  RCB: { name: 'Selina Kyle', imageQuery: 'the-batman-catwoman-zoe-kravitz', descriptionPt: 'Selina Kyle é interpretada por Zoë Kravitz em The Batman. A Mulher-Gato é uma ladra e vigilante de Gotham City que se move entre o crime e a justiça, tornando-se aliada e contraponto moral de Bruce Wayne.', descriptionEn: 'Selina Kyle is played by Zoë Kravitz in The Batman. Catwoman is a Gotham City thief and vigilante who moves between crime and justice, becoming both ally and moral counterpoint to Bruce Wayne.' },
  RCX: { name: 'Evelyn Wang', imageQuery: 'everything-everywhere-all-at-once-michelle-yeoh', descriptionPt: 'Evelyn Wang é a protagonista de Everything Everywhere All at Once, interpretada por Michelle Yeoh. Uma imigrante chinesa nos EUA que descobre estar conectada a múltiplas versões de si mesma em universos paralelos.', descriptionEn: 'Evelyn Wang is the protagonist of Everything Everywhere All at Once, played by Michelle Yeoh. A Chinese immigrant in the US who discovers she is connected to multiple versions of herself across parallel universes.' },
  RCK: { name: 'Phileas Fogg', imageQuery: 'around-world-eighty-days-phileas-fogg', descriptionPt: 'Phileas Fogg é o protagonista de Around the World in Eighty Days, de Jules Verne. Um cavalheiro inglês metódico e reservado que aposta poder dar a volta ao mundo em 80 dias.', descriptionEn: 'Phileas Fogg is the protagonist of Jules Verne\'s Around the World in Eighty Days. A methodical and reserved English gentleman who bets he can circumnavigate the globe in 80 days.' },
  RCD: { name: 'Rick Deckard', imageQuery: 'blade-runner-rick-deckard-harrison-ford', descriptionPt: 'Rick Deckard é o protagonista da franquia Blade Runner, interpretado por Harrison Ford. Ele é um agente especializado em caçar e "aposentar" replicantes — seres artificiais indistinguíveis de humanos.', descriptionEn: 'Rick Deckard is the protagonist of the Blade Runner franchise, played by Harrison Ford. He is a specialized agent hunting down and "retiring" replicants — artificial beings indistinguishable from humans.' },
  RCL: { name: 'Linguini', imageQuery: 'ratatouille-pixar-linguini', descriptionPt: 'Linguini (Alfredo Linguini) é um dos protagonistas de Ratatouille, da Pixar (2007). Conhecido por sua relação improvável com o rato chef Remy.', descriptionEn: 'Linguini (Alfredo Linguini) is one of the protagonists of Pixar\'s Ratatouille (2007), known for his unlikely relationship with the chef rat Remy.' },
  RSA: { name: 'Olaf', imageQuery: 'frozen-olaf-snowman-disney', descriptionPt: 'Olaf é um personagem fictício do filme Frozen, da Disney. Um boneco de neve encantado que serve como alívio cômico e símbolo de inocência e amizade.', descriptionEn: 'Olaf is a fictional character from Disney\'s Frozen. An enchanted snowman who serves as comic relief and a symbol of innocence and friendship.' },
  RSB: { name: 'Harley Quinn', imageQuery: 'harley-quinn-margot-robbie-suicide-squad', descriptionPt: 'Harley Quinn é interpretada por Margot Robbie no universo DC. Integrante do Suicide Squad, ela é conhecida por sua estética marcante e comportamento imprevisível.', descriptionEn: 'Harley Quinn is played by Margot Robbie in the DC universe. A member of Suicide Squad, she is known for her striking aesthetic and unpredictable behavior.' },
  RSX: { name: 'Deadpool', imageQuery: 'deadpool-marvel-ryan-reynolds', descriptionPt: 'Deadpool é um personagem da Marvel Comics, conhecido por seu humor sarcástico, consciência metalinguística e habilidades de regeneração. Tornou-se um dos anti-heróis mais populares da cultura pop.', descriptionEn: 'Deadpool is a Marvel Comics character known for his sarcastic humor, meta-awareness, and regenerative abilities. He became one of the most popular anti-heroes in pop culture.' },
  RSK: { name: 'Han Solo', imageQuery: 'star-wars-han-solo-harrison-ford', descriptionPt: 'Han Solo é um personagem do universo Star Wars, interpretado por Harrison Ford. Um contrabandista que se torna herói da Aliança Rebelde, um dos ícones mais reconhecíveis da cultura pop.', descriptionEn: 'Han Solo is a Star Wars character, played by Harrison Ford. A smuggler who becomes a hero of the Rebel Alliance, one of the most recognizable icons in pop culture.' },
  RSD: { name: 'Jake Sully', imageQuery: 'avatar-jake-sully-james-cameron', descriptionPt: 'Jake Sully é o protagonista fictício do universo Avatar, de James Cameron. Ex-fuzileiro naval paraplégico, torna-se o elo entre humanos e os Na\'vi, ao assumir um corpo avatar.', descriptionEn: 'Jake Sully is the fictional protagonist of James Cameron\'s Avatar universe. A paraplegic former Marine, he becomes the link between humans and the Na\'vi by inhabiting an avatar body.' },
  RSL: { name: 'Kuzco', imageQuery: 'emperors-new-groove-kuzco-disney', descriptionPt: 'Kuzco é o protagonista de A Nova Onda do Imperador, da Disney. Um jovem imperador inca egocêntrico que aprende humildade e empatia após ser transformado em uma lhama.', descriptionEn: 'Kuzco is the protagonist of Disney\'s The Emperor\'s New Groove. A self-centered young Inca emperor who learns humility and empathy after being transformed into a llama.' },
  SEA: { name: 'Maverick', imageQuery: 'top-gun-maverick-tom-cruise', descriptionPt: '"Maverick" é o codinome de Pete Mitchell, protagonista da franquia Top Gun, interpretado por Tom Cruise. Um piloto da Marinha dos EUA conhecido por sua ousadia e espírito rebelde.', descriptionEn: '"Maverick" is the callsign of Pete Mitchell, protagonist of the Top Gun franchise, played by Tom Cruise. A U.S. Navy pilot known for his daring and rebellious spirit.' },
  SEB: { name: 'Patrick Bateman', imageQuery: 'american-psycho-christian-bale-bateman', descriptionPt: 'Patrick Bateman é o protagonista de American Psycho, interpretado por Christian Bale. Um executivo de Manhattan cuja vida dupla como serial killer serve de sátira à cultura consumista dos anos 1980.', descriptionEn: 'Patrick Bateman is the protagonist of American Psycho, played by Christian Bale. A Manhattan executive whose double life as a serial killer serves as a satire of 1980s consumer culture.' },
  SEX: { name: 'Max Rockatansky', imageQuery: 'mad-max-fury-road', descriptionPt: 'Max Rockatansky é o protagonista da franquia Mad Max. Um ex-policial que sobrevive em um mundo pós-apocalíptico dominado pela escassez e violência, símbolo do anti-herói solitário.', descriptionEn: 'Max Rockatansky is the protagonist of the Mad Max franchise. A former police officer surviving in a post-apocalyptic world dominated by scarcity and violence, symbolizing the solitary anti-hero.' },
  SEK: { name: 'Indiana Jones', imageQuery: 'indiana-jones-harrison-ford', descriptionPt: 'Indiana Jones é um arqueólogo e aventureiro fictício, interpretado por Harrison Ford. Criado por George Lucas, tornou-se um ícone da cultura pop por combinar erudição acadêmica com coragem.', descriptionEn: 'Indiana Jones is a fictional archaeologist and adventurer, played by Harrison Ford. Created by George Lucas, he became a pop culture icon for combining academic scholarship with courage.' },
  SED: { name: 'Neil McCauley', imageQuery: 'heat-1995-robert-de-niro-neil', descriptionPt: 'Neil McCauley é o personagem principal do filme Heat, interpretado por Robert De Niro. Um ladrão profissional meticuloso que lidera uma equipe de assaltantes em Los Angeles.', descriptionEn: 'Neil McCauley is the main character of Heat, played by Robert De Niro. A meticulous professional thief who leads a crew of robbers in Los Angeles.' },
  SEL: { name: 'Peter Parker', imageQuery: 'spider-man-peter-parker-tom-holland', descriptionPt: 'Peter Parker é o alter ego do Homem-Aranha no MCU, interpretado por Tom Holland. Um estudante do Queens que adquire poderes aracnídeos e se torna um dos heróis centrais dos Vingadores.', descriptionEn: 'Peter Parker is Spider-Man\'s alter ego in the MCU, played by Tom Holland. A Queens student who acquires spider-like powers and becomes one of the central heroes of the Avengers.' },
  SIA: { name: 'The Dude', imageQuery: 'big-lebowski-jeff-bridges-dude', descriptionPt: 'Jeffrey "The Dude" Lebowski é o protagonista de The Big Lebowski, interpretado por Jeff Bridges. Um ícone cultural conhecido por seu estilo despreocupado e filosofia "go with the flow".', descriptionEn: 'Jeffrey "The Dude" Lebowski is the protagonist of The Big Lebowski, played by Jeff Bridges. A cultural icon known for his laid-back style and "go with the flow" philosophy.' },
  SIB: { name: 'Alex DeLarge', imageQuery: 'clockwork-orange-alex-delarge', descriptionPt: 'Alex DeLarge é o protagonista fictício de A Clockwork Orange, de Kubrick, interpretado por Malcolm McDowell. Tornou-se um ícone cultural por sua combinação de charme, violência e crítica social.', descriptionEn: 'Alex DeLarge is the fictional protagonist of Kubrick\'s A Clockwork Orange, played by Malcolm McDowell. He became a cultural icon for his combination of charm, violence, and social commentary.' },
  SIX: { name: 'Donnie Darko', imageQuery: 'donnie-darko-jake-gyllenhaal', descriptionPt: 'Donnie Darko é o protagonista do filme de 2001 de mesmo nome, interpretado por Jake Gyllenhaal. Um adolescente problemático que enfrenta visões apocalípticas e dilemas sobre destino e livre-arbítrio.', descriptionEn: 'Donnie Darko is the protagonist of the 2001 film of the same name, played by Jake Gyllenhaal. A troubled teenager who faces apocalyptic visions and dilemmas about fate and free will.' },
  SIK: { name: 'James Bond', imageQuery: 'james-bond-007-spy', descriptionPt: 'James Bond é um personagem fictício criado por Ian Fleming em 1953. Conhecido pelo codinome "007", é um agente secreto do MI6 e se tornou um ícone global, representando o espião sofisticado e carismático.', descriptionEn: 'James Bond is a fictional character created by Ian Fleming in 1953. Known by the code name "007", he is a British MI6 secret agent who became a global icon representing the sophisticated and charismatic spy.' },
  SID: { name: 'K', imageQuery: 'blade-runner-2049-ryan-gosling-k', descriptionPt: 'K é o personagem principal de Blade Runner 2049, interpretado por Ryan Gosling. Um "blade runner" replicante em uma jornada de autodescoberta e humanidade em um mundo dominado por IA.', descriptionEn: 'K is the main character of Blade Runner 2049, played by Ryan Gosling. A replicant blade runner on a journey of self-discovery and humanity in a world dominated by artificial intelligence.' },
  SIL: { name: 'Marty McFly', imageQuery: 'back-to-future-marty-mcfly-michael-j-fox', descriptionPt: 'Marty McFly é o protagonista da trilogia Back to the Future, interpretado por Michael J. Fox. Um adolescente californiano que viaja no tempo com a ajuda do excêntrico Dr. Emmett Brown.', descriptionEn: 'Marty McFly is the protagonist of the Back to the Future trilogy, played by Michael J. Fox. A California teenager who travels through time with the help of the eccentric Dr. Emmett Brown.' },
  SCA: { name: 'Sophie Hatter', imageQuery: "howl's-moving-castle-sophie-ghibli", descriptionPt: 'Sophie Hatter é a protagonista de Howl\'s Moving Castle, de Hayao Miyazaki. Uma jovem modista transformada em idosa por um feitiço, cuja jornada de autodescoberta impulsiona toda a narrativa.', descriptionEn: "Sophie Hatter is the protagonist of Hayao Miyazaki's Howl's Moving Castle. A young hat-maker transformed into an old woman by a curse, whose journey of self-discovery drives the entire narrative." },
  SCB: { name: 'Lestat de Lioncourt', imageQuery: 'interview-vampire-lestat-brad-pitt', descriptionPt: 'Lestat de Lioncourt é um personagem central de Entrevista com o Vampiro. Aristocrático e carismático, é um vampiro francês do século XVIII, conhecido por sua natureza rebelde.', descriptionEn: 'Lestat de Lioncourt is a central character in Interview with the Vampire. Aristocratic and charismatic, he is an 18th-century French vampire known for his rebellious nature.' },
  SCX: { name: 'Jef Costello', imageQuery: 'le-samourai-alain-delon', descriptionPt: 'Jef Costello é o personagem principal de Le Samouraï, interpretado por Alain Delon. Figura icônica do cinema noir francês, é um assassino de aluguel meticuloso cuja frieza reflete um código de conduta quase ritualístico.', descriptionEn: 'Jef Costello is the main character of Le Samouraï, played by Alain Delon. An iconic figure of French noir cinema, he is a meticulous contract killer whose coldness reflects an almost ritualistic code of conduct.' },
  SCK: { name: 'Vito Corleone', imageQuery: 'godfather-vito-corleone-marlon-brando', descriptionPt: 'Vito Corleone é o patriarca fictício da família Corleone em The Godfather. Símbolo do arquétipo do "padrinho", representa poder, tradição e a complexa moralidade das famílias mafiosas.', descriptionEn: 'Vito Corleone is the fictional patriarch of the Corleone family in The Godfather. A symbol of the "godfather" archetype, he represents power, tradition, and the complex morality of Mafia families.' },
  SCD: { name: 'Hannibal Lecter', imageQuery: 'silence-lambs-hannibal-lecter-anthony-hopkins', descriptionPt: 'Hannibal Lecter é o principal antagonista de The Silence of the Lambs. Um psiquiatra brilhante e assassino em série canibal, cuja inteligência refinada o tornou um dos vilões mais icônicos do cinema.', descriptionEn: 'Hannibal Lecter is the main antagonist of The Silence of the Lambs. A brilliant psychiatrist and cannibalistic serial killer whose refined intelligence made him one of the most iconic villains in cinema.' },
  SCL: { name: 'M. Gustave H.', imageQuery: 'grand-budapest-hotel-ralph-fiennes-gustave', descriptionPt: 'Monsieur Gustave H. é o gerente do Grand Budapest Hotel, em The Grand Budapest Hotel de Wes Anderson. Dedicado, elegante e excêntrico, sua figura simboliza a velha Europa de cortesia em declínio.', descriptionEn: 'Monsieur Gustave H. is the manager of the Grand Budapest Hotel in Wes Anderson\'s film. Dedicated, elegant, and eccentric, his figure symbolizes the old Europe of courtesy and refinement in decline.' },
  SRA: { name: 'Po', imageQuery: 'kung-fu-panda-po-dreamworks', descriptionPt: 'Po é o protagonista da franquia Kung Fu Panda, da DreamWorks. Um panda desajeitado e apaixonado por kung fu que se torna o lendário "Guerreiro Dragão".', descriptionEn: 'Po is the protagonist of DreamWorks\' Kung Fu Panda franchise. A clumsy panda passionate about kung fu who unexpectedly becomes the legendary "Dragon Warrior".' },
  SRB: { name: 'Eric Draven', imageQuery: 'the-crow-brandon-lee', descriptionPt: 'Eric Draven é o protagonista de The Crow, interpretado por Brandon Lee. Um músico assassinado que retorna dos mortos para vingar sua morte e a de sua noiva. Tornou-se um ícone gótico do cinema dos anos 1990.', descriptionEn: 'Eric Draven is the protagonist of The Crow, played by Brandon Lee. A musician murdered who returns from the dead to avenge his own death and that of his fiancée. He became a gothic icon of 1990s cinema.' },
  SRX: { name: 'Tyler Durden', imageQuery: 'fight-club-brad-pitt-tyler-durden', descriptionPt: 'Tyler Durden é o carismático alter ego do Narrador em Fight Club, de David Fincher, interpretado por Brad Pitt. Simboliza a libertação do consumismo e o colapso da identidade moderna.', descriptionEn: 'Tyler Durden is the charismatic alter ego of the Narrator in David Fincher\'s Fight Club, played by Brad Pitt. He symbolizes liberation from consumerism and the collapse of modern identity.' },
  SRK: { name: 'The Bride', imageQuery: 'kill-bill-uma-thurman-bride', descriptionPt: 'A Noiva (Beatrix Kiddo) é a protagonista de Kill Bill, de Quentin Tarantino, interpretada por Uma Thurman. Uma ex-assassina que busca vingança contra seu antigo mentor e amante, Bill.', descriptionEn: 'The Bride (Beatrix Kiddo) is the protagonist of Quentin Tarantino\'s Kill Bill, played by Uma Thurman. A former assassin seeking revenge against her former mentor and lover, Bill.' },
  SRD: { name: 'Maximus', imageQuery: 'gladiator-russell-crowe-maximus', descriptionPt: 'Maximus Decimus Meridius é o protagonista fictício de Gladiator, interpretado por Russell Crowe. Um general romano traído que busca vingança contra o imperador que assassinou sua família.', descriptionEn: 'Maximus Decimus Meridius is the fictional protagonist of Gladiator, played by Russell Crowe. A betrayed Roman general who seeks revenge against the emperor who murdered his family.' },
  SRL: { name: 'Jack Sparrow', imageQuery: 'pirates-caribbean-jack-sparrow-johnny-depp', descriptionPt: 'Capitão Jack Sparrow é o protagonista da franquia Pirates of the Caribbean, interpretado por Johnny Depp. Um pirata carismático e imprevisível que tornou-se um ícone da cultura pop.', descriptionEn: 'Captain Jack Sparrow is the protagonist of the Pirates of the Caribbean franchise, played by Johnny Depp. A charismatic and unpredictable pirate who became a pop culture icon.' },
};

const PEXELS_IMAGES: Record<string, string> = {
  // Pexels doesn't have specific character images; we use a cinematic/film aesthetic placeholder
};

interface Props {
  personalityId: string;
  language: string;
}

export default function CinematicPersonaCard({ personalityId, language }: Props) {
  const { t } = useTranslation();
  const [showModal, setShowModal] = useState(false);
  const [showEnglish, setShowEnglish] = useState(false);

  const persona = PERSONAS[personalityId];
  if (!persona) return null;

  const isEn = language.startsWith('en') || showEnglish;
  const description = isEn ? persona.descriptionEn : persona.descriptionPt;

  const accentColor = (() => {
    if (!personalityId || personalityId.length < 3) return '#3b82f6';
    const sub = personalityId.charAt(2);
    const map: Record<string, string> = { A: '#f59e0b', B: '#8b5cf6', K: '#ef4444', X: '#3b82f6', D: '#FFFFFF', L: '#10b981' };
    return map[sub] || '#3b82f6';
  })();

  return (
    <>
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5, delay: 0.25 }}
        className="mb-8"
      >
        <button
          onClick={() => setShowModal(true)}
          className="w-full text-left group relative rounded-3xl bg-white/40 dark:bg-gray-800/40 backdrop-blur-xl border border-white/60 dark:border-gray-700/60 shadow-2xl overflow-hidden p-6 hover:shadow-xl transition-all duration-300"
        >
          {/* Background glow */}
          <div
            className="absolute inset-0 opacity-0 group-hover:opacity-100 transition-opacity duration-300 rounded-3xl"
            style={{ background: `radial-gradient(ellipse at top right, ${accentColor}18, transparent 60%)` }}
          />
          <div className="absolute top-0 right-0 w-40 h-40 rounded-full blur-3xl opacity-20"
            style={{ background: accentColor }} />

          <div className="relative z-10 flex items-center gap-5">
            {/* Avatar placeholder */}
            <div
              className="flex-shrink-0 w-16 h-16 rounded-2xl flex items-center justify-center border-2 shadow-lg"
              style={{ borderColor: `${accentColor}60`, background: `${accentColor}20` }}
            >
              <User className="w-8 h-8" style={{ color: accentColor }} />
            </div>

            <div className="flex-1 min-w-0">
              <p className="text-xs font-semibold uppercase tracking-widest mb-0.5" style={{ color: accentColor }}>
                {isEn ? 'Your Persona' : 'Sua Persona'}
              </p>
              <h3 className="text-xl font-bold text-gray-900 dark:text-white truncate">
                {persona.name}
              </h3>
              <p className="text-sm text-gray-500 dark:text-gray-400 mt-1 line-clamp-2">
                {isEn ? persona.descriptionEn : persona.descriptionPt}
              </p>
            </div>

            <div
              className="flex-shrink-0 w-8 h-8 rounded-xl flex items-center justify-center opacity-60 group-hover:opacity-100 transition-opacity"
              style={{ background: `${accentColor}30` }}
            >
              <svg className="w-4 h-4" style={{ color: accentColor }} fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
              </svg>
            </div>
          </div>
        </button>
      </motion.div>

      <AnimatePresence>
        {showModal && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 bg-black/70 backdrop-blur-sm z-[9999] flex items-center justify-center p-4"
            onClick={() => setShowModal(false)}
          >
            <motion.div
              initial={{ scale: 0.9, opacity: 0, y: 20 }}
              animate={{ scale: 1, opacity: 1, y: 0 }}
              exit={{ scale: 0.9, opacity: 0, y: 20 }}
              transition={{ type: 'spring', stiffness: 300, damping: 25 }}
              onClick={e => e.stopPropagation()}
              className="relative w-full max-w-md rounded-3xl overflow-hidden shadow-2xl"
              style={{ background: 'rgba(10,10,20,0.92)', border: `1px solid ${accentColor}40` }}
            >
              {/* Top color band */}
              <div className="absolute top-0 inset-x-0 h-1" style={{ background: `linear-gradient(90deg, transparent, ${accentColor}, transparent)` }} />

              {/* Background glow */}
              <div className="absolute top-0 right-0 w-64 h-64 rounded-full blur-3xl opacity-10"
                style={{ background: accentColor }} />

              {/* Close button */}
              <button
                onClick={() => setShowModal(false)}
                className="absolute top-4 right-4 z-10 p-2 rounded-xl bg-white/10 hover:bg-white/20 transition-colors"
              >
                <X className="w-5 h-5 text-white" />
              </button>

              <div className="relative z-10 p-7">
                {/* Avatar */}
                <div className="flex justify-center mb-5">
                  <div
                    className="w-28 h-28 rounded-2xl flex items-center justify-center border-2 shadow-xl"
                    style={{ borderColor: `${accentColor}80`, background: `${accentColor}25` }}
                  >
                    <User className="w-14 h-14" style={{ color: accentColor }} />
                  </div>
                </div>

                {/* Essence badge */}
                <div className="flex justify-center mb-2">
                  <span
                    className="text-xs font-bold uppercase tracking-widest px-3 py-1 rounded-full"
                    style={{ background: `${accentColor}25`, color: accentColor, border: `1px solid ${accentColor}50` }}
                  >
                    {personalityId}
                  </span>
                </div>

                {/* Name */}
                <h2 className="text-2xl font-extrabold text-white text-center mb-4">
                  {persona.name}
                </h2>

                {/* Description */}
                <p className="text-gray-300 text-sm leading-relaxed text-center mb-6">
                  {description}
                </p>

              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </>
  );
}
