import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, User } from 'lucide-react';
import { useTranslation } from 'react-i18next';

interface Persona {
  name: string;
  descriptionPt: string;
  descriptionEn: string;
  imageQuery: string;
  imageUrl?: string;
}

const PERSONAS: Record<string, Persona> = {
  EIA: { name: 'Cooper', imageQuery: 'cooper', imageUrl: 'https://miro.medium.com/v2/resize:fit:1400/1*AgdvNkcX-5Rpjd4IE9dBLQ.jpeg', descriptionPt: 'Cooper é o protagonista do filme de ficção científica Interstellar, dirigido por Christopher Nolan. Interpretado por Matthew McConaughey, ele é um ex-piloto e engenheiro da NASA que se torna a última esperança da humanidade em uma missão interestelar para salvar a Terra da extinção ecológica.', descriptionEn: 'Cooper is the protagonist of the science fiction film Interstellar, directed by Christopher Nolan. Played by Matthew McConaughey, he is a former NASA pilot and engineer who becomes humanity\'s last hope on an interstellar mission to save Earth from ecological extinction.' },
  EIB: { name: 'Donald Kaufman', imageQuery: 'donald-kaufman', imageUrl: 'https://m.media-amazon.com/images/M/MV5BNjhkZmQ2MmUtMGM1OS00ZTFlLWFhMTQtNDM5Mzk1Y2E0YjljXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_QL75_UX500_CR0,47,500,281_.jpg', descriptionPt: 'Donald Kaufman é um personagem fictício do filme Adaptation, dirigido por Spike Jonze e escrito por Charlie Kaufman. Interpretado por Nicolas Cage, ele é o irmão gêmeo imaginário do roteirista Charlie Kaufman dentro da narrativa, funcionando como contraponto cômico e emocional.', descriptionEn: 'Donald Kaufman is a fictional character in the film Adaptation, directed by Spike Jonze and written by Charlie Kaufman. Portrayed by Nicolas Cage, he is the imaginary twin brother of screenwriter Charlie Kaufman within the narrative, serving as a comedic and emotional counterpoint.' },
  EIX: { name: 'Joel Barish', imageQuery: 'eternal-sunshine-joel', imageUrl: 'https://m.media-amazon.com/images/M/MV5BMTg0MjgxMzA1OF5BMl5BanBnXkFtZTcwMjU5ODMyMw@@._V1_QL75_UX411_.jpg', descriptionPt: 'Joel Barish é o protagonista do filme Eternal Sunshine of the Spotless Mind, dirigido por Michel Gondry e escrito por Charlie Kaufman. Interpretado por Jim Carrey, Joel é um homem introspectivo que busca apagar as memórias de um relacionamento fracassado, tornando-se o centro emocional de uma história sobre amor, perda e identidade.', descriptionEn: 'Joel Barish is the protagonist of Eternal Sunshine of the Spotless Mind, directed by Michel Gondry and written by Charlie Kaufman. Played by Jim Carrey, Joel is an introspective man who seeks to erase memories of a failed relationship, becoming the emotional center of a story about love, loss, and identity.' },
  EIK: { name: 'Atticus Finch', imageQuery: 'atticus-finch', imageUrl: 'https://hqscomcafe.com.br/wp-content/uploads/2020/04/atticus-finch.jpg', descriptionPt: 'Atticus Finch é um personagem fictício do romance To Kill a Mockingbird (1960), de Harper Lee, e do filme homônimo de 1962. Advogado e pai viúvo de Scout e Jem Finch, ele simboliza integridade moral e justiça em meio ao racismo do sul dos Estados Unidos na década de 1930.', descriptionEn: 'Atticus Finch is a fictional character from Harper Lee\'s 1960 novel and its 1962 film adaptation. A lawyer and widowed father, he symbolizes moral integrity and justice amid the racism of the 1930s American South.' },
  EID: { name: 'Rust Cohle', imageQuery: 'true-detective-rust-cohle', imageUrl: 'https://i.guim.co.uk/img/static/sys-images/Guardian/Pix/pictures/2014/4/10/1397150221534/Ruse-Cohle----hes-here-to-011.jpg?width=465&dpr=1&s=none&crop=none', descriptionPt: 'Rustin Spencer "Rust" Cohle é o protagonista da primeira temporada da série True Detective (2014), criada por Nic Pizzolatto. Interpretado por Matthew McConaughey, Cohle é um detetive brilhante, profundamente atormentado e marcado por visões filosóficas e existenciais sobre a natureza da vida e do mal.', descriptionEn: 'Rust Cohle is the protagonist of the first season of True Detective (2014). Played by Matthew McConaughey, Cohle is a brilliant, deeply tormented detective shaped by philosophical and existential views on the nature of life and evil.' },
  EIL: { name: 'Forrest Gump', imageQuery: 'forrest-gump', imageUrl: 'https://upload.wikimedia.org/wikipedia/pt/thumb/9/97/Forest_Gump_Personagem.jpg/250px-Forest_Gump_Personagem.jpg', descriptionPt: 'Forrest Gump é o protagonista homônimo do romance de 1986 de Winston Groom e de sua premiada adaptação cinematográfica de 1994 dirigida por Robert Zemeckis. Retratado por Tom Hanks, o personagem é um homem de coração puro e intelecto limitado que, de forma inocente, participa de momentos decisivos da história dos Estados Unidos no século XX.', descriptionEn: 'Forrest Gump is the eponymous protagonist of Winston Grooms 1986 novel and its award-winning 1994 film adaptation directed by Robert Zemeckis. Portrayed by Tom Hanks, the character is a pure-hearted but intellectually challenged man who innocently participates in pivotal moments in 20th-century American history.' },
  ECA: { name: 'Salvatore Di Vita', imageQuery: 'cinema-paradiso-salvatore', imageUrl: 'https://m.media-amazon.com/images/M/MV5BODQ3Mzg2OTgyMF5BMl5BanBnXkFtZTcwNDg2NzIwNw@@._V1_QL75_UX388_.jpg', descriptionPt: 'Salvatore Di Vita é o protagonista do filme italiano Nuovo Cinema Paradiso, dirigido por Giuseppe Tornatore. Sua história retrata o crescimento de um menino apaixonado por cinema em uma pequena cidade siciliana e sua trajetória até se tornar um renomado cineasta, refletindo sobre memória, amizade e perda.', descriptionEn: 'Salvatore Di Vita is the protagonist of the Italian film Cinema Paradiso, directed by Giuseppe Tornatore. His story depicts a boy\'s love for cinema in a small Sicilian town and his journey to becoming a renowned filmmaker, reflecting on memory, friendship, and loss.' },
  ECB: { name: 'Michael Corleone', imageQuery: 'godfather-michael-corleone-al-pacino', imageUrl: 'https://static.wikia.nocookie.net/godfather/images/a/aa/Michael_Corleone_Part_I.jpg/revision/latest?cb=20190828200514', descriptionPt: 'Michael Corleone é o protagonista fictício da saga cinematográfica The Godfather, criada por Mario Puzo e dirigida por Francis Ford Coppola. Interpretado por Al Pacino, ele é o terceiro filho de Vito Corleone e se torna o chefe da família após uma trajetória marcada por lealdade, violência e tragédia.', descriptionEn: 'Michael Corleone is the fictional protagonist of The Godfather film saga, created by Mario Puzo and directed by Francis Ford Coppola. Played by Al Pacino, he is the third son of Vito Corleone who becomes the family patriarch after a path marked by loyalty, violence, and tragedy.' },
  ECX: { name: 'Harold Chasen', imageQuery: 'harold-maude', imageUrl: 'https://a1cf74336522e87f135f-2f21ace9a6cf0052456644b80fa06d4f.ssl.cf2.rackcdn.com/images/characters/large/800/Harold-Chasen.Harold-and-Maude.webp', descriptionPt: 'Harold Chasen é o protagonista do filme de humor negro Harold and Maude, dirigido por Hal Ashby. Interpretado por Bud Cort, Harold é um jovem de classe alta obcecado pela morte que encontra um sentido inusitado para a vida ao se apaixonar por uma mulher septuagenária, Maude.', descriptionEn: 'Harold Chasen is the protagonist of the dark comedy film Harold and Maude, directed by Hal Ashby. Played by Bud Cort, Harold is a young man from an upper-class family obsessed with death who finds an unusual meaning to life when he falls in love with a septuagenarian woman, Maude.' },
  ECK: { name: 'Scarlett O\'Hara', imageQuery: 'scarlett-o-hara', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/d7/Vivien_Leigh_Gone_Wind_Restored.jpg', descriptionPt: 'Scarlett O\'Hara é a protagonista fictícia de Gone with the Wind (...E o Vento Levou, 1939) e do romance homônimo de Gone with the Wind de Margaret Mitchell. Ícone da cultura popular americana, ela simboliza tanto o glamour quanto a complexidade moral do Velho Sul durante e após a Guerra Civil dos Estados Unidos.', descriptionEn: 'Scarlett O\'Hara is the fictional protagonist of Gone with the Wind (1939) and the eponymous novel by Margaret Mitchell. An icon of American popular culture, she symbolizes both the glamour and the moral complexity of the Old South during and after the American Civil War.' },
  ECD: { name: 'Guido Orefice', imageQuery: 'life-is-beautiful-roberto-benigni', imageUrl: 'https://m.media-amazon.com/images/M/MV5BYjgxZDdjYmYtODg1Yy00ZWEyLTg0OTktYWJkYmVmNjFjODEzXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg', descriptionPt: 'Guido Orefice é o protagonista do filme La vita è bella ("A Vida é Bela"), interpretado por Roberto Benigni, que também dirigiu e coescreveu a obra. O personagem é um livreiro judeu na Itália fascista cuja imaginação e otimismo sustentam a família em meio aos horrores do Holocausto..', descriptionEn: 'Guido Orefice is the protagonist of Life Is Beautiful, played by Roberto Benigni who also directed and co-wrote the film. He is a Jewish bookseller in fascist Italy whose imagination and optimism sustain his family amid the horrors of the Holocaust.' },
  ECL: { name: 'Mia Thermopolis', imageQuery: 'mia-thermopolis', imageUrl: 'https://www.theodysseyonline.com/media-library/image.png?id=55940506&width=1200&height=1200&coordinates=193%2C0%2C194%2C0', descriptionPt: 'Mia Thermopolis é a protagonista fictícia da série de filmes O Diário da Princesa (The Princess Diaries), baseada nos romances de The Princess Diaries de Meg Cabot. Interpretada por Anne Hathaway, ela é uma adolescente comum que descobre ser herdeira do trono de um pequeno principado europeu chamado Genovia. Sua história tornou-se um ícone de transformação pessoal e empoderamento juvenil.', descriptionEn: 'Mia Thermopolis is the fictional protagonist of The Princess Diaries film series, based on the Princess Diaries novels by Meg Cabot. Portrayed by Anne Hathaway, she is an ordinary teenager who discovers she is the heir to the throne of a small European principality called Genovia. Her story has become an icon of personal transformation and youth empowerment.' },
  ERA: { name: 'Ted Lasso', imageQuery: 'ted-lasso-jason-sudeikis', imageUrl: 'https://media.gazetadopovo.com.br/2023/04/12151328/ted-lasso-12abr2023-apple-tv-divulga%C3%A7%C3%A3o-960x540.jpg', descriptionPt: 'Ted Lasso é o personagem fictício principal da série de comédia "Ted Lasso", interpretado por Jason Sudeikis. Ele é um treinador de futebol americano contratado inesperadamente para comandar um time de futebol inglês, apesar de sua falta de experiência no esporte. O personagem tornou-se símbolo de otimismo, empatia e liderança positiva.', descriptionEn: 'Ted Lasso is the main character of the comedy series Ted Lasso, played by Jason Sudeikis. He is an American football coach unexpectedly hired to manage an English soccer team despite his lack of experience in the sport, becoming a symbol of optimism, empathy, and positive leadership.' },
  ERB: { name: 'Anakin Skywalker', imageQuery: 'star-wars-anakin-skywalker', imageUrl: 'https://saberspro.com/cdn/shop/articles/2cde43c2-0f15-4b32-a486-89564965c73b_backup.webp?v=1774966035&width=2048', descriptionPt: 'Anakin Skywalker é um personagem fictício da franquia Star Wars, criado por George Lucas. Originalmente um escravo em Tatooine com grande sensibilidade à Força, tornou-se Cavaleiro Jedi e mais tarde o Sith Lord Darth Vader. Sua jornada trágica, da promessa à queda e à redenção, é um dos arcos narrativos mais icônicos do cinema.', descriptionEn: 'Anakin Skywalker is a fictional character in the Star Wars franchise, created by George Lucas. Originally a slave on Tatooine with exceptional Force sensitivity, he became a Jedi Knight and later the Sith Lord Darth Vader. His tragic journey from promise to fall to redemption is one of cinema\'s most iconic narrative arcs.' },
  ERX: { name: 'Truman Burbank', imageQuery: 'truman-show', imageUrl: 'https://m.media-amazon.com/images/M/MV5BMTM5OTUzMTAwNF5BMl5BanBnXkFtZTcwNzM0ODcxNA@@._V1_.jpg', descriptionPt: 'Truman Burbank é o protagonista fictício do filme The Truman Show, interpretado por Jim Carrey. Ele é um homem comum que, sem saber, vive toda a sua vida dentro de um reality show transmitido para o mundo, ambientado em uma cidade cenográfica chamada Seahaven.', descriptionEn: 'Truman Burbank is the fictional protagonist of the film The Truman Show, played by Jim Carrey. He is an ordinary man who unknowingly lives his entire life inside a reality show broadcast to the world, set in a fictional town called Seahaven.' },
  ERK: { name: 'Elliott', imageQuery: 'elliott-et', imageUrl: 'https://upload.wikimedia.org/wikipedia/en/c/c8/Elliott_from_ET.jpg', descriptionPt: 'Elliott é o protagonista humano do filme E.T. the Extra-Terrestrial, dirigido por Steven Spielberg. Ele é um garoto solitário de dez anos que desenvolve uma amizade profunda com um extraterrestre perdido na Terra, chamado E.T. A relação entre os dois simboliza empatia, inocência e o poder da conexão além das diferenças.', descriptionEn: 'Elliott is the human protagonist of the film E.T. the Extra-Terrestrial, directed by Steven Spielberg. He is a lonely ten-year-old boy who develops a deep friendship with an extraterrestrial lost on Earth, named E.T. The relationship between the two symbolizes empathy, innocence, and the power of connection beyond differences.' },
  ERD: { name: 'Frankie Dunn', imageQuery: 'frankie-dunn', imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0lwy_SQ_TMj0gtm2v85N2HUX47Xp79DHU9w&s', descriptionPt: 'Frankie Dunn é o personagem principal do filme Million Dollar Baby (2004), dirigido e estrelado por Clint Eastwood. Treinador de boxe veterano e dono de uma academia modesta, Frankie é retratado como um homem reservado e atormentado por arrependimentos, que encontra redenção ao treinar uma jovem boxeadora talentosa.', descriptionEn: 'Frankie Dunn is the main character in the film Million Dollar Baby (2004), directed by and starring Clint Eastwood. A veteran boxing trainer and owner of a modest gym, Frankie is portrayed as a reserved man tormented by regrets, who finds redemption by training a talented young female boxer.' },
  ERL: { name: 'Bridget Jones', imageQuery: 'bridget-jones', imageUrl: 'https://ichef.bbci.co.uk/ace/ws/640/cpsprodpb/8307/live/58813b10-eeaa-11ef-bd1b-d536627785f2.jpg.webp', descriptionPt: 'Bridget Jones é a protagonista fictícia da comédia romântica Bridget Jones\'s Diary e de suas continuações, baseada nos romances de Bridget Jones\'s Diary escritos por Helen Fielding. Interpretada por Renée Zellweger, ela se tornou um ícone da cultura pop britânica moderna por retratar com humor as inseguranças e dilemas de uma mulher solteira nos trinta e poucos anos.', descriptionEn: 'Bridget Jones is the fictional protagonist of the romantic comedy Bridget Jones\'s Diary and its sequels, based on the Bridget Jones\'s Diary novels written by Helen Fielding. Portrayed by Renée Zellweger, she has become an icon of modern British pop culture for humorously portraying the insecurities and dilemmas of a single woman in her thirties.' },
  ESA: { name: 'Mia Dolan', imageQuery: 'la-la-land-emma-stone-mia', imageUrl: 'https://static.wikia.nocookie.net/lalaland/images/e/eb/Mia_1.jpeg/revision/latest?cb=20210104034425', descriptionPt: 'Mia Dolan é a personagem principal do filme musical La La Land, interpretada por Emma Stone. Aspirante a atriz em Los Angeles, Mia simboliza o conflito entre paixão artística e realidade prática.', descriptionEn: 'Mia Dolan is the main character of the musical film La La Land, played by Emma Stone. An aspiring actress in Los Angeles, Mia symbolizes the conflict between artistic passion and practical reality.' },
  ESB: { name: 'Nina Sayers', imageQuery: 'nina-sayers', imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwFI5UlRDKqpjCvpxGOHXNEw227rF9f5UbMQ&s', descriptionPt: 'Nina Sayers é a protagonista do filme psicológico Black Swan, dirigido por Darren Aronofsky. Interpretada por Natalie Portman, ela é uma bailarina nova-iorquina obcecada pela perfeição que mergulha em um colapso psicológico ao buscar encarnar as dualidades do “Cisne Branco” e do “Cisne Negro” em uma produção de O Lago dos Cisnes.', descriptionEn: 'Nina Sayers is the protagonist of the psychological film Black Swan, directed by Darren Aronofsky. Played by Natalie Portman, she is a New York ballerina obsessed with perfection who plunges into a psychological breakdown while trying to embody the dualities of the "White Swan" and the "Black Swan" in a production of Swan Lake.' },
  ESX: { name: 'Elisa Esposito', imageQuery: 'elisa-esposito', imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1qo19DU7kXm7C-AThphRq76zbcOJ9JlwBpQ&s', descriptionPt: 'Elisa Esposito é a protagonista do filme The Shape of Water, dirigido por Guillermo del Toro. É uma mulher muda que trabalha como faxineira em um laboratório governamental nos Estados Unidos durante a Guerra Fria. Sua história centraliza-se em seu relacionamento com uma criatura anfíbia mantida em cativeiro, explorando temas de empatia, alteridade e amor fora dos padrões.', descriptionEn: 'Elisa Esposito is the protagonist of the film The Shape of Water, directed by Guillermo del Toro. She is a mute woman who works as a cleaner in a government laboratory in the United States during the Cold War. Her story centers on her relationship with an amphibious creature kept in captivity, exploring themes of empathy, otherness, and unconventional love.' },
  ESK: { name: 'Edward Scissorhands', imageQuery: 'edward-scissorhands', imageUrl: 'https://static.wikia.nocookie.net/p__/images/6/61/JD_as_Acissorhamds.jpeg/revision/latest/thumbnail/width/360/height/360?cb=20160323144628&path-prefix=protagonist', descriptionPt: 'Edward Scissorhands é um personagem fictício e o protagonista do filme homônimo de 1990 dirigido por Tim Burton. Interpretado por Johnny Depp, Edward é um andróide inacabado com lâminas de tesoura no lugar das mãos, cuja aparência gótica e natureza inocente o tornam um dos ícones mais reconhecíveis do cinema contemporâneo.', descriptionEn: 'Edward Scissorhands is a fictional character and the protagonist of the 1990 film of the same name directed by Tim Burton. Played by Johnny Depp, Edward is an unfinished android with scissor blades in place of hands, whose gothic appearance and innocent nature make him one of the most recognizable icons of contemporary cinema.' },
  ESD: { name: 'Joker', imageQuery: 'joker-2019-joaquin-phoenix', imageUrl: 'https://www.magazine-hd.com/apps/wp/wp-content/uploads/2019/04/joker.jpg', descriptionPt: 'O Coringa (Joker, 2019) é interpretado por Joaquin Phoenix. A obra apresenta uma origem alternativa e realista para o famoso vilão da DC Comics, explorando temas de isolamento social, doença mental e desigualdade urbana.', descriptionEn: 'The Joker (2019), played by Joaquin Phoenix, presents an alternative and realistic origin for the famous DC Comics villain, exploring themes of social isolation, mental illness, and urban inequality.' },
  ESL: { name: 'Amélie Poulain', imageQuery: 'amelie-poulain', imageUrl: 'https://ammepapier.com.br/cdn/shop/articles/5699b52a1c9aaf91afca6eb42d717216.jpg?v=1687550261', descriptionPt: 'Amélie Poulain é a personagem principal do filme francês Le Fabuleux Destin d\'Amélie Poulain, dirigido por Jean-Pierre Jeunet. Interpretada por Audrey Tautou, Amélie tornou-se um ícone da cultura pop por seu olhar poético e imaginativo sobre a vida cotidiana em Paris.', descriptionEn: 'Amélie Poulain is the main character in the French film Le Fabuleux Destin d\'Amélie Poulain, directed by Jean-Pierre Jeunet. Played by Audrey Tautou, Amélie became a pop culture icon for her poetic and imaginative look at everyday life in Paris.' },
  IEA: { name: 'Professor X', imageQuery: 'professor-x', imageUrl: 'https://rollingstone.com.br/wp-content/uploads/patrick-stewart_como_professor_xavier_em_xmen_foto_reproducao_fox.jpg', descriptionPt: 'Professor X é um personagem fictício do universo X-Men, criado pela Marvel Comics e adaptado para o cinema como líder dos mutantes. Também conhecido como Charles Xavier, ele é um poderoso telepata e fundador da Escola Xavier para Jovens Superdotados. É central na narrativa dos X-Men, simbolizando tolerância, igualdade e coexistência pacífica entre humanos e mutantes.', descriptionEn: 'Professor X is a fictional character from the X-Men universe, created by Marvel Comics and adapted for film as the leader of the mutants. Also known as Charles Xavier, he is a powerful telepath and founder of Xavier\'s School for Gifted Youngsters. He is central to the X-Men narrative, symbolizing tolerance, equality, and peaceful coexistence between humans and mutants.' },
  IEB: { name: 'Severus Snape', imageQuery: 'severus-snape', imageUrl: 'https://images.shoutwiki.com/harrypotter/a/a3/Severus_Snape.jpg', descriptionPt: 'Severus Snape é um personagem fictício da série de filmes Harry Potter, baseada nos livros de Harry Potter. Ele é o professor de Poções e, mais tarde, diretor da Escola de Magia e Bruxaria de Hogwarts. Complexo e ambíguo, Snape é central na tensão moral da narrativa, oscilando entre vilania e heroísmo.', descriptionEn: 'Severus Snape is a fictional character from the Harry Potter film series, based on the Harry Potter books. He is the Potions professor and later headmaster of Hogwarts School of Witchcraft and Wizardry. Complex and ambiguous, Snape is central to the moral tension of the narrative, oscillating between villainy and heroism.' },
  IEX: { name: 'Dom Cobb', imageQuery: 'inception-dom-cobb-leonardo-dicaprio', imageUrl: 'https://static.wikia.nocookie.net/inception/images/2/2b/Dom_cobb.jpg/revision/latest?cb=20150125061140', descriptionPt: 'Dom Cobb é o protagonista do filme Inception, interpretado por Leonardo DiCaprio. Cobb é um ladrão especializado em "extração" — o roubo de segredos do inconsciente durante o sonho. O personagem é o centro emocional e filosófico da história, marcada por temas de culpa, memória e realidade.', descriptionEn: 'Dom Cobb is the protagonist of Inception, played by Leonardo DiCaprio. He is a thief specializing in "extraction" — stealing secrets from the subconscious during dreams. The character is the emotional and philosophical center of the story, marked by themes of guilt, memory, and reality.' },
  IEK: { name: 'Clarice Starling', imageQuery: 'clarice-starling', imageUrl: 'https://upload.wikimedia.org/wikipedia/en/b/b4/SOTLClariceLecter.jpg', descriptionPt: 'Clarice Starling é a protagonista fictícia do filme The Silence of the Lambs e da série de livros de Thomas Harris. Jovem agente do FBI, ela se torna conhecida por sua inteligência, empatia e determinação ao investigar assassinos em série, especialmente na icônica interação com o canibal erudito Hannibal Lecter.', descriptionEn: 'Clarice Starling is the fictional protagonist of the film The Silence of the Lambs and the book series by Thomas Harris. A young FBI agent, she becomes known for her intelligence, empathy, and determination while investigating serial killers, especially in her iconic interaction with the erudite cannibal Hannibal Lecter.' },
  IED: { name: 'Anton Ego', imageQuery: 'anton-ego', imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0AC8laFkxqqcyaD4v_xnT240kRNV9xA4y2Q&s', descriptionPt: 'Anton Ego é um personagem fictício do filme de animação Ratatouille (2007), produzido pela Pixar Animation Studios e lançado pela Walt Disney Pictures. Ele é o temido crítico gastronômico de Paris, cuja opinião pode fazer ou destruir restaurantes. Sua transformação emocional no final simboliza a redescoberta da paixão e da humildade diante da verdadeira arte culinária.', descriptionEn: 'Anton Ego is a fictional character from the animated film Ratatouille (2007), produced by Pixar Animation Studios and released by Walt Disney Pictures. He is the feared Parisian food critic whose opinion can make or break restaurants. His emotional transformation at the end symbolizes the rediscovery of passion and humility in the face of true culinary art.' },
  IEL: { name: 'Hiro Hamada', imageQuery: 'hiro-6', imageUrl: 'https://static.wikia.nocookie.net/disney/images/2/21/Profile_-_Hiro_Hamada.jpeg/revision/latest/scale-to-width-down/1200?cb=20251202024306', descriptionPt: 'Hiro Hamada é o protagonista do filme de animação Big Hero 6 (2014), produzido pela Walt Disney Animation Studios e inspirado em personagens da Marvel Comics. Ele é um jovem prodígio da robótica que se torna herói ao lado de seu robô Baymax e de seus amigos cientistas.', descriptionEn: 'Hiro Hamada is the protagonist of the animated film Big Hero 6 (2014), produced by Walt Disney Animation Studios and inspired by Marvel Comics characters. He is a young robotics prodigy who becomes a hero alongside his robot Baymax and his scientist friends.' },
  ICA: { name: 'Prof. Keating', imageQuery: 'dead-poets-society-robin-williams', imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1Gc7ISASzWY3bDIf4qcmBXXxdWyZz6T5p9g&s', descriptionPt: 'Professor John Keating é um personagem fictício do filme Dead Poets Society, interpretado por Robin Williams. Ele é um professor de literatura inglesa que inspira seus alunos a pensar de forma independente e a "aproveitar o dia" ("carpe diem").', descriptionEn: 'Professor John Keating is a fictional character in Dead Poets Society, played by Robin Williams. He is an English literature teacher who inspires his students to think independently and to "seize the day" (carpe diem).' },
  ICB: { name: 'V', imageQuery: 'v-vendetta', imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJ7jUDd5fdrVDAMUUrqFbgfpG_ts5nZC11LQ&s', descriptionPt: 'V é o protagonista mascarado do filme V for Vendetta e da graphic novel homônima de Alan Moore e David Lloyd. O personagem é um vigilante anarquista que combate um regime totalitário na Inglaterra pós-guerra, usando a máscara de Guy Fawkes como símbolo de resistência e anonimato.', descriptionEn: 'V is the masked protagonist of the film V for Vendetta and the graphic novel of the same name by Alan Moore and David Lloyd. The character is an anarchist vigilante who fights a totalitarian regime in post-war England, using the Guy Fawkes mask as a symbol of resistance and anonymity.' },
  ICX: { name: 'Theodore Twombly', imageQuery: 'her-2013-joaquin-phoenix', imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfWv6Lraos3eE1egkP7s87PudGedjYDrQYVQ&s', descriptionPt: 'Theodore Twombly é o protagonista do filme Her, interpretado por Joaquin Phoenix. Theodore é um homem solitário que desenvolve uma relação emocional com um sistema operacional inteligente chamado Samantha.', descriptionEn: 'Theodore Twombly is the protagonist of Her, played by Joaquin Phoenix. He is a lonely man who develops an emotional relationship with an intelligent operating system named Samantha.' },
  ICK: { name: 'Spock', imageQuery: 'star-trek-spock', imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQz3LUvmcYRb7dUvrszj_uPX0hQWovXGa-KuA&s', descriptionPt: 'Spock é um personagem fictício da franquia Star Trek, conhecido por sua lógica impecável e herança mista humana e vulcana. Tornou-se um dos ícones mais duradouros da cultura pop e símbolo do equilíbrio entre razão e emoção.', descriptionEn: 'Spock is a fictional character in the Star Trek franchise, known for his impeccable logic and mixed human-Vulcan heritage. He became one of the most enduring pop culture icons and a symbol of the balance between reason and emotion.' },
  ICD: { name: 'Adrian Veidt', imageQuery: 'watchmen-adrian', imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmT3Ph-kdrP2oet8XVAEXKpNgZKC2nY-W4UA&s', descriptionPt: 'Adrian Veidt, também conhecido como Ozymandias, é um personagem fictício do universo de Watchmen. Criado por Alan Moore e Dave Gibbons, ele aparece originalmente na graphic novel de 1986 e em suas adaptações cinematográficas e televisivas. Veidt é retratado como o homem mais inteligente do mundo e um dos vigilantes mais influentes de sua era.', descriptionEn: 'Adrian Veidt, also known as Ozymandias, is a fictional character from the Watchmen universe. Created by Alan Moore and Dave Gibbons, he originally appears in the 1986 graphic novel and its film and television adaptations. Veidt is portrayed as the smartest man in the world and one of the most influential vigilantes of his era.' },
  ICL: { name: 'Hermione Granger', imageQuery: 'harry-potter-hermione', imageUrl: 'https://static.wikia.nocookie.net/harrypotter/images/5/56/Hermione-granger-deathly-hallows-part-1-portrait-1.jpg/revision/latest/thumbnail/width/360/height/450?cb=20220621185536&path-prefix=pt-br', descriptionPt: 'Hermione Granger é uma personagem fictícia da série de filmes Harry Potter, baseada nos romances de Harry Potter. Uma das protagonistas centrais, ela é conhecida por sua inteligência, ética e lealdade. Interpretada por Emma Watson, Hermione tornou-se um ícone cultural de coragem e erudição juvenil.', descriptionEn: 'Hermione Granger is a fictional character from the Harry Potter film series, based on the Harry Potter novels. One of the central protagonists, she is known for her intelligence, ethics, and loyalty. Portrayed by Emma Watson, Hermione has become a cultural icon of youthful courage and scholarship.' },
  IRA: { name: 'Doc Brown', imageQuery: 'back-to-future-doc-brown-christopher-lloyd', imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQIQMovPtrt-3Qwekm20JCh6pO_mkPGkZUYDQ&s', descriptionPt: 'Doc Brown (Dr. Emmett Brown) é um personagem fictício da franquia de filmes Back to the Future, criado por Robert Zemeckis e Bob Gale. Interpretado por Christopher Lloyd, ele é o excêntrico cientista responsável por inventar a máquina do tempo em um DeLorean. Tornou-se um dos personagens mais icônicos da cultura pop dos anos 1980.', descriptionEn: 'Doc Brown (Dr. Emmett Brown) is a fictional character from the Back to the Future film franchise, created by Robert Zemeckis and Bob Gale. Portrayed by Christopher Lloyd, he is the eccentric scientist responsible for inventing the time machine in a DeLorean. He became one of the most iconic characters in 1980s pop culture.' },
  IRB: { name: 'Edward Nashton', imageQuery: 'edward-nashton', imageUrl: 'https://static.wikia.nocookie.net/batman/images/3/38/Edward_Nashton_-_The_Batman.jpg/revision/latest?cb=20230119023052', descriptionPt: 'Edward Nashton, também conhecido como Charada (The Riddler), é o principal antagonista do filme The Batman, dirigido por Matt Reeves. Interpretado por Paul Dano, ele é uma reinterpretação sombria e realista do clássico vilão da DC Comics, retratado como um assassino em série que expõe a corrupção de Gotham City por meio de enigmas e crimes ritualísticos.', descriptionEn: 'Edward Nashton, also known as The Riddler, is the main antagonist in the film The Batman, directed by Matt Reeves. Played by Paul Dano, he is a dark and realistic reinterpretation of the classic DC Comics villain, portrayed as a serial killer who exposes the corruption of Gotham City through riddles and ritualistic crimes.' },
  IRX: { name: 'Rick Sanchez', imageQuery: 'rick-sanchez', imageUrl: 'https://static.wikia.nocookie.net/rickandmorty/images/a/a6/Rick_Sanchez.png/revision/latest?cb=20250817060829', descriptionPt: 'Rick Sanchez é um personagem fictício da série animada Rick and Morty, criada por Justin Roiland e Dan Harmon. Ele é um cientista genial, cínico e alcoólatra, conhecido por suas aventuras interdimensionais ao lado do neto Morty Smith. O personagem tornou-se um ícone da cultura pop moderna, representando tanto o brilhantismo quanto o niilismo extremos.', descriptionEn: 'Rick Sanchez is a fictional character from the animated series Rick and Morty, created by Justin Roiland and Dan Harmon. He is a brilliant, cynical, and alcoholic scientist, known for his interdimensional adventures alongside his grandson Morty Smith. The character has become a modern pop culture icon, representing both extreme brilliance and nihilism.' },
  IRK: { name: 'Hercule Poirot', imageQuery: 'hercule-poirot-agatha-christie', imageUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/5/56/DavidSuchet_-_Poirot.png/250px-DavidSuchet_-_Poirot.png', descriptionPt: 'Hercule Poirot é um detetive fictício criado por Agatha Christie. De origem belga, é um dos personagens mais icônicos da literatura policial, conhecido por seu intelecto meticuloso e obsessão pela ordem e pelos "pequenos detalhes".', descriptionEn: 'Hercule Poirot is a fictional detective created by Agatha Christie. Of Belgian origin, he is one of the most iconic characters in crime literature, known for his meticulous intellect and obsession with order and "the little grey cells".' },
  IRD: { name: 'Michael Scofield', imageQuery: 'prison-break-michael-scofield', imageUrl: 'https://static.wikia.nocookie.net/prisonbreak-files/images/b/b5/Micheal_Scofield.webp/revision/latest/scale-to-width-down/275?cb=20250517182145', descriptionPt: 'Michael Scofield é o protagonista fictício da série Prison Break, interpretado por Wentworth Miller. Ele é um engenheiro estrutural brilhante que se infiltra deliberadamente em uma prisão para resgatar seu irmão condenado injustamente.', descriptionEn: 'Michael Scofield is the fictional protagonist of Prison Break, played by Wentworth Miller. He is a brilliant structural engineer who deliberately infiltrates a prison to rescue his unjustly condemned brother.' },
  IRL: { name: 'Kevin McCallister', imageQuery: "home-alone", imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQsicYfqUI-cpE0nPSY3Q1ECgiMRFDsieV-3w&s', descriptionPt: 'Kevin McCallister é o protagonista fictício da franquia de filmes Home Alone (em português, Esqueceram de Mim). Interpretado por Macaulay Culkin, Kevin é um garoto de oito anos que, acidentalmente deixado sozinho em casa, precisa defender sua residência de ladrões trapalhões. O personagem tornou-se um ícone da cultura pop dos anos 1990.', descriptionEn: 'Kevin McCallister is the fictional protagonist of the Home Alone film franchise. Played by Macaulay Culkin, Kevin is an eight-year-old boy who, accidentally left home alone, must defend his residence from bumbling burglars. The character became a pop culture icon of the 1990s.' },
  ISA: { name: 'Tony Stark', imageQuery: 'tony-stark', imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSWGy4tNeDt5WZXdT42HtwwiVj8G2Ot73_Yrg&s', descriptionPt: 'Tony Stark é um personagem fictício do Universo Cinematográfico da Marvel (MCU), interpretado por Robert Downey Jr.. Gênio bilionário, inventor e filantropo, ele é a identidade civil do super-herói Homem de Ferro e figura central da franquia The Avengers, sendo um dos pilares da saga iniciada em 2008.', descriptionEn: 'Tony Stark is a fictional character in the Marvel Cinematic Universe (MCU), portrayed by Robert Downey Jr. A billionaire genius, inventor, and philanthropist, he is the civilian identity of the superhero Iron Man and a central figure in The Avengers franchise, being one of the pillars of the saga that began in 2008.' },
  ISB: { name: 'John Doe', imageQuery: 'se7en-kevin-spacey-john-doe', imageUrl: 'https://m.media-amazon.com/images/M/MV5BMzdiM2ZlYmUtMDY1Mi00NGE2LTk4ODYtMDhiYWVhOWIxZjhiXkEyXkFqcGc@._V1_QL75_UX525_.jpg', descriptionPt: 'John Doe é o assassino fictício do thriller policial Se7en, interpretado por Kevin Spacey. O personagem é o vilão central cuja série de crimes brutais gira em torno dos sete pecados capitais.', descriptionEn: 'John Doe is the fictional killer in the crime thriller Se7en, played by Kevin Spacey. The central villain whose series of brutal crimes revolves around the seven deadly sins.' },
  ISX: { name: 'Major Kusanagi', imageQuery: 'ghost-in-shell-major-kusanagi', imageUrl: 'https://upload.wikimedia.org/wikipedia/pt/a/a0/Motoko_Kusanagi_SAC.png', descriptionPt: 'Major Motoko Kusanagi é a protagonista cibernética da franquia Ghost in the Shell. Ela simboliza a fusão entre humanidade e tecnologia, explorando os limites da consciência e da identidade em um mundo altamente conectado.', descriptionEn: 'Major Motoko Kusanagi is the cybernetic protagonist of the Ghost in the Shell franchise. She symbolizes the fusion of humanity and technology, exploring the limits of consciousness and identity in a hyper-connected world.' },
  ISK: { name: 'Sherlock Holmes', imageQuery: 'sherlock-holmes', imageUrl: 'https://uploads.jovemnerd.com.br/wp-content/uploads/2020/09/sherlock-holmes-trends-twitter.jpg', descriptionPt: 'Sherlock Holmes é um detetive ficcional criado por Arthur Conan Doyle, conhecido por sua inteligência analítica, raciocínio dedutivo e atenção meticulosa aos detalhes. Como protagonista de contos e romances publicados entre 1887 e 1927, tornou-se um dos personagens literários mais reconhecíveis do mundo e uma figura central na cultura popular.', descriptionEn: 'Sherlock Holmes is a fictional detective created by Arthur Conan Doyle, known for his analytical intelligence, deductive reasoning, and meticulous attention to detail. As the protagonist of short stories and novels published between 1887 and 1927, he has become one of the world\'s most recognizable literary characters and a central figure in popular culture.' },
  ISD: { name: 'Roy Batty', imageQuery: 'blade-runner-roy-batty-rutger-hauer', imageUrl: 'https://br.web.img3.acsta.net/r_654_368/newsv7/16/01/08/17/41/128552.jpg', descriptionPt: 'Roy Batty é o carismático líder dos replicantes em Blade Runner (1982), interpretado por Rutger Hauer. Sua busca por mais vida e significado faz dele uma das figuras mais complexas do cinema de ficção científica.', descriptionEn: 'Roy Batty is the charismatic leader of the replicants in Blade Runner (1982), played by Rutger Hauer. His search for more life and meaning makes him one of the most complex figures in science fiction cinema.' },
  ISL: { name: 'Newt Scamander', imageQuery: 'newt-scamander', imageUrl: 'https://upload.wikimedia.org/wikipedia/en/c/c5/Newt_Scamander_in_New_York.jpg', descriptionPt: 'Newt Scamander é o protagonista da série cinematográfica Fantastic Beasts and Where to Find Them, parte do universo mágico criado por Harry Potter. Um magizoologista britânico excêntrico e compassivo, ele é conhecido por seu amor e cuidado com criaturas mágicas e por ser o autor fictício do livro didático homônimo usado em Harry Potter.', descriptionEn: 'Newt Scamander is the protagonist of the Fantastic Beasts and Where to Find Them film series, part of the magical universe created by Harry Potter. An eccentric and compassionate British magizoologist, he is known for his love and care for magical creatures and for being the fictional author of the eponymous textbook used in Harry Potter.' },
  CEA: { name: 'Walter Mitty', imageQuery: 'secret-life-walter-mitty-ben-stiller', imageUrl: 'https://pausadramatica.com.br/wp-content/uploads/2013/12/ben-stiller-in-a-still-fr-014.jpg', descriptionPt: 'Walter Mitty é o personagem principal de The Secret Life of Walter Mitty, estrelado por Ben Stiller. Um homem comum e sonhador que vive aventuras extraordinárias em sua imaginação, até que circunstâncias o levam a viver experiências reais transformadoras.', descriptionEn: 'Walter Mitty is the main character of The Secret Life of Walter Mitty, starring Ben Stiller. An ordinary daydreamer who lives extraordinary adventures in his imagination, until circumstances lead him to experience real transformative adventures.' },
  CEB: { name: 'Travis Bickle', imageQuery: 'taxi-driver-robert-de-niro-travis', imageUrl: 'https://f.i.uol.com.br/hunting/2017/06/01/14963466495930701969d8b_1496346649_16x9_md.jpg', descriptionPt: 'Travis Bickle é o protagonista fictício do filme Taxi Driver, interpretado por Robert De Niro. Tornou-se um dos personagens mais icônicos do cinema americano, símbolo de alienação urbana e colapso psicológico.', descriptionEn: 'Travis Bickle is the fictional protagonist of Taxi Driver, played by Robert De Niro. He became one of the most iconic characters in American cinema, a symbol of urban alienation and psychological collapse.' },
  CEX: { name: 'Louise Banks', imageQuery: 'louise-banks', imageUrl: 'https://getpersonality.com/_next/image?url=https%3A%2F%2Fstatic1.personality-database.com%2Fprofile_images%2F9ea99dddab884d748078bf6915cd53d8.png&w=3840&q=75', descriptionPt: 'Louise Banks é a protagonista do filme de ficção científica Arrival (2016), dirigido por Denis Villeneuve e baseado no conto Story of Your Life de Ted Chiang. Interpretada por Amy Adams, ela é uma linguista renomada encarregada de se comunicar com seres extraterrestres que chegam à Terra. Sua jornada une linguagem, tempo e emoção em uma narrativa sobre compreensão e destino.', descriptionEn: 'Louise Banks é protagonista do filme de ficção científica Arrival (2016), dirigido por Denis Villeneuve e baseado no conto Story of Your Life de Ted Chiang. Interpretada por Amy Adams, ela é uma linguista renomada encarregada de se comunicar com seres extraterrestres que chegam à Terra. Sua jornada é linguagem, tempo e emoção em uma narrativa sobre compreensão e destino.' },
  CEK: { name: 'Lawrence of Arabia', imageQuery: 'lawrence-of-arabia-peter-otoole', imageUrl: 'https://variety.com/wp-content/uploads/2017/01/lawrence-of-arabia.jpg?w=1000', descriptionPt: 'Lawrence of Arabia é o personagem principal do épico cinematográfico de 1962, interpretado por Peter O\'Toole. É uma representação dramática de um homem dividido entre culturas e identidades durante a Primeira Guerra Mundial.', descriptionEn: 'Lawrence of Arabia is the main character of the 1962 epic film, played by Peter O\'Toole. He is a dramatic representation of a man divided between cultures and identities during World War I.' },
  CED: { name: 'Daniel Plainview', imageUrl: 'https://cdn1.faroutmagazine.co.uk/uploads/1/2023/04/Daniel-Plainview-Daniel-Day-Lewis-There-Will-Be-Blood-Paul-Thomas-Anderson-Far-Out-Magazine-F-1140x855.jpg', imageQuery: 'there-will-be-blood-daniel-day-lewis', descriptionPt: 'Daniel Plainview é o protagonista fictício do filme There Will Be Blood, interpretado por Daniel Day-Lewis. Um ambicioso empresário do petróleo do início do século XX, simboliza o poder corrosivo da ganância no capitalismo americano.', descriptionEn: 'Daniel Plainview is the fictional protagonist of There Will Be Blood, played by Daniel Day-Lewis. An ambitious oil entrepreneur from the early 20th century, he symbolizes the corrosive power of greed in American capitalism.' },
  CEL: { name: 'Miguel Rivera', imageQuery: 'miguel-rivera', imageUrl: 'https://static.wikia.nocookie.net/disneyfanon/images/0/00/Profile_-_Miguel_Rivera.jpg/revision/latest?cb=20250410073004', descriptionPt: 'Miguel Rivera é o protagonista do filme animado Coco (2017), produzido pela Pixar Animation Studios e lançado pela Walt Disney Pictures. Ele é um menino mexicano de 12 anos apaixonado por música que desafia as tradições familiares ao sonhar em se tornar músico como seu ídolo Ernesto de la Cruz.', descriptionEn: 'Miguel Rivera is the protagonist of the animated film Coco (2017), produced by Pixar Animation Studios and released by Walt Disney Pictures. He is a 12-year-old Mexican boy passionate about music who defies family traditions by dreaming of becoming a musician like his idol Ernesto de la Cruz.' },
  CIA: { name: 'Dr. Ellie Arroway', imageQuery: 'ellie-arroway', imageUrl: 'https://scienceonscreen.org/assets/films/_1600x900_crop_top-center_75_none/Contact.jpg', descriptionPt: 'Dr. Ellie Arroway é a protagonista do filme de ficção científica Contact, interpretada por Jodie Foster. A personagem é uma astrônoma e cientista do programa SETI (Search for Extraterrestrial Intelligence), dedicada a encontrar sinais de vida inteligente fora da Terra. Sua busca simboliza a tensão entre fé, ciência e o desejo humano de compreender o universo.', descriptionEn: 'Ellie Arroway is the protagonist of the science fiction film Contact, portrayed by Jodie Foster. The character is an astronomer and scientist with the SETI (Search for Extraterrestrial Intelligence) program, dedicated to finding signs of intelligent life beyond Earth. Her quest symbolizes the tension between faith, science, and humanity\'s desire to understand the universe.' },
  CIB: { name: 'Hans Landa', imageQuery: 'hans-landa', imageUrl: 'https://m.media-amazon.com/images/M/MV5BM2YwZGYxY2YtOWE3Yy00OGIzLWExMzAtMzA1MjE5YzMyNWJiXkEyXkFqcGc@._V1_QL75_UX500_CR0,26,500,281_.jpg', descriptionPt: 'Hans Landa é o principal antagonista do filme Inglourious Basterds (2009), dirigido por Quentin Tarantino. Interpretado por Christoph Waltz, o personagem é um coronel da SS (Standartenführer) conhecido por sua inteligência afiada, charme e crueldade calculada. Sua performance consagrou Waltz internacionalmente e lhe rendeu o Oscar de Melhor Ator Coadjuvante.', descriptionEn: 'Hans Landa is the main antagonist in the film Inglourious Basterds (2009), directed by Quentin Tarantino. Played by Christoph Waltz, the character is an SS colonel (Standartenführer) known for his sharp intelligence, charm, and calculated cruelty. His performance earned Waltz international acclaim and the Academy Award for Best Supporting Actor.' },
  CIX: { name: 'O Stalker', imageQuery: 'stalker-tarkovsky-1979', imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8bSVQiSF1tUjqjNhChDb6Hy8-ecCJ6lrETg&s',descriptionPt: 'O Stalker é o personagem central do filme soviético de ficção científica Stalker, de Andrei Tarkovsky. Ele guia dois homens através de uma área misteriosa e proibida chamada Zona, que supostamente concede os desejos mais profundos.', descriptionEn: 'The Stalker is the central character of Andrei Tarkovsky\'s Soviet sci-fi film Stalker. He guides two men through a mysterious forbidden area called the Zone, which supposedly grants the deepest wishes of those who reach its center.' },
  CIK: { name: 'Antonius Block', imageQuery: 'seventh-seal-max-von-sydow', imageUrl: 'https://images.mubicdn.net/images/avatars/129005/cache-129005-1574075409/images-large.jpg?size=800x', descriptionPt: 'Antonius Block é o cavaleiro fictício de O Sétimo Selo (1957), de Ingmar Bergman. Ele enfrenta uma personificação da Morte em uma partida de xadrez, buscando sentido e fé em meio à peste e ao silêncio divino.', descriptionEn: 'Antonius Block is the fictional knight in Ingmar Bergman\'s The Seventh Seal (1957). He faces a personification of Death in a game of chess, seeking meaning and faith amid plague and divine silence.' },
  CID: { name: 'Lydia Tár', imageQuery: 'lydia-tar', imageUrl: 'https://images.impresa.pt/expresso/2023-02-08-TAR_T.jpg-ac4c6da6/original', descriptionPt: 'Lydia Tár é a personagem principal fictícia do filme Tár, interpretada por Cate Blanchett. Ela é retratada como uma maestrina e compositora de renome mundial, cuja carreira e reputação entram em colapso diante de controvérsias pessoais e éticas. A personagem se tornou um estudo de poder, ambição e queda na música erudita contemporânea.', descriptionEn: 'Lydia Tar is the fictional main character in the film Tar, portrayed by Cate Blanchett. She is depicted as a world-renowned conductor and composer whose career and reputation collapse amidst personal and ethical controversies. The character has become a study of power, ambition, and downfall in contemporary classical music.' },
  CIL: { name: 'Milo Thatch', imageQuery: 'milo-atlantis', imageUrl: 'https://static.wikia.nocookie.net/disney/images/4/40/Profile_-_Milo_Thatch.png/revision/latest/thumbnail/width/360/height/360?cb=20190401182656', descriptionPt: 'Milo James Thatch é o protagonista do filme de animação Atlantis: The Lost Empire (2001), da Disney. Ele é um linguista e cartógrafo idealista que sonha em encontrar a lendária cidade de Atlântida. Sua curiosidade intelectual e coragem moral o tornam um herói atípico no cânone de aventuras da Disney.', descriptionEn: 'Milo James Thatch is the protagonist of the Disney animated film Atlantis: The Lost Empire (2001). He is an idealistic linguist and cartographer who dreams of finding the legendary city of Atlantis. His intellectual curiosity and moral courage make him an atypical hero in the Disney adventure canon.' },
  CRA: { name: 'Aang', imageQuery: 'avatar-aang-last-airbender', imageUrl: 'https://static.wikia.nocookie.net/avatar/images/c/ce/Aang.png/revision/latest/scale-to-width/360?cb=20161129194603&path-prefix=pt-br', descriptionPt: 'Aang é o protagonista da série animada Avatar: The Last Airbender. Ele é o último sobrevivente dos Nômades do Ar e o atual Avatar, responsável por manter o equilíbrio entre as quatro nações e os elementos.', descriptionEn: 'Aang is the protagonist of Avatar: The Last Airbender. He is the last survivor of the Air Nomads and the current Avatar, responsible for maintaining balance between the four nations and the elements.' },
  CRB: { name: 'Ofelia', imageQuery: 'ofelia', imageUrl: 'https://vejasp.abril.com.br/wp-content/uploads/2016/12/el-laberinto.jpg?quality=70&strip=all', descriptionPt: 'Ofelia é a protagonista do filme O Labirinto do Fauno (Pan’s Labyrinth), dirigido por Guillermo del Toro. Ambientada na Espanha franquista de 1944, ela é uma menina de imaginação vívida que descobre um mundo mágico sombrio paralelo à brutalidade da guerra civil. O personagem simboliza a inocência e a resistência da fantasia diante da tirania e da violência.', descriptionEn: 'Ofelia is the protagonist of the film Pan\'s Labyrinth, directed by Guillermo del Toro. Set in Francoist Spain in 1944, she is a girl with a vivid imagination who discovers a dark, magical world parallel to the brutality of the civil war. The character symbolizes the innocence and resilience of fantasy in the face of tyranny and violence.' },
  CRX: { name: 'Pi Patel', imageQuery: 'pi', imageUrl: 'https://static.wikia.nocookie.net/p__/images/e/e6/Life_of_pi_7.jpg/revision/latest?cb=20220819134432&path-prefix=protagonist', descriptionPt: 'Pi Patel é o protagonista fictício do romance Life of Pi (2001), adaptado para o cinema em Life of Pi, dirigido por Ang Lee. Conhecido por sua busca espiritual e notável sobrevivência no mar, Pi simboliza a fé, a imaginação e a resiliência humana.', descriptionEn: 'Pi Patel is the fictional protagonist of the novel Life of Pi (2001), adapted into the film Life of Pi, directed by Ang Lee. Known for his spiritual quest and remarkable survival at sea, Pi symbolizes faith, imagination, and human resilience.' },
  CRK: { name: 'Zorro', imageQuery: 'zorro', imageUrl: 'https://cloudfront-us-east-1.images.arcpublishing.com/estadao/3HWSBHDAPVOWFO3KIMILS7FPLU.jpg', descriptionPt: 'Zorro é um personagem fictício de um justiceiro mascarado criado por Johnston McCulley em 1919. Conhecido por usar uma máscara preta e uma capa, ele defende os oprimidos contra autoridades corruptas na Califórnia sob domínio espanhol. O personagem tornou-se um ícone cultural, símbolo de justiça, astúcia e rebeldia heroica.', descriptionEn: 'Zorro is a fictional character, a masked vigilante created by Johnston McCulley in 1919. Known for wearing a black mask and cape, he defends the oppressed against corrupt authorities in Spanish-ruled California. The character has become a cultural icon, a symbol of justice, cunning, and heroic rebellion.' },
  CRD: { name: 'Príncipe Ashitaka', imageQuery: 'princess-mononoke-ashitaka-ghibli', imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTK63r5LwRS5acbs4C0pSqXtQ64Ga5w9fwztQ&s', descriptionPt: 'O Príncipe Ashitaka é o protagonista de Princess Mononoke, de Hayao Miyazaki. Um jovem príncipe cuja jornada o coloca no centro de um conflito entre a natureza e a industrialização.', descriptionEn: 'Prince Ashitaka is the protagonist of Hayao Miyazaki\'s Princess Mononoke. A young prince whose journey places him at the center of a conflict between nature and industrialization.' },
  CRL: { name: 'Sr. Miyagi', imageUrl: 'https://static.wikia.nocookie.net/p__/images/3/31/IMG_1639.jpeg/revision/latest?cb=20230724195456&path-prefix=protagonist', imageQuery: "miyagi", descriptionPt: 'Sr. Miyagi (Mr. Miyagi) é um personagem fictício da série de filmes The Karate Kid, conhecido por ser o sábio e paciente mestre de caratê de Daniel LaRusso. Interpretado por Pat Morita, tornou-se um ícone cultural por representar a filosofia oriental de equilíbrio, disciplina e respeito.', descriptionEn: "Mr. Miyagi is a fictional character from The Karate Kid film series, known for being Daniel LaRusso's wise and patient karate master. Portrayed by Pat Morita, he has become a cultural icon for representing the Eastern philosophy of balance, discipline, and respect." },
  CSA: { name: 'Babette', imageQuery: 'babette', imageUrl: 'https://s2.glbimg.com/mWmVhZxA9WX1fug9Au3mGVY7blA=/e.glbimg.com/og/ed/f/original/2020/06/02/babette.jpg', descriptionPt: 'Babette é a personagem central do filme A Festa de Babette, adaptação da obra de A Festa de Babette (pseudônimo de Karen Blixen). Exilada da França e acolhida em um vilarejo austero da Dinamarca do século XIX, Babette transforma uma comunidade religiosa ao preparar um banquete memorável.', descriptionEn: 'Babette is the central character in the film Babette\'s Feast, an adaptation of the novel by Karen Blixen (pseudonym of Babette). Exiled from France and welcomed into an austere 19th-century Danish village, Babette transforms a religious community by preparing a memorable banquet.' },
  CSB: { name: 'Tom Ripley', imageQuery: 'talented-mr-ripley-matt-damon', descriptionPt: 'Tom Ripley é o protagonista fictício de O Talentoso Ripley, interpretado por Matt Damon. Um jovem impostor de personalidade enigmática, ambição obsessiva e moral ambígua.', descriptionEn: 'Tom Ripley is the fictional protagonist of The Talented Mr. Ripley, played by Matt Damon. A young impostor with an enigmatic personality, obsessive ambition, and ambiguous morality.' },
  CSX: { name: 'Pinóquio', imageQuery: 'pinocchio-guillermo-del-toro', descriptionPt: 'Pinóquio é o protagonista do filme em stop motion de Guillermo del Toro. Inspirado no romance clássico de Carlo Collodi, essa versão reinventa o boneco de madeira como um símbolo de inocência e desobediência.', descriptionEn: 'Pinocchio is the protagonist of Guillermo del Toro\'s stop-motion film. Inspired by Carlo Collodi\'s classic novel, this version reimagines the wooden puppet as a symbol of innocence and defiance.' },
  CSK: { name: 'Jay Gatsby', imageQuery: 'great-gatsby-leonardo-dicaprio', descriptionPt: 'Jay Gatsby é o personagem central de The Great Gatsby. Figura enigmática e símbolo do sonho americano, conhecido por sua riqueza extravagante, festas luxuosas e paixão obsessiva por Daisy Buchanan.', descriptionEn: 'Jay Gatsby is the central character of The Great Gatsby. An enigmatic figure and symbol of the American Dream, known for his extravagant wealth, lavish parties, and obsessive passion for Daisy Buchanan.' },
  CSD: { name: 'Capitão Willard', imageQuery: 'apocalypse-now-martin-sheen-willard', descriptionPt: 'Capitão Willard é o personagem central de Apocalypse Now, interpretado por Martin Sheen. Um oficial do Exército dos EUA enviado em missão secreta para eliminar o coronel renegado Walter E. Kurtz durante a Guerra do Vietnã.', descriptionEn: 'Captain Willard is the central character of Apocalypse Now, played by Martin Sheen. A U.S. Army officer sent on a secret mission to eliminate the renegade Colonel Kurtz during the Vietnam War.' },
  CSL: { name: 'Monsieur Hulot', imageQuery: 'monsieur-hulot-holiday-tati', descriptionPt: 'Monsieur Hulot é o personagem central criado e interpretado por Jacques Tati. Figura excêntrica, gentil e desajeitada, tornou-se um dos ícones cômicos mais duradouros do cinema francês do pós-guerra.', descriptionEn: 'Monsieur Hulot is the central character created and played by Jacques Tati. An eccentric, gentle, and clumsy figure, he became one of the most enduring comic icons of postwar French cinema.' },
  REA: { name: 'Paddington', imageQuery: 'paddington-bear-movie', descriptionPt: 'Paddington é um urso educado e bem-intencionado originário do "Darkest Peru", que se torna protagonista dos filmes Paddington. Criado por Michael Bond, ele vive aventuras em Londres com a família Brown.', descriptionEn: 'Paddington is a polite and well-meaning bear from "Darkest Peru" who becomes the protagonist of the Paddington films. Created by Michael Bond, he lives adventures in London with the Brown family.' },
  REB: { name: 'Cruella de Vil', imageQuery: 'cruella-de-vil-101-dalmatians', descriptionPt: 'Cruella de Vil é a principal antagonista de 101 Dálmatas, retratada como uma socialite excêntrica e obcecada por moda que deseja fazer casacos de pele com filhotes de dálmata.', descriptionEn: 'Cruella de Vil is the main antagonist of 101 Dalmatians, portrayed as an eccentric, fashion-obsessed socialite who wants to make fur coats from dalmatian puppies.' },
  REX: { name: 'Baby', imageQuery: 'baby-driver-ansel-elgort', descriptionPt: 'Baby é o protagonista do filme Baby Driver, interpretado por Ansel Elgort. Um jovem e talentoso motorista de fuga que usa a música como refúgio para lidar com um zumbido crônico nos ouvidos.', descriptionEn: 'Baby is the protagonist of Baby Driver, played by Ansel Elgort. A young and talented getaway driver who uses music as refuge to cope with a chronic ringing in his ears.' },
  REK: { name: 'Danny Ocean', imageQuery: "ocean's-eleven-george-clooney", descriptionPt: 'Danny Ocean é o protagonista da franquia de filmes Ocean\'s Eleven, interpretado por George Clooney. Símbolo do golpista elegante e calculista no cinema de assaltos.', descriptionEn: 'Danny Ocean is the protagonist of the Ocean\'s Eleven film franchise, played by George Clooney. A symbol of the elegant and calculating con man in heist cinema.' },
  RED: { name: 'Jordan Belfort', imageQuery: 'wolf-of-wall-street-leonardo-dicaprio', descriptionPt: 'Jordan Belfort é o protagonista de The Wolf of Wall Street, de Martin Scorsese. Baseado em pessoa real, é um corretor de ações ambicioso cuja ascensão e queda ilustram o excesso e a corrupção de Wall Street.', descriptionEn: 'Jordan Belfort is the protagonist of The Wolf of Wall Street by Martin Scorsese. Based on a real person, he is an ambitious stockbroker whose meteoric rise and spectacular fall illustrate the excess and corruption of Wall Street.' },
  REL: { name: 'Ferris Bueller', imageQuery: 'ferris-buellers-day-off-matthew-broderick', descriptionPt: 'Ferris Bueller é o protagonista de Ferris Bueller\'s Day Off, interpretado por Matthew Broderick. O arquétipo do estudante espirituoso e rebelde dos anos 1980 que desafia regras em busca de liberdade.', descriptionEn: 'Ferris Bueller is the protagonist of Ferris Bueller\'s Day Off, played by Matthew Broderick. The archetype of the witty and rebellious 1980s student who defies rules in pursuit of freedom.' },
  RIA: { name: 'Woody', imageQuery: 'toy-story-woody-tom-hanks', descriptionPt: 'Woody é o protagonista da franquia Toy Story, criada pela Pixar. Um boneco de caubói que atua como líder e figura paternal entre os brinquedos de Andy.', descriptionEn: 'Woody is the protagonist of Pixar\'s Toy Story franchise. A cowboy doll who acts as leader and paternal figure among Andy\'s toys, voiced by Tom Hanks.' },
  RIB: { name: 'Sid Phillips', imageQuery: 'toy-story-sid-phillips', descriptionPt: 'Sid Phillips é o principal antagonista do primeiro Toy Story (1995). Conhecido por seu comportamento destrutivo com brinquedos, tornou-se um dos vilões infantis mais memoráveis da animação moderna.', descriptionEn: 'Sid Phillips is the main antagonist of the first Toy Story (1995). Known for his destructive behavior with toys, he became one of the most memorable child villains in modern animation.' },
  RIX: { name: 'Vanellope', imageQuery: 'wreck-it-ralph-vanellope', descriptionPt: 'Vanellope von Schweetz é uma personagem de Wreck-It Ralph. Uma corredora carismática e rebelde do jogo "Sugar Rush", conhecida por seu espírito determinado e sua habilidade de "glitchar".', descriptionEn: 'Vanellope von Schweetz is a character from Wreck-It Ralph. A charismatic and rebellious racer from the game "Sugar Rush", known for her determined spirit and ability to "glitch".' },
  RIK: { name: 'George Bailey', imageQuery: "it's-a-wonderful-life-james-stewart", descriptionPt: 'George Bailey é o protagonista de It\'s a Wonderful Life (1946), interpretado por James Stewart. Um homem generoso e idealista que sacrifica seus sonhos para ajudar os outros, símbolo de empatia e propósito.', descriptionEn: 'George Bailey is the protagonist of It\'s a Wonderful Life (1946), played by James Stewart. A generous and idealistic man who sacrifices his dreams to help others, a symbol of empathy and purpose.' },
  RID: { name: 'Cady Heron', imageQuery: 'mean-girls-lindsay-lohan-cady', descriptionPt: 'Cady Heron é a protagonista de Mean Girls, interpretada por Lindsay Lohan. Criada na África, ela entra em uma escola americana e tenta se adaptar às complexas dinâmicas sociais do ensino médio.', descriptionEn: 'Cady Heron is the protagonist of Mean Girls, played by Lindsay Lohan. Raised in Africa, she enters an American high school and tries to adapt to its complex social dynamics.' },
  RIL: { name: 'Shrek', imageQuery: 'shrek-dreamworks-animation', descriptionPt: 'Shrek é o protagonista da franquia de animação Shrek, da DreamWorks. Um ogro verde que vive isolado em um pântano e se tornou um dos ícones mais reconhecíveis da animação moderna.', descriptionEn: 'Shrek is the protagonist of DreamWorks\' Shrek animation franchise. A green ogre who lives isolated in a swamp and became one of the most recognizable icons of modern animation.' },
  RCA: { name: 'Miguel Rivera', imageQuery: 'coco-pixar-miguel-rivera', descriptionPt: 'Miguel Rivera é o protagonista do filme animado Coco (2017) da Pixar. Um menino mexicano apaixonado por música que desafia as tradições familiares ao sonhar em se tornar músico.', descriptionEn: 'Miguel Rivera is the protagonist of Pixar\'s animated film Coco (2017). A Mexican boy passionate about music who defies family traditions by dreaming of becoming a musician.' },
  RCB: { name: 'Selina Kyle', imageQuery: 'the-batman-catwoman-zoe-kravitz', descriptionPt: 'Selina Kyle é interpretada por Zoë Kravitz em The Batman. A Mulher-Gato é uma ladra e vigilante de Gotham City que se move entre o crime e a justiça, tornando-se aliada e contraponto moral de Bruce Wayne.', descriptionEn: 'Selina Kyle is played by Zoë Kravitz in The Batman. Catwoman is a Gotham City thief and vigilante who moves between crime and justice, becoming both ally and moral counterpoint to Bruce Wayne.' },
  RCX: { name: 'Evelyn Wang', imageQuery: 'everything-everywhere-all-at-once-michelle-yeoh', descriptionPt: 'Evelyn Wang é a protagonista de Everything Everywhere All at Once, interpretada por Michelle Yeoh. Uma imigrante chinesa nos EUA que descobre estar conectada a múltiplas versões de si mesma em universos paralelos.', descriptionEn: 'Evelyn Wang is the protagonist of Everything Everywhere All at Once, played by Michelle Yeoh. A Chinese immigrant in the US who discovers she is connected to multiple versions of herself across parallel universes.' },
  RCK: { name: 'Phileas Fogg', imageQuery: 'around-world-eighty-days-phileas-fogg', descriptionPt: 'Phileas Fogg é o protagonista de Around the World in Eighty Days, de Jules Verne. Um cavalheiro inglês metódico e reservado que aposta poder dar a volta ao mundo em 80 dias.', descriptionEn: 'Phileas Fogg is the protagonist of Jules Verne\'s Around the World in Eighty Days. A methodical and reserved English gentleman who bets he can circumnavigate the globe in 80 days.' },
  RCD: { name: 'Rick Deckard', imageQuery: 'blade-runner-rick-deckard-harrison-ford', descriptionPt: 'Rick Deckard é o protagonista da franquia Blade Runner, interpretado por Harrison Ford. Ele é um agente especializado em caçar e "aposentar" replicantes — seres artificiais indistinguíveis de humanos.', descriptionEn: 'Rick Deckard is the protagonist of the Blade Runner franchise, played by Harrison Ford. He is a specialized agent hunting down and "retiring" replicants — artificial beings indistinguishable from humans.' },
  RCL: { name: 'Linguini', imageQuery: 'ratatouille-pixar-linguini', descriptionPt: 'Linguini (Alfredo Linguini) é um dos protagonistas de Ratatouille, da Pixar (2007). Conhecido por sua relação improvável com o rato chef Remy.', descriptionEn: 'Linguini (Alfredo Linguini) is one of the protagonists of Pixar\'s Ratatouille (2007), known for his unlikely relationship with the chef rat Remy.' },
  RSA: { name: 'Olaf', imageQuery: 'frozen-olaf-snowman-disney', descriptionPt: 'Olaf é um personagem fictício do filme Frozen, da Disney. Um boneco de neve encantado que serve como alívio cômico e símbolo de inocência e amizade.', descriptionEn: 'Olaf is a fictional character from Disney\'s Frozen. An enchanted snowman who serves as comic relief and a symbol of innocence and friendship.' },
  RSB: { name: 'Harley Quinn', imageQuery: 'harley-quinn-margot-robbie-suicide-squad', descriptionPt: 'Harley Quinn é interpretada por Margot Robbie no universo DC. Integrante do Suicide Squad, ela é conhecida por sua estética marcante e comportamento imprevisível.', descriptionEn: 'Harley Quinn is played by Margot Robbie in the DC universe. A member of Suicide Squad, she is known for her striking aesthetic and unpredictable behavior.' },
  RSX: { name: 'Deadpool', imageQuery: 'deadpool-marvel-ryan-reynolds', descriptionPt: 'Deadpool é um personagem da Marvel Comics, conhecido por seu humor sarcástico, consciência metalinguística e habilidades de regeneração. Tornou-se um dos anti-heróis mais populares da cultura pop.', descriptionEn: 'Deadpool is a Marvel Comics character known for his sarcastic humor, meta-awareness, and regenerative abilities. He became one of the most popular anti-heroes in pop culture.' },
  RSK: { name: 'Han Solo', imageQuery: 'star-wars-han-solo-harrison-ford', descriptionPt: 'Han Solo é um personagem do universo Star Wars, interpretado por Harrison Ford. Um contrabandista que se torna herói da Aliança Rebelde, um dos ícones mais reconhecíveis da cultura pop.', descriptionEn: 'Han Solo is a Star Wars character, played by Harrison Ford. A smuggler who becomes a hero of the Rebel Alliance, one of the most recognizable icons in pop culture.' },
  RSD: { name: 'Jake Sully', imageQuery: 'avatar-jake-sully-james-cameron', descriptionPt: 'Jake Sully é o protagonista fictício do universo Avatar, de James Cameron. Ex-fuzileiro naval paraplégico, torna-se o elo entre humanos e os Na\'vi, ao assumir um corpo avatar.', descriptionEn: 'Jake Sully is the fictional protagonist of James Cameron\'s Avatar universe. A paraplegic former Marine, he becomes the link between humans and the Na\'vi by inhabiting an avatar body.' },
  RSL: { name: 'Kuzco', imageQuery: 'emperors-new-groove-kuzco-disney', descriptionPt: 'Kuzco é o protagonista de A Nova Onda do Imperador, da Disney. Um jovem imperador inca egocêntrico que aprende humildade e empatia após ser transformado em uma lhama.', descriptionEn: 'Kuzco is the protagonist of Disney\'s The Emperor\'s New Groove. A self-centered young Inca emperor who learns humility and empathy after being transformed into a llama.' },
  SEA: { name: 'Maverick', imageQuery: 'top-gun-maverick-tom-cruise', descriptionPt: '"Maverick" é o codinome de Pete Mitchell, protagonista da franquia Top Gun, interpretado por Tom Cruise. Um piloto da Marinha dos EUA conhecido por sua ousadia e espírito rebelde.', descriptionEn: '"Maverick" is the callsign of Pete Mitchell, protagonist of the Top Gun franchise, played by Tom Cruise. A U.S. Navy pilot known for his daring and rebellious spirit.' },
  SEB: { name: 'Patrick Bateman', imageQuery: 'american-psycho-christian-bale-bateman', descriptionPt: 'Patrick Bateman é o protagonista de American Psycho, interpretado por Christian Bale. Um executivo de Manhattan cuja vida dupla como serial killer serve de sátira à cultura consumista dos anos 1980.', descriptionEn: 'Patrick Bateman is the protagonist of American Psycho, played by Christian Bale. A Manhattan executive whose double life as a serial killer serves as a satire of 1980s consumer culture.' },
  SEX: { name: 'Max Rockatansky', imageQuery: 'mad-max-fury-road', descriptionPt: 'Max Rockatansky é o protagonista da franquia Mad Max. Um ex-policial que sobrevive em um mundo pós-apocalíptico dominado pela escassez e violência, símbolo do anti-herói solitário.', descriptionEn: 'Max Rockatansky is the protagonist of the Mad Max franchise. A former police officer surviving in a post-apocalyptic world dominated by scarcity and violence, symbolizing the solitary anti-hero.' },
  SEK: { name: 'Indiana Jones', imageQuery: 'indiana-jones-harrison-ford', descriptionPt: 'Indiana Jones é um arqueólogo e aventureiro fictício, interpretado por Harrison Ford. Criado por George Lucas, tornou-se um ícone da cultura pop por combinar erudição acadêmica com coragem.', descriptionEn: 'Indiana Jones is a fictional archaeologist and adventurer, played by Harrison Ford. Created by George Lucas, he became a pop culture icon for combining academic scholarship with courage.' },
  SED: { name: 'Neil McCauley', imageQuery: 'heat-1995-robert-de-niro-neil', descriptionPt: 'Neil McCauley é o personagem principal do filme Heat, interpretado por Robert De Niro. Um ladrão profissional meticuloso que lidera uma equipe de assaltantes em Los Angeles.', descriptionEn: 'Neil McCauley is the main character of Heat, played by Robert De Niro. A meticulous professional thief who leads a crew of robbers in Los Angeles.' },
  SEL: { name: 'Peter Parker', imageQuery: 'spider-man-peter-parker-tom-holland', descriptionPt: 'Peter Parker é o alter ego do Homem-Aranha no MCU, interpretado por Tom Holland. Um estudante do Queens que adquire poderes aracnídeos e se torna um dos heróis centrais dos Vingadores.', descriptionEn: 'Peter Parker is Spider-Man\'s alter ego in the MCU, played by Tom Holland. A Queens student who acquires spider-like powers and becomes one of the central heroes of the Avengers.' },
  SIA: { name: 'The Dude', imageQuery: 'big-lebowski-jeff-bridges-dude', descriptionPt: 'Jeffrey "The Dude" Lebowski é o protagonista de The Big Lebowski, interpretado por Jeff Bridges. Um ícone cultural conhecido por seu estilo despreocupado e filosofia "go with the flow".', descriptionEn: 'Jeffrey "The Dude" Lebowski is the protagonist of The Big Lebowski, played by Jeff Bridges. A cultural icon known for his laid-back style and "go with the flow" philosophy.' },
  SIB: { name: 'Alex DeLarge', imageQuery: 'clockwork-orange-alex-delarge', descriptionPt: 'Alex DeLarge é o protagonista fictício de A Clockwork Orange, de Kubrick, interpretado por Malcolm McDowell. Tornou-se um ícone cultural por sua combinação de charme, violência e crítica social.', descriptionEn: 'Alex DeLarge is the fictional protagonist of Kubrick\'s A Clockwork Orange, played by Malcolm McDowell. He became a cultural icon for his combination of charm, violence, and social commentary.' },
  SIX: { name: 'Donnie Darko', imageQuery: 'donnie-darko-jake-gyllenhaal', descriptionPt: 'Donnie Darko é o protagonista do filme de 2001 de mesmo nome, interpretado por Jake Gyllenhaal. Um adolescente problemático que enfrenta visões apocalípticas e dilemas sobre destino e livre-arbítrio.', descriptionEn: 'Donnie Darko is the protagonist of the 2001 film of the same name, played by Jake Gyllenhaal. A troubled teenager who faces apocalyptic visions and dilemmas about fate and free will.' },
  SIK: { name: 'James Bond', imageQuery: 'james-bond-007-spy', descriptionPt: 'James Bond é um personagem fictício criado por Ian Fleming em 1953. Conhecido pelo codinome "007", é um agente secreto do MI6 e se tornou um ícone global, representando o espião sofisticado e carismático.', descriptionEn: 'James Bond is a fictional character created by Ian Fleming in 1953. Known by the code name "007", he is a British MI6 secret agent who became a global icon representing the sophisticated and charismatic spy.' },
  SID: { name: 'K', imageQuery: 'blade-runner-2049-ryan-gosling-k', descriptionPt: 'K é o personagem principal de Blade Runner 2049, interpretado por Ryan Gosling. Um "blade runner" replicante em uma jornada de autodescoberta e humanidade em um mundo dominado por IA.', descriptionEn: 'K is the main character of Blade Runner 2049, played by Ryan Gosling. A replicant blade runner on a journey of self-discovery and humanity in a world dominated by artificial intelligence.' },
  SIL: { name: 'Marty McFly', imageQuery: 'back-to-future-marty-mcfly-michael-j-fox', descriptionPt: 'Marty McFly é o protagonista da trilogia Back to the Future, interpretado por Michael J. Fox. Um adolescente californiano que viaja no tempo com a ajuda do excêntrico Dr. Emmett Brown.', descriptionEn: 'Marty McFly is the protagonist of the Back to the Future trilogy, played by Michael J. Fox. A California teenager who travels through time with the help of the eccentric Dr. Emmett Brown.' },
  SCA: { name: 'Sophie Hatter', imageQuery: "howl's-moving-castle-sophie-ghibli", descriptionPt: 'Sophie Hatter é a protagonista de Howl\'s Moving Castle, de Hayao Miyazaki. Uma jovem modista transformada em idosa por um feitiço, cuja jornada de autodescoberta impulsiona toda a narrativa.', descriptionEn: "Sophie Hatter is the protagonist of Hayao Miyazaki's Howl's Moving Castle. A young hat-maker transformed into an old woman by a curse, whose journey of self-discovery drives the entire narrative." },
  SCB: { name: 'Lestat de Lioncourt', imageQuery: 'interview-vampire-lestat-brad-pitt', descriptionPt: 'Lestat de Lioncourt é um personagem central de Entrevista com o Vampiro. Aristocrático e carismático, é um vampiro francês do século XVIII, conhecido por sua natureza rebelde.', descriptionEn: 'Lestat de Lioncourt is a central character in Interview with the Vampire. Aristocratic and charismatic, he is an 18th-century French vampire known for his rebellious nature.' },
  SCX: { name: 'Jef Costello', imageQuery: 'le-samourai-alain-delon', descriptionPt: 'Jef Costello é o personagem principal de Le Samouraï, interpretado por Alain Delon. Figura icônica do cinema noir francês, é um assassino de aluguel meticuloso cuja frieza reflete um código de conduta quase ritualístico.', descriptionEn: 'Jef Costello is the main character of Le Samouraï, played by Alain Delon. An iconic figure of French noir cinema, he is a meticulous contract killer whose coldness reflects an almost ritualistic code of conduct.' },
  SCK: { name: 'Vito Corleone', imageQuery: 'godfather-vito-corleone-marlon-brando', descriptionPt: 'Vito Corleone é o patriarca fictício da família Corleone em The Godfather. Símbolo do arquétipo do "padrinho", representa poder, tradição e a complexa moralidade das famílias mafiosas.', descriptionEn: 'Vito Corleone is the fictional patriarch of the Corleone family in The Godfather. A symbol of the "godfather" archetype, he represents power, tradition, and the complex morality of Mafia families.' },
  SCD: { name: 'Hannibal Lecter', imageQuery: 'silence-lambs-hannibal-lecter-anthony-hopkins', descriptionPt: 'Hannibal Lecter é o principal antagonista de The Silence of the Lambs. Um psiquiatra brilhante e assassino em série canibal, cuja inteligência refinada o tornou um dos vilões mais icônicos do cinema.', descriptionEn: 'Hannibal Lecter is the main antagonist of The Silence of the Lambs. A brilliant psychiatrist and cannibalistic serial killer whose refined intelligence made him one of the most iconic villains in cinema.' },
  SCL: { name: 'M. Gustave H.', imageQuery: 'grand-budapest-hotel-ralph-fiennes-gustave', descriptionPt: 'Monsieur Gustave H. é o gerente do Grand Budapest Hotel, em The Grand Budapest Hotel de Wes Anderson. Dedicado, elegante e excêntrico, sua figura simboliza a velha Europa de cortesia em declínio.', descriptionEn: 'Monsieur Gustave H. is the manager of the Grand Budapest Hotel in Wes Anderson\'s film. Dedicated, elegant, and eccentric, his figure symbolizes the old Europe of courtesy and refinement in decline.' },
  SRA: { name: 'Po', imageQuery: 'kung-fu-panda-po-dreamworks', descriptionPt: 'Po é o protagonista da franquia Kung Fu Panda, da DreamWorks. Um panda desajeitado e apaixonado por kung fu que se torna o lendário "Guerreiro Dragão".', descriptionEn: 'Po is the protagonist of DreamWorks\' Kung Fu Panda franchise. A clumsy panda passionate about kung fu who unexpectedly becomes the legendary "Dragon Warrior".' },
  SRB: { name: 'Eric Draven', imageQuery: 'the-crow-brandon-lee', descriptionPt: 'Eric Draven é o protagonista de The Crow, interpretado por Brandon Lee. Um músico assassinado que retorna dos mortos para vingar sua morte e a de sua noiva. Tornou-se um ícone gótico do cinema dos anos 1990.', descriptionEn: 'Eric Draven is the protagonist of The Crow, played by Brandon Lee. A musician murdered who returns from the dead to avenge his own death and that of his fiancée. He became a gothic icon of 1990s cinema.' },
  SRX: { name: 'Tyler Durden', imageQuery: 'fight-club-brad-pitt-tyler-durden', descriptionPt: 'Tyler Durden é o carismático alter ego do Narrador em Fight Club, de David Fincher, interpretado por Brad Pitt. Simboliza a libertação do consumismo e o colapso da identidade moderna.', descriptionEn: 'Tyler Durden is the charismatic alter ego of the Narrator in David Fincher\'s Fight Club, played by Brad Pitt. He symbolizes liberation from consumerism and the collapse of modern identity.' },
  SRK: { name: 'The Bride', imageQuery: 'kill-bill-uma-thurman-bride', descriptionPt: 'A Noiva (Beatrix Kiddo) é a protagonista de Kill Bill, de Quentin Tarantino, interpretada por Uma Thurman. Uma ex-assassina que busca vingança contra seu antigo mentor e amante, Bill.', descriptionEn: 'The Bride (Beatrix Kiddo) is the protagonist of Quentin Tarantino\'s Kill Bill, played by Uma Thurman. A former assassin seeking revenge against her former mentor and lover, Bill.' },
  SRD: { name: 'Maximus', imageQuery: 'gladiator-russell-crowe-maximus', descriptionPt: 'Maximus Decimus Meridius é o protagonista fictício de Gladiator, interpretado por Russell Crowe. Um general romano traído que busca vingança contra o imperador que assassinou sua família.', descriptionEn: 'Maximus Decimus Meridius is the fictional protagonist of Gladiator, played by Russell Crowe. A betrayed Roman general who seeks revenge against the emperor who murdered his family.' },
  SRL: { name: 'Jack Sparrow', imageQuery: 'pirates-caribbean-jack-sparrow-johnny-depp', descriptionPt: 'Capitão Jack Sparrow é o protagonista da franquia Pirates of the Caribbean, interpretado por Johnny Depp. Um pirata carismático e imprevisível que tornou-se um ícone da cultura pop.', descriptionEn: 'Captain Jack Sparrow is the protagonist of the Pirates of the Caribbean franchise, played by Johnny Depp. A charismatic and unpredictable pirate who became a pop culture icon.' },
};

const PEXELS_IMAGES: Record<string, string> = {
  // Pexels doesn't have specific character images; we use a cinematic/film aesthetic placeholder
};

interface Props {
  personalityId: string;
  language: string;
}

export default function CinematicPersonaCard({ personalityId, language }: Props) {
  const { t } = useTranslation();
  const [showModal, setShowModal] = useState(false);
  const [showEnglish, setShowEnglish] = useState(false);

  const persona = PERSONAS[personalityId];
  if (!persona) return null;

  const isEn = language.startsWith('en') || showEnglish;
  const description = isEn ? persona.descriptionEn : persona.descriptionPt;

  const accentColor = (() => {
    if (!personalityId || personalityId.length < 3) return '#3b82f6';
    const sub = personalityId.charAt(2);
    const map: Record<string, string> = { A: '#f59e0b', B: '#8b5cf6', K: '#ef4444', X: '#3b82f6', D: '#FFFFFF', L: '#10b981' };
    return map[sub] || '#3b82f6';
  })();

  return (
    <>
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5, delay: 0.25 }}
        className="mb-8"
      >
        <button
          onClick={() => setShowModal(true)}
          className="w-full text-left group relative rounded-3xl bg-white/40 dark:bg-gray-800/40 backdrop-blur-xl border border-white/60 dark:border-gray-700/60 shadow-2xl overflow-hidden p-6 hover:shadow-xl transition-all duration-300"
        >
          {/* Background glow */}
          <div
            className="absolute inset-0 opacity-0 group-hover:opacity-100 transition-opacity duration-300 rounded-3xl"
            style={{ background: `radial-gradient(ellipse at top right, ${accentColor}18, transparent 60%)` }}
          />
          <div className="absolute top-0 right-0 w-40 h-40 rounded-full blur-3xl opacity-20"
            style={{ background: accentColor }} />

          <div className="relative z-10 flex items-center gap-5">
            {/* Avatar placeholder */}
            <div
              className="flex-shrink-0 w-16 h-16 rounded-2xl flex items-center justify-center border-2 shadow-lg overflow-hidden"
              style={{ borderColor: `${accentColor}60`, background: `${accentColor}20` }}
            >
              {persona.imageUrl ? (
                <img src={persona.imageUrl} alt={persona.name} className="w-full h-full object-cover" />
              ) : (
                <User className="w-8 h-8" style={{ color: accentColor }} />
              )}
            </div>

            <div className="flex-1 min-w-0">
              <p className="text-xs font-semibold uppercase tracking-widest mb-0.5" style={{ color: accentColor }}>
                {isEn ? 'Your Persona' : 'Sua Persona'}
              </p>
              <h3 className="text-xl font-bold text-gray-900 dark:text-white truncate">
                {persona.name}
              </h3>
              <p className="text-sm text-gray-500 dark:text-gray-400 mt-1 line-clamp-2">
                {isEn ? persona.descriptionEn : persona.descriptionPt}
              </p>
            </div>

            <div
              className="flex-shrink-0 w-8 h-8 rounded-xl flex items-center justify-center opacity-60 group-hover:opacity-100 transition-opacity"
              style={{ background: `${accentColor}30` }}
            >
              <svg className="w-4 h-4" style={{ color: accentColor }} fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
              </svg>
            </div>
          </div>
        </button>
      </motion.div>

      <AnimatePresence>
        {showModal && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 bg-black/70 backdrop-blur-sm z-[9999] flex items-center justify-center p-4"
            onClick={() => setShowModal(false)}
          >
            <motion.div
              initial={{ scale: 0.9, opacity: 0, y: 20 }}
              animate={{ scale: 1, opacity: 1, y: 0 }}
              exit={{ scale: 0.9, opacity: 0, y: 20 }}
              transition={{ type: 'spring', stiffness: 300, damping: 25 }}
              onClick={e => e.stopPropagation()}
              className="relative w-full max-w-md rounded-3xl overflow-hidden shadow-2xl"
              style={{ background: 'rgba(10,10,20,0.92)', border: `1px solid ${accentColor}40` }}
            >
              {/* Top color band */}
              <div className="absolute top-0 inset-x-0 h-1" style={{ background: `linear-gradient(90deg, transparent, ${accentColor}, transparent)` }} />

              {/* Background glow */}
              <div className="absolute top-0 right-0 w-64 h-64 rounded-full blur-3xl opacity-10 pointer-events-none"
                style={{ background: accentColor }} />

              {/* Close button */}
              <button
                onClick={() => setShowModal(false)}
                className="absolute top-4 right-4 z-50 p-2 rounded-xl bg-white/10 hover:bg-white/20 transition-colors cursor-pointer"
              >
                <X className="w-5 h-5 text-white" />
              </button>

              <div className="relative z-10 p-7">
                {/* Avatar */}
                <div className="flex justify-center mb-5">
                  <div
                    className="w-28 h-28 rounded-2xl flex items-center justify-center border-2 shadow-xl overflow-hidden"
                    style={{ borderColor: `${accentColor}80`, background: `${accentColor}25` }}
                  >
                    {persona.imageUrl ? (
                      <img src={persona.imageUrl} alt={persona.name} className="w-full h-full object-cover" />
                    ) : (
                      <User className="w-14 h-14" style={{ color: accentColor }} />
                    )}
                  </div>
                </div>

              {/* Essence badge */}
                <div className="flex justify-center mb-2">
                  <span
                    className="text-xs font-bold uppercase tracking-widest px-3 py-1 rounded-full"
                    style={{ background: `${accentColor}25`, color: accentColor, border: `1px solid ${accentColor}50` }}
                  >
                    {personalityId}
                  </span>
                </div>

                {/* Name */}
                <h2 className="text-2xl font-extrabold text-white text-center mb-4">
                  {persona.name}
                </h2>

                {/* Description */}
                <p className="text-gray-300 text-sm leading-relaxed text-center mb-6">
                  {description}
                </p>

              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </>
  );
}
